### PR TITLE
Performance improvements for HTTP proxy.

### PR DESCRIPTION
**Pull request by dstiliadis**
#### Description
This PR includes several performance improvements for the HTTP proxy.

1. Introduce a token cache that does not require generating new tokens for every request. A token can be created in a fixed time interval. Hardwired to 10s for the time being.

2. Introduce a sync pool for buffers so that the proxy does not constantly allocate and free memory from the operating system. This significantly improves both latency as well as the overhead of garbage collection. 

3. Adapt the transport parameters to allow a larger number of connections to be shared in the underlying transport.

4. Properly configure http/2 between the proxies.

### CODE REVIEW

**Comment by aporeto-dimitri** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "stats",
    "component": "trireme-lib",
    "pr-id": "593",
    "commit-sha": "675079ee393874a397f1a4913002e2179faebdcd"
  },
  {
    "project": "stats",
    "component": "enforcerd",
    "pr-id": "710",
    "commit-sha": "bb40edde26823c8a576940f330509a6defffd590"
  }
]
```

**Comment by aporeto-dimitri** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "stats",
    "component": "trireme-lib",
    "pr-id": "593",
    "commit-sha": "675079ee393874a397f1a4913002e2179faebdcd"
  },
  {
    "project": "stats",
    "component": "enforcerd",
    "pr-id": "710",
    "commit-sha": "0a392382ea308318836c45529bd3b11f93a7b087"
  }
]
```

**Comment by aporeto-dimitri** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "stats",
    "component": "trireme-lib",
    "pr-id": "593",
    "commit-sha": "4472dd6fc0ac545827b511fb92fcbdf530bf41a9"
  },
  {
    "project": "stats",
    "component": "enforcerd",
    "pr-id": "710",
    "commit-sha": "0a392382ea308318836c45529bd3b11f93a7b087"
  }
]
```

**Comment by aporeto-dimitri** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "stats",
    "component": "trireme-lib",
    "pr-id": "593",
    "commit-sha": "e92457cfb7ee8b8729a2eb94d937e6b55967646f"
  },
  {
    "project": "stats",
    "component": "enforcerd",
    "pr-id": "710",
    "commit-sha": "0a392382ea308318836c45529bd3b11f93a7b087"
  }
]
```

**Comment by aporeto-dimitri** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "stats",
    "component": "trireme-lib",
    "pr-id": "593",
    "commit-sha": "097b8b99fc6c1533671105c1714fadce49338ac0"
  },
  {
    "project": "stats",
    "component": "enforcerd",
    "pr-id": "710",
    "commit-sha": "0a392382ea308318836c45529bd3b11f93a7b087"
  }
]
```

**Comment by aporeto-dimitri** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "stats",
    "component": "trireme-lib",
    "pr-id": "593",
    "commit-sha": "dd83879fda5174d96b11cfc63d64a3871685d353"
  },
  {
    "project": "stats",
    "component": "enforcerd",
    "pr-id": "710",
    "commit-sha": "0a392382ea308318836c45529bd3b11f93a7b087"
  }
]
```

**Comment by aporeto-dimitri** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "stats",
    "component": "trireme-lib",
    "pr-id": "593",
    "commit-sha": "492d0be6cf01a7beb59c0c4662dcafe40d30b2d6"
  },
  {
    "project": "stats",
    "component": "enforcerd",
    "pr-id": "710",
    "commit-sha": "0a392382ea308318836c45529bd3b11f93a7b087"
  }
]
```

**Comment by aporeto-dimitri** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "stats",
    "component": "trireme-lib",
    "pr-id": "593",
    "commit-sha": "f95b5eb6ec9e50dfd6308ccfd97a957d87a53f01"
  },
  {
    "project": "stats",
    "component": "enforcerd",
    "pr-id": "710",
    "commit-sha": "0a392382ea308318836c45529bd3b11f93a7b087"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "stats",
    "component": "trireme-lib",
    "pr-id": "593",
    "commit-sha": "ca17122ba3bba74e4fd5e09a39c0102ea87ee488"
  },
  {
    "project": "stats",
    "component": "enforcerd",
    "pr-id": "710",
    "commit-sha": "0a392382ea308318836c45529bd3b11f93a7b087"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "stats",
    "component": "trireme-lib",
    "pr-id": "593",
    "commit-sha": "ca17122ba3bba74e4fd5e09a39c0102ea87ee488"
  },
  {
    "project": "stats",
    "component": "enforcerd",
    "pr-id": "710",
    "commit-sha": "1864fdd57c31623392518c432ee3811c3fc6d2a1"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "stats",
    "component": "trireme-lib",
    "pr-id": "593",
    "commit-sha": "d252c32551c1ba77cab2032968e1cae4cc7e3ab1"
  },
  {
    "project": "stats",
    "component": "enforcerd",
    "pr-id": "710",
    "commit-sha": "1864fdd57c31623392518c432ee3811c3fc6d2a1"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "stats",
    "component": "trireme-lib",
    "pr-id": "593",
    "commit-sha": "d252c32551c1ba77cab2032968e1cae4cc7e3ab1"
  },
  {
    "project": "stats",
    "component": "enforcerd",
    "pr-id": "710",
    "commit-sha": "1864fdd57c31623392518c432ee3811c3fc6d2a1"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "stats",
    "component": "trireme-lib",
    "pr-id": "593",
    "commit-sha": "e07c9d99bff1ecf8efb812253c51790a47eec023"
  },
  {
    "project": "stats",
    "component": "enforcerd",
    "pr-id": "710",
    "commit-sha": "2a82ac4fe3a2f5e89553deab1794a24f2fc07462"
  }
]
```

**Review by varks — APPROVED** [review]

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "stats",
    "component": "trireme-lib",
    "pr-id": "593",
    "commit-sha": "d9bac24d27593ff807ca29b0149733d3fbe0bd56"
  },
  {
    "project": "stats",
    "component": "enforcerd",
    "pr-id": "710",
    "commit-sha": "2a82ac4fe3a2f5e89553deab1794a24f2fc07462"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "stats",
    "component": "trireme-lib",
    "pr-id": "593",
    "commit-sha": "98c3a2b8e6a1c548177ecc95b0c78daf2512f57a"
  },
  {
    "project": "stats",
    "component": "enforcerd",
    "pr-id": "710",
    "commit-sha": "2a82ac4fe3a2f5e89553deab1794a24f2fc07462"
  }
]
```

**Pull request merged**
