### PR TITLE
new: ping

### PR DESCRIPTION
**Pull request by sibicramesh**
--> Ping is an inbuilt diagnostic tool.
--> The control message has
```go
type PingConfig struct {
	Type     claimsheader.PingType     // Custom, Default and DefaultPassthrough
	IP       net.IP                     // Destination IP
	Ports    []*portspec.PortSpec        // Destination ports
	Requests int                      // Number of requests
}
```
--> There are three ping types,

- DefaultIdentity - The response from the enforcer will have the default token untouched and the signature validation will be performed. 

- CustomIdentity - The response from the enforcer will have custom information collected by the server enforcer. No validation will be performed. Msgpack is used for encoding.

```go
type customIdentity struct {
	AgentVersion         string
	TransmitterID        string
	TransmitterNamespace string
	FlowTuple            string
}
```

- DefaultIdentityPassthrough - Similar to DefaultIdentity but the request is allowed to the application and the application responds back to the client.

--> The report is on request and response which has
```go
type PingReport struct {
	SourceID             string               
	SourceNamespace      string     
	DestinationID        string             
	DestinationNamespace string
	FlowTuple            string
	Latency              string
	AgentVersion         string
	Protocol             int
	ServiceType          string
	PayloadSize          int
	Request              int
	Type                 claimsheader.PingType
	Stage                Stage
	SessionID            string
}
```

Important legends
```
Stage - Identifies whether its origin (syn sent) or reply (synack recv) report.
SessionID - Unique across origin and reply report.
FlowTuple - <sip:dip:spt:dpt>
Latency - Is the delay between the request and response (syn  sent -- synack recv)
```

Some details to note,
--> It supports both trireme v1 and v2.
--> The diagnosis ends at network synack.

### CODE REVIEW

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "ping",
    "component": "trireme-lib",
    "pr-id": "932",
    "commit-sha": "bfbe325d4e058ca0c626e8426bfeadc5e17634d2"
  },
  {
    "project": "ping",
    "component": "backend",
    "pr-id": "652",
    "commit-sha": "90e46493079974dae53795f0fa8d64f6dee79534"
  },
  {
    "project": "ping",
    "component": "gaia",
    "pr-id": "443",
    "commit-sha": "bcaeba8e254833edae0fd8060ff977aec237f243"
  },
  {
    "project": "ping",
    "component": "apoctl",
    "pr-id": "215",
    "commit-sha": "3f8547a748ea24aff95b3dc5b2ff03379fdd6a61"
  },
  {
    "project": "ping",
    "component": "enforcerd",
    "pr-id": "1526",
    "commit-sha": "58713c5532a52a5d683831521779ef9ab22d7321"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "ping",
    "component": "apoctl",
    "pr-id": "215",
    "commit-sha": "3f8547a748ea24aff95b3dc5b2ff03379fdd6a61"
  },
  {
    "project": "ping",
    "component": "enforcerd",
    "pr-id": "1526",
    "commit-sha": "4c139c0b53dfee0ad98d434a10edc3bd29189386"
  },
  {
    "project": "ping",
    "component": "trireme-lib",
    "pr-id": "932",
    "commit-sha": "bfbe325d4e058ca0c626e8426bfeadc5e17634d2"
  },
  {
    "project": "ping",
    "component": "backend",
    "pr-id": "652",
    "commit-sha": "90e46493079974dae53795f0fa8d64f6dee79534"
  },
  {
    "project": "ping",
    "component": "gaia",
    "pr-id": "443",
    "commit-sha": "bcaeba8e254833edae0fd8060ff977aec237f243"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "ping",
    "component": "enforcerd",
    "pr-id": "1526",
    "commit-sha": "4c139c0b53dfee0ad98d434a10edc3bd29189386"
  },
  {
    "project": "ping",
    "component": "trireme-lib",
    "pr-id": "932",
    "commit-sha": "a33a1efc51e84eb3b971fb124ee463d0a6d3f86e"
  },
  {
    "project": "ping",
    "component": "backend",
    "pr-id": "652",
    "commit-sha": "90e46493079974dae53795f0fa8d64f6dee79534"
  },
  {
    "project": "ping",
    "component": "gaia",
    "pr-id": "443",
    "commit-sha": "bcaeba8e254833edae0fd8060ff977aec237f243"
  },
  {
    "project": "ping",
    "component": "apoctl",
    "pr-id": "215",
    "commit-sha": "3f8547a748ea24aff95b3dc5b2ff03379fdd6a61"
  }
]
```

**Review by amitlimaye — DISMISSED** [review]

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "ping",
    "component": "apoctl",
    "pr-id": "215",
    "commit-sha": "400ca4554ce09466358954ea1e4008379d0269e2"
  },
  {
    "project": "ping",
    "component": "enforcerd",
    "pr-id": "1526",
    "commit-sha": "3b321008c7a8521a95eb073d4ed91056ea42082a"
  },
  {
    "project": "ping",
    "component": "trireme-lib",
    "pr-id": "932",
    "commit-sha": "8947f6ed048da5524e9409ae2b6151f119050708"
  },
  {
    "project": "ping",
    "component": "backend",
    "pr-id": "652",
    "commit-sha": "5d78ea3dc0a01ec77780a5f34abcb19352f6ae51"
  },
  {
    "project": "ping",
    "component": "gaia",
    "pr-id": "443",
    "commit-sha": "bcaeba8e254833edae0fd8060ff977aec237f243"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "ping",
    "component": "backend",
    "pr-id": "652",
    "commit-sha": "5d78ea3dc0a01ec77780a5f34abcb19352f6ae51"
  },
  {
    "project": "ping",
    "component": "gaia",
    "pr-id": "443",
    "commit-sha": "bcaeba8e254833edae0fd8060ff977aec237f243"
  },
  {
    "project": "ping",
    "component": "apoctl",
    "pr-id": "215",
    "commit-sha": "400ca4554ce09466358954ea1e4008379d0269e2"
  },
  {
    "project": "ping",
    "component": "enforcerd",
    "pr-id": "1526",
    "commit-sha": "3b321008c7a8521a95eb073d4ed91056ea42082a"
  },
  {
    "project": "ping",
    "component": "trireme-lib",
    "pr-id": "932",
    "commit-sha": "ac6ea2fe34bb114d0629bc3062bb09048129189b"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "ping",
    "component": "enforcerd",
    "pr-id": "1526",
    "commit-sha": "03b97cf9c989f19574bf74f3eed6aa64f9f40951"
  },
  {
    "project": "ping",
    "component": "trireme-lib",
    "pr-id": "932",
    "commit-sha": "35784888654ca1099978fa91a3e62c1f6aa3e81c"
  },
  {
    "project": "ping",
    "component": "backend",
    "pr-id": "652",
    "commit-sha": "87e4b7d2f8b50ae587f5a8903000d7cb7942730b"
  },
  {
    "project": "ping",
    "component": "gaia",
    "pr-id": "443",
    "commit-sha": "0ac4dfa5b6ae0a04541aeb9daa91d1b1e8c7df94"
  },
  {
    "project": "ping",
    "component": "apoctl",
    "pr-id": "215",
    "commit-sha": "a0079eddbcc1cac17604796c545f612fbb155ff5"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "ping",
    "component": "enforcerd",
    "pr-id": "1526",
    "commit-sha": "03b97cf9c989f19574bf74f3eed6aa64f9f40951"
  },
  {
    "project": "ping",
    "component": "trireme-lib",
    "pr-id": "932",
    "commit-sha": "35784888654ca1099978fa91a3e62c1f6aa3e81c"
  },
  {
    "project": "ping",
    "component": "backend",
    "pr-id": "652",
    "commit-sha": "4780ccd592fce9010118054bcb30a7026f927f2f"
  },
  {
    "project": "ping",
    "component": "gaia",
    "pr-id": "443",
    "commit-sha": "0ac4dfa5b6ae0a04541aeb9daa91d1b1e8c7df94"
  },
  {
    "project": "ping",
    "component": "apoctl",
    "pr-id": "215",
    "commit-sha": "b32602f6994ccd46db0f5775d2a01a191bac4770"
  }
]
```

**Review by amitlimaye — APPROVED** [review]

**Pull request merged**
