### PR TITLE
Enhancements to host mode

### PR DESCRIPTION
**Pull request by varks**

### CODE REVIEW

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "hostmode",
    "component": "backend",
    "pr-id": "140",
    "commit-sha": "2df0ab0726d01136686e5674495e2c99d4edf22b"
  },
  {
    "project": "hostmode",
    "component": "apotests",
    "pr-id": "1818",
    "commit-sha": "fdba1a626a5776114b3efc0ffff33c30df5f9cec"
  },
  {
    "project": "hostmode",
    "component": "integrations-lib",
    "pr-id": "46",
    "commit-sha": "81ffde56602173304f36d3ef076b1ccd8dd1d75a"
  },
  {
    "project": "hostmode",
    "component": "trireme-lib",
    "pr-id": "654",
    "commit-sha": "107c8b99893a3b214435396e7dfaeb0ebab09bd3"
  },
  {
    "project": "hostmode",
    "component": "enforcerd",
    "pr-id": "834",
    "commit-sha": "c906954cc6c6b4d93c0309a25f4042240b667146"
  },
  {
    "project": "hostmode",
    "component": "apoctl",
    "pr-id": "149",
    "commit-sha": "b25d81e49ac59bbf91b9784bee29a82b88768e64"
  },
  {
    "project": "hostmode",
    "component": "clad",
    "pr-id": "784",
    "commit-sha": "bd931d6da311a8e08ac6e71f4075adcaefa0d025"
  },
  {
    "project": "hostmode",
    "component": "gaia",
    "pr-id": "202",
    "commit-sha": "de76179c042162144d37a1880a3b4a50629e00f9"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "hostmode",
    "component": "clad",
    "pr-id": "784",
    "commit-sha": "bd931d6da311a8e08ac6e71f4075adcaefa0d025"
  },
  {
    "project": "hostmode",
    "component": "gaia",
    "pr-id": "202",
    "commit-sha": "de76179c042162144d37a1880a3b4a50629e00f9"
  },
  {
    "project": "hostmode",
    "component": "backend",
    "pr-id": "140",
    "commit-sha": "2df0ab0726d01136686e5674495e2c99d4edf22b"
  },
  {
    "project": "hostmode",
    "component": "apotests",
    "pr-id": "1818",
    "commit-sha": "fdba1a626a5776114b3efc0ffff33c30df5f9cec"
  },
  {
    "project": "hostmode",
    "component": "integrations-lib",
    "pr-id": "46",
    "commit-sha": "81ffde56602173304f36d3ef076b1ccd8dd1d75a"
  },
  {
    "project": "hostmode",
    "component": "trireme-lib",
    "pr-id": "654",
    "commit-sha": "d2e4d303a6100e3348f21c90e0e3f8bd61a06561"
  },
  {
    "project": "hostmode",
    "component": "enforcerd",
    "pr-id": "834",
    "commit-sha": "e634fc5856602fd11c74cbd14d85aae753f26bd5"
  },
  {
    "project": "hostmode",
    "component": "apoctl",
    "pr-id": "149",
    "commit-sha": "b25d81e49ac59bbf91b9784bee29a82b88768e64"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "654",
    "commit-sha": "72ba70c3567df05b10f479fc3b68f0ad63c063ec"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "654",
    "commit-sha": "307221dfe7a4e6181beef2494603a0e17465a00d"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "654",
    "commit-sha": "f749344c7b6900da327035d596549a59b71e0f7f"
  }
]
```

**Review by dstiliadis — APPROVED** [review]

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "654",
    "commit-sha": "d9cf59335e9128b9ce6345edccbbb994813c2bc9"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "654",
    "commit-sha": "b181208e7d18517e0d558b81275edf287aac62d4"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "hostmode",
    "component": "apoctl",
    "pr-id": "149",
    "commit-sha": "b25d81e49ac59bbf91b9784bee29a82b88768e64"
  },
  {
    "project": "hostmode",
    "component": "clad",
    "pr-id": "784",
    "commit-sha": "e04124cf803fe76e8f0ddaa52d08f91857b51fc5"
  },
  {
    "project": "hostmode",
    "component": "gaia",
    "pr-id": "202",
    "commit-sha": "85a6ac714237815ea175634bed8612b424d0dd2f"
  },
  {
    "project": "hostmode",
    "component": "backend",
    "pr-id": "140",
    "commit-sha": "1b62efbe48210d48bce6a7c2d70c3231143f6cf4"
  },
  {
    "project": "hostmode",
    "component": "apotests",
    "pr-id": "1818",
    "commit-sha": "fdba1a626a5776114b3efc0ffff33c30df5f9cec"
  },
  {
    "project": "hostmode",
    "component": "integrations-lib",
    "pr-id": "46",
    "commit-sha": "81ffde56602173304f36d3ef076b1ccd8dd1d75a"
  },
  {
    "project": "hostmode",
    "component": "trireme-lib",
    "pr-id": "654",
    "commit-sha": "56d81c54a5d61b40bbfcc3cd06dc995add602a11"
  },
  {
    "project": "hostmode",
    "component": "enforcerd",
    "pr-id": "834",
    "commit-sha": "d31bc84cb7b8ab7c6d1fb4c35c32255c0900ecfd"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "hostmode",
    "component": "integrations-lib",
    "pr-id": "46",
    "commit-sha": "e482e21990de307d1364804b6e63b851cfd53d1b"
  },
  {
    "project": "hostmode",
    "component": "trireme-lib",
    "pr-id": "654",
    "commit-sha": "dd1f36c97cdbd20ea06e42808ab2eff59e6308c7"
  },
  {
    "project": "hostmode",
    "component": "enforcerd",
    "pr-id": "834",
    "commit-sha": "6ab12fc674482477b8c0391b74456e687816cbb4"
  },
  {
    "project": "hostmode",
    "component": "apoctl",
    "pr-id": "149",
    "commit-sha": "b25d81e49ac59bbf91b9784bee29a82b88768e64"
  },
  {
    "project": "hostmode",
    "component": "clad",
    "pr-id": "784",
    "commit-sha": "e04124cf803fe76e8f0ddaa52d08f91857b51fc5"
  },
  {
    "project": "hostmode",
    "component": "gaia",
    "pr-id": "202",
    "commit-sha": "85a6ac714237815ea175634bed8612b424d0dd2f"
  },
  {
    "project": "hostmode",
    "component": "backend",
    "pr-id": "140",
    "commit-sha": "9c19fc5f91a948b8d0f727a14cb05d50ccf3b561"
  },
  {
    "project": "hostmode",
    "component": "apotests",
    "pr-id": "1818",
    "commit-sha": "fdba1a626a5776114b3efc0ffff33c30df5f9cec"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "hostmode",
    "component": "trireme-lib",
    "pr-id": "654",
    "commit-sha": "dd1f36c97cdbd20ea06e42808ab2eff59e6308c7"
  },
  {
    "project": "hostmode",
    "component": "enforcerd",
    "pr-id": "834",
    "commit-sha": "6ab12fc674482477b8c0391b74456e687816cbb4"
  },
  {
    "project": "hostmode",
    "component": "apoctl",
    "pr-id": "149",
    "commit-sha": "b25d81e49ac59bbf91b9784bee29a82b88768e64"
  },
  {
    "project": "hostmode",
    "component": "clad",
    "pr-id": "784",
    "commit-sha": "e04124cf803fe76e8f0ddaa52d08f91857b51fc5"
  },
  {
    "project": "hostmode",
    "component": "gaia",
    "pr-id": "202",
    "commit-sha": "85a6ac714237815ea175634bed8612b424d0dd2f"
  },
  {
    "project": "hostmode",
    "component": "backend",
    "pr-id": "140",
    "commit-sha": "3c7f839b9e64672c91a32b8fd29c653a03e97f8e"
  },
  {
    "project": "hostmode",
    "component": "apotests",
    "pr-id": "1818",
    "commit-sha": "adf20a4f98b7fd73434856966ddfba28bc80350c"
  },
  {
    "project": "hostmode",
    "component": "integrations-lib",
    "pr-id": "46",
    "commit-sha": "e482e21990de307d1364804b6e63b851cfd53d1b"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "hostmode",
    "component": "apotests",
    "pr-id": "1818",
    "commit-sha": "adf20a4f98b7fd73434856966ddfba28bc80350c"
  },
  {
    "project": "hostmode",
    "component": "integrations-lib",
    "pr-id": "46",
    "commit-sha": "e482e21990de307d1364804b6e63b851cfd53d1b"
  },
  {
    "project": "hostmode",
    "component": "trireme-lib",
    "pr-id": "654",
    "commit-sha": "dd1f36c97cdbd20ea06e42808ab2eff59e6308c7"
  },
  {
    "project": "hostmode",
    "component": "enforcerd",
    "pr-id": "834",
    "commit-sha": "6ab12fc674482477b8c0391b74456e687816cbb4"
  },
  {
    "project": "hostmode",
    "component": "apoctl",
    "pr-id": "149",
    "commit-sha": "b25d81e49ac59bbf91b9784bee29a82b88768e64"
  },
  {
    "project": "hostmode",
    "component": "clad",
    "pr-id": "784",
    "commit-sha": "e04124cf803fe76e8f0ddaa52d08f91857b51fc5"
  },
  {
    "project": "hostmode",
    "component": "gaia",
    "pr-id": "202",
    "commit-sha": "85a6ac714237815ea175634bed8612b424d0dd2f"
  },
  {
    "project": "hostmode",
    "component": "backend",
    "pr-id": "140",
    "commit-sha": "3c7f839b9e64672c91a32b8fd29c653a03e97f8e"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "hostmode",
    "component": "backend",
    "pr-id": "140",
    "commit-sha": "3c7f839b9e64672c91a32b8fd29c653a03e97f8e"
  },
  {
    "project": "hostmode",
    "component": "apotests",
    "pr-id": "1818",
    "commit-sha": "adf20a4f98b7fd73434856966ddfba28bc80350c"
  },
  {
    "project": "hostmode",
    "component": "integrations-lib",
    "pr-id": "46",
    "commit-sha": "e482e21990de307d1364804b6e63b851cfd53d1b"
  },
  {
    "project": "hostmode",
    "component": "trireme-lib",
    "pr-id": "654",
    "commit-sha": "dd1f36c97cdbd20ea06e42808ab2eff59e6308c7"
  },
  {
    "project": "hostmode",
    "component": "enforcerd",
    "pr-id": "834",
    "commit-sha": "6ab12fc674482477b8c0391b74456e687816cbb4"
  },
  {
    "project": "hostmode",
    "component": "apoctl",
    "pr-id": "149",
    "commit-sha": "b25d81e49ac59bbf91b9784bee29a82b88768e64"
  },
  {
    "project": "hostmode",
    "component": "clad",
    "pr-id": "784",
    "commit-sha": "e04124cf803fe76e8f0ddaa52d08f91857b51fc5"
  },
  {
    "project": "hostmode",
    "component": "gaia",
    "pr-id": "202",
    "commit-sha": "85a6ac714237815ea175634bed8612b424d0dd2f"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "hostmode",
    "component": "apotests",
    "pr-id": "1818",
    "commit-sha": "4206b4f1a137002cc4343d34fcb64375cc5e7d0a"
  },
  {
    "project": "hostmode",
    "component": "integrations-lib",
    "pr-id": "46",
    "commit-sha": "e482e21990de307d1364804b6e63b851cfd53d1b"
  },
  {
    "project": "hostmode",
    "component": "trireme-lib",
    "pr-id": "654",
    "commit-sha": "dd1f36c97cdbd20ea06e42808ab2eff59e6308c7"
  },
  {
    "project": "hostmode",
    "component": "enforcerd",
    "pr-id": "834",
    "commit-sha": "6ab12fc674482477b8c0391b74456e687816cbb4"
  },
  {
    "project": "hostmode",
    "component": "apoctl",
    "pr-id": "149",
    "commit-sha": "b25d81e49ac59bbf91b9784bee29a82b88768e64"
  },
  {
    "project": "hostmode",
    "component": "clad",
    "pr-id": "784",
    "commit-sha": "e04124cf803fe76e8f0ddaa52d08f91857b51fc5"
  },
  {
    "project": "hostmode",
    "component": "gaia",
    "pr-id": "202",
    "commit-sha": "85a6ac714237815ea175634bed8612b424d0dd2f"
  },
  {
    "project": "hostmode",
    "component": "backend",
    "pr-id": "140",
    "commit-sha": "3c7f839b9e64672c91a32b8fd29c653a03e97f8e"
  }
]
```

**Review by sibicramesh — APPROVED** [review]
LGTM

**Pull request merged**
