### PR TITLE
new func to cleanup rule of old version

### PR DESCRIPTION
**Pull request by amitlimaye**
#### Description
*Changes proposed in this pull request.*

#### Test plan
*Outline the test plan used to test this change before merging it.*

> Fixes #.

### CODE REVIEW

**Comment by amitlimaye** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1371",
    "commit-sha": "71c718b3d630438b2d45aa55e1bf5f1d0af4dfc5"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "865",
    "commit-sha": "6053741d38a12c8286822a01cad94bdc7d1a6ffa"
  }
]
```

**Review by dstiliadis — DISMISSED** [review]
see inline

**Comment by amitlimaye** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "865",
    "commit-sha": "6053741d38a12c8286822a01cad94bdc7d1a6ffa"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1371",
    "commit-sha": "71c718b3d630438b2d45aa55e1bf5f1d0af4dfc5"
  }
]
```

**Comment by amitlimaye** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1371",
    "commit-sha": "71c718b3d630438b2d45aa55e1bf5f1d0af4dfc5"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "865",
    "commit-sha": "3c78271aa191f5766a9e64b95f242bf1aa52bb4a"
  }
]
```

**Comment by amitlimaye** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1371",
    "commit-sha": "71c718b3d630438b2d45aa55e1bf5f1d0af4dfc5"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "865",
    "commit-sha": "7c42dda8b61c079cb34d1bfb576c6a5213212681"
  }
]
```

**Review by satyamsi — APPROVED** [review]

**Pull request merged**
