### PR TITLE
Report correct src id and dst id in flow report

### PR DESCRIPTION
**Pull request by varks**

### CODE REVIEW

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "enforcerd-reporting",
    "component": "enforcerd",
    "pr-id": "993",
    "commit-sha": "d74ed8826868c64d49ea3c19b9a897e4f83b7918"
  },
  {
    "project": "enforcerd-reporting",
    "component": "trireme-lib",
    "pr-id": "709",
    "commit-sha": "142973e85b64db6af792bcaca1cc8468d2e354f2"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "enforcerd-reporting",
    "component": "enforcerd",
    "pr-id": "993",
    "commit-sha": "d74ed8826868c64d49ea3c19b9a897e4f83b7918"
  },
  {
    "project": "enforcerd-reporting",
    "component": "trireme-lib",
    "pr-id": "709",
    "commit-sha": "336ad20d84c29c265e910a15be14f489453dc404"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "enforcerd-reporting",
    "component": "trireme-lib",
    "pr-id": "709",
    "commit-sha": "302d738bb68c7ab2dfeace07e136362e9cabf3c6"
  },
  {
    "project": "enforcerd-reporting",
    "component": "enforcerd",
    "pr-id": "993",
    "commit-sha": "d74ed8826868c64d49ea3c19b9a897e4f83b7918"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "enforcerd-reporting",
    "component": "trireme-lib",
    "pr-id": "709",
    "commit-sha": "1fc3012269c4b2f49a64987b329c66314c1357fb"
  },
  {
    "project": "enforcerd-reporting",
    "component": "enforcerd",
    "pr-id": "993",
    "commit-sha": "19e4367330af80c35bde7e9aab84f840581e3a13"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "enforcerd-reporting",
    "component": "enforcerd",
    "pr-id": "993",
    "commit-sha": "19e4367330af80c35bde7e9aab84f840581e3a13"
  },
  {
    "project": "enforcerd-reporting",
    "component": "trireme-lib",
    "pr-id": "709",
    "commit-sha": "556b4cd479e027bff4b10d104524322866452a55"
  }
]
```

**Review by 0xmchadha — APPROVED** [review]

**Pull request merged**
