### PR TITLE
fix: pu name being reveresed when claims are bad

### PR DESCRIPTION
**Pull request by sibicramesh**
--> When the token is missing or invalid, we mistakenly reverse the pu name and report it.

### CODE REVIEW

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1559",
    "commit-sha": "be66ef983d16066066a6c086c8350ab2b3978a41",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "958",
    "commit-sha": "f6499faa94a16f134c7de907e1dcf0f850db2aaa",
    "pipeline": "master"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1567",
    "commit-sha": "0e0f4cfd3c49c71152da486af872071aa789bff7",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "958",
    "commit-sha": "f6499faa94a16f134c7de907e1dcf0f850db2aaa",
    "pipeline": "master"
  }
]
```

**Review by 0xmchadha — DISMISSED** [review]

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1582",
    "commit-sha": "523ed33fd6f27d7ceb602edd200900645bf32ddf",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "958",
    "commit-sha": "ffadee9b09c2719d374e2c14eb5a23eb2590ef4d",
    "pipeline": "master"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1582",
    "commit-sha": "523ed33fd6f27d7ceb602edd200900645bf32ddf",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "958",
    "commit-sha": "ffadee9b09c2719d374e2c14eb5a23eb2590ef4d",
    "pipeline": "master"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1582",
    "commit-sha": "523ed33fd6f27d7ceb602edd200900645bf32ddf",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "958",
    "commit-sha": "ffadee9b09c2719d374e2c14eb5a23eb2590ef4d",
    "pipeline": "master"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1586",
    "commit-sha": "74fdae0273e9e9cf26b86c990f53aa90f6f3dc34",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "958",
    "commit-sha": "ffadee9b09c2719d374e2c14eb5a23eb2590ef4d",
    "pipeline": "master"
  }
]
```

**Review by amitlimaye — APPROVED** [review]

**Pull request merged**
