### PR TITLE
use executable path to calculate file checksum tag for linux pus

### PR DESCRIPTION
**Pull request by varks**

### CODE REVIEW

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "fix_tags",
    "component": "trireme-lib",
    "pr-id": "719",
    "commit-sha": "dc287af09ea316b36ac83a73c7aa6f140be7a99f"
  },
  {
    "project": "fix_tags",
    "component": "enforcerd",
    "pr-id": "991",
    "commit-sha": "fc381236072c396cf14a134e11cae65ef49bfb4a"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "fix_tags",
    "component": "trireme-lib",
    "pr-id": "719",
    "commit-sha": "dc287af09ea316b36ac83a73c7aa6f140be7a99f"
  },
  {
    "project": "fix_tags",
    "component": "enforcerd",
    "pr-id": "991",
    "commit-sha": "fc381236072c396cf14a134e11cae65ef49bfb4a"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "719",
    "commit-sha": "87029bae1554e9a7e3ae4b4c03e8cbbfe8049932"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "fix_tags",
    "component": "trireme-lib",
    "pr-id": "719",
    "commit-sha": "87029bae1554e9a7e3ae4b4c03e8cbbfe8049932"
  },
  {
    "project": "fix_tags",
    "component": "enforcerd",
    "pr-id": "991",
    "commit-sha": "fc381236072c396cf14a134e11cae65ef49bfb4a"
  }
]
```

**Review by amitlimaye — APPROVED** [review]

**Pull request merged**
