### PR TITLE
Support services(TCP, HTTP) with ipv6

### PR DESCRIPTION
**Pull request by 0xmchadha**

### CODE REVIEW

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1128",
    "commit-sha": "4d53cbff6da97c6ae24b1ceffed9399e023c060e"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "818",
    "commit-sha": "c7a5ee41cb037f454af4c3d9eced1ddeb43bb03c"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1128",
    "commit-sha": "4d53cbff6da97c6ae24b1ceffed9399e023c060e"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "818",
    "commit-sha": "c7a5ee41cb037f454af4c3d9eced1ddeb43bb03c"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1138",
    "commit-sha": "3d8cc38ab58af29f63d70fe1bf90ab544ef1bf71"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "818",
    "commit-sha": "c7a5ee41cb037f454af4c3d9eced1ddeb43bb03c"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1138",
    "commit-sha": "3d8cc38ab58af29f63d70fe1bf90ab544ef1bf71"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "818",
    "commit-sha": "13c67c21c8b965ce4b5c4b88986073fb21c04fe0"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1138",
    "commit-sha": "cf7e17f20ed4d1532f6379b4f71c0e09511daa6d"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "818",
    "commit-sha": "13c67c21c8b965ce4b5c4b88986073fb21c04fe0"
  }
]
```

**Review by dstiliadis — APPROVED** [review]

**Pull request merged**
