### PR TITLE
Return early if options are bad

### PR DESCRIPTION
**Pull request by amitlimaye**
#### Description
*Changes proposed in this pull request.*

#### Test plan
*Outline the test plan used to test this change before merging it.*

> Fixes #.

### CODE REVIEW

**Comment by amitlimaye** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "962",
    "commit-sha": "fe3f0fbce4cb47e714c9db46cd1d7afe118670ba",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1574",
    "commit-sha": "d2855202f3985a58577ca270e0ae7a0c209b569a",
    "pipeline": "master"
  }
]
```

**Comment by amitlimaye** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "962",
    "commit-sha": "bb09607e4bb6ad8943aa06c741d0c19eb5c1ae87",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1574",
    "commit-sha": "d2855202f3985a58577ca270e0ae7a0c209b569a",
    "pipeline": "master"
  }
]
```

**Comment by amitlimaye** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "962",
    "commit-sha": "bb09607e4bb6ad8943aa06c741d0c19eb5c1ae87",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1574",
    "commit-sha": "ad7bc4f141ca6d5d2bc30ca056e2dee41f50a9ef",
    "pipeline": "master"
  }
]
```

**Comment by amitlimaye** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1574",
    "commit-sha": "85189b672150886f8ac12933689b3ba2798bfd15",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "962",
    "commit-sha": "bb09607e4bb6ad8943aa06c741d0c19eb5c1ae87",
    "pipeline": "master"
  }
]
```

**Comment by amitlimaye** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1574",
    "commit-sha": "7b33a264b0f84de6e455b490b36b34f056b60434",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "962",
    "commit-sha": "bb09607e4bb6ad8943aa06c741d0c19eb5c1ae87",
    "pipeline": "master"
  }
]
```

**Comment by amitlimaye** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "962",
    "commit-sha": "44345a69112c3efd5ac26b39bb02e26cc04cc12f",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1574",
    "commit-sha": "7b33a264b0f84de6e455b490b36b34f056b60434",
    "pipeline": "master"
  }
]
```

**Comment by amitlimaye** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1578",
    "commit-sha": "eeafa00a136851bd20b42909ccf53d26e943d10e",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "962",
    "commit-sha": "44345a69112c3efd5ac26b39bb02e26cc04cc12f",
    "pipeline": "master"
  }
]
```

**Review by sibicramesh — DISMISSED** [review]

**Comment by amitlimaye** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1578",
    "commit-sha": "eeafa00a136851bd20b42909ccf53d26e943d10e",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "962",
    "commit-sha": "8669713e93164052f766172a07ae453a5c958cdf",
    "pipeline": "master"
  }
]
```

**Pull request closed without merging**
