### PR TITLE
Fix: Move compression types from constants to dedicated pkg

### PR DESCRIPTION
**Pull request by sibicramesh**
--> Make compression type to int enum
--> This refactoring is needed for another PR (handshake metadata)

### CODE REVIEW

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "refactor-compression",
    "component": "trireme-lib",
    "pr-id": "716",
    "commit-sha": "14e340e34a0d9f257abc8ecb6fe8de2573914b69"
  },
  {
    "project": "refactor-compression",
    "component": "enforcerd",
    "pr-id": "988",
    "commit-sha": "c5279728cd80227a3abf3565af46cd3b06f74918"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "refactor-compression",
    "component": "enforcerd",
    "pr-id": "988",
    "commit-sha": "6be854dc6b4e751fdc9b833b1389ae9b97bf4b71"
  },
  {
    "project": "refactor-compression",
    "component": "trireme-lib",
    "pr-id": "716",
    "commit-sha": "376aa09fae6f4e4992198e5e44b3c3cedd7abb00"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "refactor-compression",
    "component": "enforcerd",
    "pr-id": "988",
    "commit-sha": "8b100b1d4cdb038faac053877072d784fc0441d7"
  },
  {
    "project": "refactor-compression",
    "component": "trireme-lib",
    "pr-id": "716",
    "commit-sha": "5834ed4d254a36d33496be4f7cfca0567ebac6a5"
  }
]
```

**Review by varks — DISMISSED** [review]

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "refactor-compression",
    "component": "trireme-lib",
    "pr-id": "716",
    "commit-sha": "b52aeb0a6d3bc3c8c6287822500d9bc05dbebbc1"
  },
  {
    "project": "refactor-compression",
    "component": "enforcerd",
    "pr-id": "988",
    "commit-sha": "8b100b1d4cdb038faac053877072d784fc0441d7"
  }
]
```

**Review by sooryamanian91 — APPROVED** [review]

**Pull request merged**
