### PR TITLE
Support more complex claim matching rules (ORs of ANDs)

### PR DESCRIPTION
**Pull request by dstiliadis**
#### Description
Add support for more complex rules in matching APIs to claims. Support for an ORs of ANDs where each AND clause is a set of claims. This enables better definition of claims match criteria.

### CODE REVIEW

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "claims",
    "component": "trireme-lib",
    "pr-id": "694",
    "commit-sha": "44bcd592d0d1140237b726a61109fafb4a52692d"
  },
  {
    "project": "claims",
    "component": "gaia",
    "pr-id": "229",
    "commit-sha": "e441ef76cdb691f2d2877444fa49d212d58f521e"
  },
  {
    "project": "claims",
    "component": "enforcerd",
    "pr-id": "940",
    "commit-sha": "b719706d8310eec231c81773316e9d409811ca85"
  },
  {
    "project": "claims",
    "component": "backend",
    "pr-id": "223",
    "commit-sha": "7a48b9f760dfe46a9422145b4f772b2398b6135c"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "claims",
    "component": "trireme-lib",
    "pr-id": "694",
    "commit-sha": "44bcd592d0d1140237b726a61109fafb4a52692d"
  },
  {
    "project": "claims",
    "component": "gaia",
    "pr-id": "229",
    "commit-sha": "e441ef76cdb691f2d2877444fa49d212d58f521e"
  },
  {
    "project": "claims",
    "component": "enforcerd",
    "pr-id": "940",
    "commit-sha": "b719706d8310eec231c81773316e9d409811ca85"
  },
  {
    "project": "claims",
    "component": "backend",
    "pr-id": "223",
    "commit-sha": "7a48b9f760dfe46a9422145b4f772b2398b6135c"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "claims",
    "component": "enforcerd",
    "pr-id": "940",
    "commit-sha": "b719706d8310eec231c81773316e9d409811ca85"
  },
  {
    "project": "claims",
    "component": "backend",
    "pr-id": "223",
    "commit-sha": "ef2f79deb91305ebf003d68212a462e7a5d99efe"
  },
  {
    "project": "claims",
    "component": "trireme-lib",
    "pr-id": "694",
    "commit-sha": "44bcd592d0d1140237b726a61109fafb4a52692d"
  },
  {
    "project": "claims",
    "component": "gaia",
    "pr-id": "229",
    "commit-sha": "e441ef76cdb691f2d2877444fa49d212d58f521e"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "claims",
    "component": "trireme-lib",
    "pr-id": "694",
    "commit-sha": "44bcd592d0d1140237b726a61109fafb4a52692d"
  },
  {
    "project": "claims",
    "component": "gaia",
    "pr-id": "229",
    "commit-sha": "009ac43ec75e234435053ffe78e3c2fbfa32231b"
  },
  {
    "project": "claims",
    "component": "enforcerd",
    "pr-id": "940",
    "commit-sha": "b719706d8310eec231c81773316e9d409811ca85"
  },
  {
    "project": "claims",
    "component": "backend",
    "pr-id": "223",
    "commit-sha": "4de1ac00812608aeee7b385b778fab54d17e07ab"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "claims",
    "component": "trireme-lib",
    "pr-id": "694",
    "commit-sha": "44bcd592d0d1140237b726a61109fafb4a52692d"
  },
  {
    "project": "claims",
    "component": "gaia",
    "pr-id": "229",
    "commit-sha": "009ac43ec75e234435053ffe78e3c2fbfa32231b"
  },
  {
    "project": "claims",
    "component": "enforcerd",
    "pr-id": "940",
    "commit-sha": "b719706d8310eec231c81773316e9d409811ca85"
  },
  {
    "project": "claims",
    "component": "backend",
    "pr-id": "223",
    "commit-sha": "4de1ac00812608aeee7b385b778fab54d17e07ab"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "claims",
    "component": "trireme-lib",
    "pr-id": "694",
    "commit-sha": "44bcd592d0d1140237b726a61109fafb4a52692d"
  },
  {
    "project": "claims",
    "component": "gaia",
    "pr-id": "229",
    "commit-sha": "5c6c62dcbd192b133c118ac4fc90827f7b33436d"
  },
  {
    "project": "claims",
    "component": "enforcerd",
    "pr-id": "940",
    "commit-sha": "52f343ffe834c14fbba80984852911b74506a0a7"
  },
  {
    "project": "claims",
    "component": "backend",
    "pr-id": "223",
    "commit-sha": "820a563f08e9a93f6f27cdc12b0d083b6561abdb"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "claims",
    "component": "gaia",
    "pr-id": "229",
    "commit-sha": "5c6c62dcbd192b133c118ac4fc90827f7b33436d"
  },
  {
    "project": "claims",
    "component": "enforcerd",
    "pr-id": "940",
    "commit-sha": "52f343ffe834c14fbba80984852911b74506a0a7"
  },
  {
    "project": "claims",
    "component": "backend",
    "pr-id": "223",
    "commit-sha": "820a563f08e9a93f6f27cdc12b0d083b6561abdb"
  },
  {
    "project": "claims",
    "component": "trireme-lib",
    "pr-id": "694",
    "commit-sha": "44bcd592d0d1140237b726a61109fafb4a52692d"
  }
]
```

**Comment by satyamsi** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "claims",
    "component": "trireme-lib",
    "pr-id": "694",
    "commit-sha": "44bcd592d0d1140237b726a61109fafb4a52692d"
  },
  {
    "project": "claims",
    "component": "gaia",
    "pr-id": "229",
    "commit-sha": "5c6c62dcbd192b133c118ac4fc90827f7b33436d"
  },
  {
    "project": "claims",
    "component": "enforcerd",
    "pr-id": "940",
    "commit-sha": "52f343ffe834c14fbba80984852911b74506a0a7"
  },
  {
    "project": "claims",
    "component": "backend",
    "pr-id": "223",
    "commit-sha": "820a563f08e9a93f6f27cdc12b0d083b6561abdb"
  }
]
```

**Comment by satyamsi** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "claims",
    "component": "backend",
    "pr-id": "223",
    "commit-sha": "820a563f08e9a93f6f27cdc12b0d083b6561abdb"
  },
  {
    "project": "claims",
    "component": "trireme-lib",
    "pr-id": "694",
    "commit-sha": "44bcd592d0d1140237b726a61109fafb4a52692d"
  },
  {
    "project": "claims",
    "component": "gaia",
    "pr-id": "229",
    "commit-sha": "5c6c62dcbd192b133c118ac4fc90827f7b33436d"
  },
  {
    "project": "claims",
    "component": "enforcerd",
    "pr-id": "940",
    "commit-sha": "52f343ffe834c14fbba80984852911b74506a0a7"
  }
]
```

**Comment by satyamsi** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "claims",
    "component": "trireme-lib",
    "pr-id": "694",
    "commit-sha": "44bcd592d0d1140237b726a61109fafb4a52692d"
  },
  {
    "project": "claims",
    "component": "gaia",
    "pr-id": "229",
    "commit-sha": "5c6c62dcbd192b133c118ac4fc90827f7b33436d"
  },
  {
    "project": "claims",
    "component": "enforcerd",
    "pr-id": "940",
    "commit-sha": "52f343ffe834c14fbba80984852911b74506a0a7"
  },
  {
    "project": "claims",
    "component": "backend",
    "pr-id": "223",
    "commit-sha": "820a563f08e9a93f6f27cdc12b0d083b6561abdb"
  }
]
```

**Comment by satyamsi** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "claims",
    "component": "backend",
    "pr-id": "223",
    "commit-sha": "820a563f08e9a93f6f27cdc12b0d083b6561abdb"
  },
  {
    "project": "claims",
    "component": "trireme-lib",
    "pr-id": "694",
    "commit-sha": "44bcd592d0d1140237b726a61109fafb4a52692d"
  },
  {
    "project": "claims",
    "component": "gaia",
    "pr-id": "229",
    "commit-sha": "5c6c62dcbd192b133c118ac4fc90827f7b33436d"
  },
  {
    "project": "claims",
    "component": "enforcerd",
    "pr-id": "940",
    "commit-sha": "52f343ffe834c14fbba80984852911b74506a0a7"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "claims",
    "component": "apotests",
    "pr-id": "1866",
    "commit-sha": "e66e38239f7a92c25097ba8d1b35734240ea9283"
  },
  {
    "project": "claims",
    "component": "integrations-lib",
    "pr-id": "71",
    "commit-sha": "3248946fbf7eef131bbe6f34482198c6ef508f1e"
  },
  {
    "project": "claims",
    "component": "trireme-lib",
    "pr-id": "694",
    "commit-sha": "39fcd59f278d6dc1305a8553610012c636301ae1"
  },
  {
    "project": "claims",
    "component": "gaia",
    "pr-id": "229",
    "commit-sha": "799124abfc2475d659b401df93e9e80940b21338"
  },
  {
    "project": "claims",
    "component": "enforcerd",
    "pr-id": "940",
    "commit-sha": "bc57d85aad560d8510fa241cf3ca9a57e34e41a7"
  },
  {
    "project": "claims",
    "component": "backend",
    "pr-id": "223",
    "commit-sha": "92f669501e60b61f8e28cfa4c12ee4a18b53ff91"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "claims",
    "component": "enforcerd",
    "pr-id": "940",
    "commit-sha": "bc57d85aad560d8510fa241cf3ca9a57e34e41a7"
  },
  {
    "project": "claims",
    "component": "backend",
    "pr-id": "223",
    "commit-sha": "92f669501e60b61f8e28cfa4c12ee4a18b53ff91"
  },
  {
    "project": "claims",
    "component": "apotests",
    "pr-id": "1866",
    "commit-sha": "e66e38239f7a92c25097ba8d1b35734240ea9283"
  },
  {
    "project": "claims",
    "component": "integrations-lib",
    "pr-id": "71",
    "commit-sha": "3248946fbf7eef131bbe6f34482198c6ef508f1e"
  },
  {
    "project": "claims",
    "component": "trireme-lib",
    "pr-id": "694",
    "commit-sha": "39fcd59f278d6dc1305a8553610012c636301ae1"
  },
  {
    "project": "claims",
    "component": "gaia",
    "pr-id": "229",
    "commit-sha": "adf5699765355efa440369b556e4b7aa5e9142a8"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "claims",
    "component": "gaia",
    "pr-id": "229",
    "commit-sha": "adf5699765355efa440369b556e4b7aa5e9142a8"
  },
  {
    "project": "claims",
    "component": "enforcerd",
    "pr-id": "940",
    "commit-sha": "bc57d85aad560d8510fa241cf3ca9a57e34e41a7"
  },
  {
    "project": "claims",
    "component": "backend",
    "pr-id": "223",
    "commit-sha": "c9c6fc6e6578929856d4902c378867c5ddd787e1"
  },
  {
    "project": "claims",
    "component": "apotests",
    "pr-id": "1866",
    "commit-sha": "e66e38239f7a92c25097ba8d1b35734240ea9283"
  },
  {
    "project": "claims",
    "component": "integrations-lib",
    "pr-id": "71",
    "commit-sha": "3248946fbf7eef131bbe6f34482198c6ef508f1e"
  },
  {
    "project": "claims",
    "component": "trireme-lib",
    "pr-id": "694",
    "commit-sha": "39fcd59f278d6dc1305a8553610012c636301ae1"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "claims",
    "component": "gaia",
    "pr-id": "229",
    "commit-sha": "adf5699765355efa440369b556e4b7aa5e9142a8"
  },
  {
    "project": "claims",
    "component": "enforcerd",
    "pr-id": "940",
    "commit-sha": "bc57d85aad560d8510fa241cf3ca9a57e34e41a7"
  },
  {
    "project": "claims",
    "component": "backend",
    "pr-id": "223",
    "commit-sha": "c9c6fc6e6578929856d4902c378867c5ddd787e1"
  },
  {
    "project": "claims",
    "component": "apotests",
    "pr-id": "1866",
    "commit-sha": "e66e38239f7a92c25097ba8d1b35734240ea9283"
  },
  {
    "project": "claims",
    "component": "clad",
    "pr-id": "859",
    "commit-sha": "eabac3ee79858ad9846d4e69641c9b098d60d566"
  },
  {
    "project": "claims",
    "component": "integrations-lib",
    "pr-id": "71",
    "commit-sha": "3248946fbf7eef131bbe6f34482198c6ef508f1e"
  },
  {
    "project": "claims",
    "component": "trireme-lib",
    "pr-id": "694",
    "commit-sha": "39fcd59f278d6dc1305a8553610012c636301ae1"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "claims",
    "component": "clad",
    "pr-id": "859",
    "commit-sha": "8a6b8de1fdf6d09e1d151767a3c9f39c7816ebd9"
  },
  {
    "project": "claims",
    "component": "integrations-lib",
    "pr-id": "71",
    "commit-sha": "3248946fbf7eef131bbe6f34482198c6ef508f1e"
  },
  {
    "project": "claims",
    "component": "trireme-lib",
    "pr-id": "694",
    "commit-sha": "39fcd59f278d6dc1305a8553610012c636301ae1"
  },
  {
    "project": "claims",
    "component": "gaia",
    "pr-id": "229",
    "commit-sha": "adf5699765355efa440369b556e4b7aa5e9142a8"
  },
  {
    "project": "claims",
    "component": "enforcerd",
    "pr-id": "940",
    "commit-sha": "bc57d85aad560d8510fa241cf3ca9a57e34e41a7"
  },
  {
    "project": "claims",
    "component": "backend",
    "pr-id": "223",
    "commit-sha": "c9c6fc6e6578929856d4902c378867c5ddd787e1"
  },
  {
    "project": "claims",
    "component": "apotests",
    "pr-id": "1866",
    "commit-sha": "e66e38239f7a92c25097ba8d1b35734240ea9283"
  }
]
```

**Pull request merged**
