### PR TITLE
Fixing a bug on packet print when packet creation failed

### PR DESCRIPTION
**Pull request by 0xmchadha**
#### Description
*Changes proposed in this pull request.*

#### Test plan
*Outline the test plan used to test this change before merging it.*

> Fixes #.

### CODE REVIEW

**Review by amitlimaye — DISMISSED** [review]

**Review by varks — DISMISSED** [review]

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1445",
    "commit-sha": "e79b2b1e6f898b77ff7c8940c2f05f3869278450"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "554",
    "commit-sha": "855af0f30ce441d6cfdd80a272d8fa4eb848d0ee"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1445",
    "commit-sha": "21889b250600891b0df925fde15d367df368ea96"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "554",
    "commit-sha": "855af0f30ce441d6cfdd80a272d8fa4eb848d0ee"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1445",
    "commit-sha": "21889b250600891b0df925fde15d367df368ea96"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "554",
    "commit-sha": "855af0f30ce441d6cfdd80a272d8fa4eb848d0ee"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1445",
    "commit-sha": "21889b250600891b0df925fde15d367df368ea96"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "554",
    "commit-sha": "855af0f30ce441d6cfdd80a272d8fa4eb848d0ee"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1445",
    "commit-sha": "21889b250600891b0df925fde15d367df368ea96"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "554",
    "commit-sha": "855af0f30ce441d6cfdd80a272d8fa4eb848d0ee"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1445",
    "commit-sha": "21889b250600891b0df925fde15d367df368ea96"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "554",
    "commit-sha": "855af0f30ce441d6cfdd80a272d8fa4eb848d0ee"
  }
]
```

**Pull request closed without merging**
