### PR TITLE
Fix Kubernetes Monitor Resync

### PR DESCRIPTION
**Pull request by mheese**

### CODE REVIEW

**Comment by sooryamanian91** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "fix-k8s-monitor-resync",
    "component": "trireme-lib",
    "pr-id": "828",
    "commit-sha": "c28a477ee1009240f146a26b71b00f882efaeaa2"
  },
  {
    "project": "fix-k8s-monitor-resync",
    "component": "enforcerd",
    "pr-id": "1277",
    "commit-sha": "7a9d767f3600e7d52b96cf5dd568d76c7022640f"
  }
]
```

**Comment by sooryamanian91** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "fix-k8s-monitor-resync",
    "component": "enforcerd",
    "pr-id": "1277",
    "commit-sha": "492b4a3ef0d00c2b4e4863ffb08ae59741d3909f"
  },
  {
    "project": "fix-k8s-monitor-resync",
    "component": "trireme-lib",
    "pr-id": "828",
    "commit-sha": "c28a477ee1009240f146a26b71b00f882efaeaa2"
  },
  {
    "project": "fix-k8s-monitor-resync",
    "component": "integrations-lib",
    "pr-id": "116",
    "commit-sha": "4d08237c7eb87841f0d07c37a1d849c42721c880"
  }
]
```

**Comment by sooryamanian91** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "fix-k8s-monitor-resync",
    "component": "enforcerd",
    "pr-id": "1277",
    "commit-sha": "4cd7985b70e66dc8b1dc5756f6277a183d1709df"
  },
  {
    "project": "fix-k8s-monitor-resync",
    "component": "trireme-lib",
    "pr-id": "828",
    "commit-sha": "c28a477ee1009240f146a26b71b00f882efaeaa2"
  },
  {
    "project": "fix-k8s-monitor-resync",
    "component": "integrations-lib",
    "pr-id": "116",
    "commit-sha": "4d08237c7eb87841f0d07c37a1d849c42721c880"
  }
]
```

**Comment by sooryamanian91** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "fix-k8s-monitor-resync",
    "component": "enforcerd",
    "pr-id": "1277",
    "commit-sha": "4cd7985b70e66dc8b1dc5756f6277a183d1709df"
  },
  {
    "project": "fix-k8s-monitor-resync",
    "component": "trireme-lib",
    "pr-id": "828",
    "commit-sha": "c28a477ee1009240f146a26b71b00f882efaeaa2"
  },
  {
    "project": "fix-k8s-monitor-resync",
    "component": "integrations-lib",
    "pr-id": "116",
    "commit-sha": "4d08237c7eb87841f0d07c37a1d849c42721c880"
  }
]
```

**Review by amitlimaye — APPROVED** [review]

**Pull request merged**
