### PR TITLE
Read the raw bytes from miekg dns package to return back to the pu client

### PR DESCRIPTION
**Pull request by 0xmchadha**

### CODE REVIEW

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1647",
    "commit-sha": "0759e309d84f7e821946bf35f934e985afa0816e",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "1020",
    "commit-sha": "9652afd54bac4797599aef0cadc8db0767079db2",
    "pipeline": "master"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1647",
    "commit-sha": "0759e309d84f7e821946bf35f934e985afa0816e",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "1020",
    "commit-sha": "9652afd54bac4797599aef0cadc8db0767079db2",
    "pipeline": "master"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1647",
    "commit-sha": "0759e309d84f7e821946bf35f934e985afa0816e",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "1020",
    "commit-sha": "9652afd54bac4797599aef0cadc8db0767079db2",
    "pipeline": "master"
  }
]
```

**Review by mheese — DISMISSED** [review]
Looks good! 👍 ... Good catch and good work!

Thanks again for also walking me through the rest of the code today. I'll create a follow-up ticket for a test for the problem child DNS client.

Also as we decided in our team meeting, please get another review from another person. I count as the non-expert on this one.

**Review by amitlimaye — DISMISSED** [review]

**Pull request closed without merging**
