### PR TITLE
Update: Bring golint check back to 100% for goreport

### PR DESCRIPTION
**Pull request by ericrpowers**
#### Description
This brings the `golint` check in https://goreportcard.com/report/go.aporeto.io/trireme-lib#golint back to 100% (unless it is hiding more after this merge)

### CODE REVIEW

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1216",
    "commit-sha": "1c3c48fa7dc4791ec576ac02ae99c1295ee64723"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "811",
    "commit-sha": "64077711e071532dffcee5e40c5379861664be4e"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1216",
    "commit-sha": "1c3c48fa7dc4791ec576ac02ae99c1295ee64723"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "811",
    "commit-sha": "64077711e071532dffcee5e40c5379861664be4e"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1216",
    "commit-sha": "f792bfe356c0979414907d2d9eafa9cc9ececdaa"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "811",
    "commit-sha": "64077711e071532dffcee5e40c5379861664be4e"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1216",
    "commit-sha": "f792bfe356c0979414907d2d9eafa9cc9ececdaa"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "811",
    "commit-sha": "64077711e071532dffcee5e40c5379861664be4e"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "811",
    "commit-sha": "64077711e071532dffcee5e40c5379861664be4e"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1216",
    "commit-sha": "e0461e00c4dc40c4be25fd11403e5cf2b86699c3"
  }
]
```

**Review by sibicramesh — APPROVED** [review]

**Pull request merged**
