### PR TITLE
Adding a different mark for external service flow

### PR DESCRIPTION
**Pull request by amitlimaye**
#### Description
*Changes proposed in this pull request.*

#### Test plan
*Outline the test plan used to test this change before merging it.*

> Fixes #.

### CODE REVIEW

**Comment by amitlimaye** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1447",
    "commit-sha": "31970f04b96db4efc79625fa4376684fd4a114cd"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "899",
    "commit-sha": "4bf70374f33af195f7f90b249c5f116356e0246d"
  }
]
```

**Comment by amitlimaye** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1447",
    "commit-sha": "31970f04b96db4efc79625fa4376684fd4a114cd"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "899",
    "commit-sha": "b70b3cbb55a7ccf77c91c2720c173cfd8fe1283b"
  }
]
```

**Review by sibicramesh — DISMISSED** [review]

**Comment by dstiliadis** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1353",
    "commit-sha": "2177e571cb234291c0fb6cc46e7b424d050c976e"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "899",
    "commit-sha": "b70b3cbb55a7ccf77c91c2720c173cfd8fe1283b"
  }
]
```

**Comment by dstiliadis** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1453",
    "commit-sha": "8574b6278574e07f653d47b1514fe2e8e4777e60"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "899",
    "commit-sha": "b70b3cbb55a7ccf77c91c2720c173cfd8fe1283b"
  }
]
```

**Comment by dstiliadis** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1453",
    "commit-sha": "8574b6278574e07f653d47b1514fe2e8e4777e60"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "899",
    "commit-sha": "1295ce4555a143397f7c35500e1110416ab80627"
  }
]
```

**Comment by dstiliadis** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1453",
    "commit-sha": "8574b6278574e07f653d47b1514fe2e8e4777e60"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "899",
    "commit-sha": "206db2694d55554f8a506d05b89285a8e58d4b0d"
  }
]
```

**Comment by dstiliadis** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1453",
    "commit-sha": "8574b6278574e07f653d47b1514fe2e8e4777e60"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "899",
    "commit-sha": "2827899db92cb171c77167d6c2b576d371e5d7ec"
  }
]
```

**Comment by dstiliadis** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1453",
    "commit-sha": "fe9ced0f77367e2f80ca9788698221694b6ea3ef"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "899",
    "commit-sha": "2827899db92cb171c77167d6c2b576d371e5d7ec"
  }
]
```

**Pull request merged**
