### PR TITLE
Enable auto port discovery for PU's started with apoctl.

### PR DESCRIPTION
**Pull request by 0xmchadha**
…code to merge UID along with normal process

#### Description
*Changes proposed in this pull request.*

#### Test plan
*Outline the test plan used to test this change before merging it.*

> Fixes #.

### CODE REVIEW

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "865",
    "commit-sha": "2306503a933c1c10733a20e85d0f78060df2627f"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "631",
    "commit-sha": "5b02aab1e7f30d96522192e470fdae7a08af437d"
  },
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "53",
    "commit-sha": "677ec1b482a760ef7742c62db61ab2bcf98c058a"
  },
  {
    "project": "",
    "component": "integrations-lib",
    "pr-id": "51",
    "commit-sha": "593c670dedbd8cb9983cfd2cdf6e8172ed090e8e"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "integrations-lib",
    "pr-id": "51",
    "commit-sha": "593c670dedbd8cb9983cfd2cdf6e8172ed090e8e"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "865",
    "commit-sha": "2306503a933c1c10733a20e85d0f78060df2627f"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "631",
    "commit-sha": "5b02aab1e7f30d96522192e470fdae7a08af437d"
  },
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "53",
    "commit-sha": "677ec1b482a760ef7742c62db61ab2bcf98c058a"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "865",
    "commit-sha": "2306503a933c1c10733a20e85d0f78060df2627f"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "631",
    "commit-sha": "5b02aab1e7f30d96522192e470fdae7a08af437d"
  },
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "53",
    "commit-sha": "677ec1b482a760ef7742c62db61ab2bcf98c058a"
  },
  {
    "project": "",
    "component": "integrations-lib",
    "pr-id": "51",
    "commit-sha": "593c670dedbd8cb9983cfd2cdf6e8172ed090e8e"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "865",
    "commit-sha": "2306503a933c1c10733a20e85d0f78060df2627f"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "631",
    "commit-sha": "5b02aab1e7f30d96522192e470fdae7a08af437d"
  },
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "53",
    "commit-sha": "677ec1b482a760ef7742c62db61ab2bcf98c058a"
  },
  {
    "project": "",
    "component": "integrations-lib",
    "pr-id": "51",
    "commit-sha": "593c670dedbd8cb9983cfd2cdf6e8172ed090e8e"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "53",
    "commit-sha": "677ec1b482a760ef7742c62db61ab2bcf98c058a"
  },
  {
    "project": "",
    "component": "integrations-lib",
    "pr-id": "51",
    "commit-sha": "593c670dedbd8cb9983cfd2cdf6e8172ed090e8e"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "865",
    "commit-sha": "19dcf4a85a5d021d4dc80111a7cf5c279778cea9"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "631",
    "commit-sha": "5b02aab1e7f30d96522192e470fdae7a08af437d"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "865",
    "commit-sha": "19dcf4a85a5d021d4dc80111a7cf5c279778cea9"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "631",
    "commit-sha": "5b02aab1e7f30d96522192e470fdae7a08af437d"
  },
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "53",
    "commit-sha": "677ec1b482a760ef7742c62db61ab2bcf98c058a"
  },
  {
    "project": "",
    "component": "integrations-lib",
    "pr-id": "51",
    "commit-sha": "999f24586655203928e9b5c87998668beb810f0a"
  }
]
```

**Review by amitlimaye — APPROVED** [review]

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "865",
    "commit-sha": "390feeeef2e95b0bbed18ad43129e520aa44657c"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "631",
    "commit-sha": "f6f8a5fb224b03bb2c23a1f03d3c329fcfc624ab"
  },
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "53",
    "commit-sha": "967691476da375e00ed2c63f9d597fb962b89dc2"
  },
  {
    "project": "",
    "component": "integrations-lib",
    "pr-id": "51",
    "commit-sha": "18254afa5ffe3c630620b89ed0b74b6d47c99d56"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "865",
    "commit-sha": "390feeeef2e95b0bbed18ad43129e520aa44657c"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "631",
    "commit-sha": "f6f8a5fb224b03bb2c23a1f03d3c329fcfc624ab"
  },
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "53",
    "commit-sha": "967691476da375e00ed2c63f9d597fb962b89dc2"
  },
  {
    "project": "",
    "component": "integrations-lib",
    "pr-id": "51",
    "commit-sha": "18254afa5ffe3c630620b89ed0b74b6d47c99d56"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "865",
    "commit-sha": "390feeeef2e95b0bbed18ad43129e520aa44657c"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "631",
    "commit-sha": "f6f8a5fb224b03bb2c23a1f03d3c329fcfc624ab"
  },
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "53",
    "commit-sha": "967691476da375e00ed2c63f9d597fb962b89dc2"
  },
  {
    "project": "",
    "component": "integrations-lib",
    "pr-id": "51",
    "commit-sha": "18254afa5ffe3c630620b89ed0b74b6d47c99d56"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "631",
    "commit-sha": "f6f8a5fb224b03bb2c23a1f03d3c329fcfc624ab"
  },
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "53",
    "commit-sha": "967691476da375e00ed2c63f9d597fb962b89dc2"
  },
  {
    "project": "",
    "component": "integrations-lib",
    "pr-id": "51",
    "commit-sha": "18254afa5ffe3c630620b89ed0b74b6d47c99d56"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "865",
    "commit-sha": "390feeeef2e95b0bbed18ad43129e520aa44657c"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "865",
    "commit-sha": "1e1596c74f2def549f28dcfd464af07195539ad3"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "631",
    "commit-sha": "bb7868a6f75b9fce56adf75b50f8227f504c5b70"
  },
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "53",
    "commit-sha": "e7362f422edc18d3e3570980e66d9805c5bad530"
  },
  {
    "project": "",
    "component": "integrations-lib",
    "pr-id": "51",
    "commit-sha": "18254afa5ffe3c630620b89ed0b74b6d47c99d56"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "integrations-lib",
    "pr-id": "51",
    "commit-sha": "18254afa5ffe3c630620b89ed0b74b6d47c99d56"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "865",
    "commit-sha": "1e1596c74f2def549f28dcfd464af07195539ad3"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "631",
    "commit-sha": "e1365a56ed23f2d49e7e0cfca6c11fceced108b3"
  },
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "53",
    "commit-sha": "e7362f422edc18d3e3570980e66d9805c5bad530"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "631",
    "commit-sha": "4aa612964bb90a645d8e76234e8b6b6e1f3eff7c"
  },
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "53",
    "commit-sha": "e7362f422edc18d3e3570980e66d9805c5bad530"
  },
  {
    "project": "",
    "component": "integrations-lib",
    "pr-id": "51",
    "commit-sha": "90298cef4bd997a3323b1a9edece3103c769b0a7"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "865",
    "commit-sha": "1e1596c74f2def549f28dcfd464af07195539ad3"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "865",
    "commit-sha": "1e1596c74f2def549f28dcfd464af07195539ad3"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "631",
    "commit-sha": "4219b45c1d3427e3fb5d6f8452f5ca59bebc4d0a"
  },
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "53",
    "commit-sha": "e7362f422edc18d3e3570980e66d9805c5bad530"
  },
  {
    "project": "",
    "component": "integrations-lib",
    "pr-id": "51",
    "commit-sha": "90298cef4bd997a3323b1a9edece3103c769b0a7"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "631",
    "commit-sha": "4219b45c1d3427e3fb5d6f8452f5ca59bebc4d0a"
  },
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "53",
    "commit-sha": "e7362f422edc18d3e3570980e66d9805c5bad530"
  },
  {
    "project": "",
    "component": "integrations-lib",
    "pr-id": "51",
    "commit-sha": "90298cef4bd997a3323b1a9edece3103c769b0a7"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "865",
    "commit-sha": "92a41f11a626249d36145a3638e765cf088be058"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "865",
    "commit-sha": "92a41f11a626249d36145a3638e765cf088be058"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "631",
    "commit-sha": "91823334934f9c7d76b88b7c02e4ef84beb08024"
  },
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "53",
    "commit-sha": "e7362f422edc18d3e3570980e66d9805c5bad530"
  },
  {
    "project": "",
    "component": "integrations-lib",
    "pr-id": "51",
    "commit-sha": "90298cef4bd997a3323b1a9edece3103c769b0a7"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "865",
    "commit-sha": "92a41f11a626249d36145a3638e765cf088be058"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "631",
    "commit-sha": "bf96b0d2802d2fff5ef0174a74c3a05e7b8d372f"
  },
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "53",
    "commit-sha": "e7362f422edc18d3e3570980e66d9805c5bad530"
  },
  {
    "project": "",
    "component": "integrations-lib",
    "pr-id": "51",
    "commit-sha": "90298cef4bd997a3323b1a9edece3103c769b0a7"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "865",
    "commit-sha": "92a41f11a626249d36145a3638e765cf088be058"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "631",
    "commit-sha": "fb269cf29cbdb3e157f2ccaffbac7c122e49205c"
  },
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "53",
    "commit-sha": "e7362f422edc18d3e3570980e66d9805c5bad530"
  },
  {
    "project": "",
    "component": "integrations-lib",
    "pr-id": "51",
    "commit-sha": "90298cef4bd997a3323b1a9edece3103c769b0a7"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "865",
    "commit-sha": "92a41f11a626249d36145a3638e765cf088be058"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "631",
    "commit-sha": "3d569ba6f632e6eb6b7f714c45bbf362feb1d1ed"
  },
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "53",
    "commit-sha": "e7362f422edc18d3e3570980e66d9805c5bad530"
  },
  {
    "project": "",
    "component": "integrations-lib",
    "pr-id": "51",
    "commit-sha": "90298cef4bd997a3323b1a9edece3103c769b0a7"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "865",
    "commit-sha": "92a41f11a626249d36145a3638e765cf088be058"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "631",
    "commit-sha": "68d79029862af34ca54916ae0ee7ffb51b9a88f2"
  },
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "53",
    "commit-sha": "e7362f422edc18d3e3570980e66d9805c5bad530"
  },
  {
    "project": "",
    "component": "integrations-lib",
    "pr-id": "51",
    "commit-sha": "90298cef4bd997a3323b1a9edece3103c769b0a7"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "865",
    "commit-sha": "92a41f11a626249d36145a3638e765cf088be058"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "631",
    "commit-sha": "c550c48d29bc190a005034270f703cdc24eeb27d"
  },
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "53",
    "commit-sha": "e7362f422edc18d3e3570980e66d9805c5bad530"
  },
  {
    "project": "",
    "component": "integrations-lib",
    "pr-id": "51",
    "commit-sha": "90298cef4bd997a3323b1a9edece3103c769b0a7"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "865",
    "commit-sha": "92a41f11a626249d36145a3638e765cf088be058"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "631",
    "commit-sha": "c550c48d29bc190a005034270f703cdc24eeb27d"
  },
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "53",
    "commit-sha": "e7362f422edc18d3e3570980e66d9805c5bad530"
  },
  {
    "project": "",
    "component": "integrations-lib",
    "pr-id": "51",
    "commit-sha": "90298cef4bd997a3323b1a9edece3103c769b0a7"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "865",
    "commit-sha": "4b4071967814913b53548568443944fb9f85d97b"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "631",
    "commit-sha": "c550c48d29bc190a005034270f703cdc24eeb27d"
  },
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "53",
    "commit-sha": "e7362f422edc18d3e3570980e66d9805c5bad530"
  },
  {
    "project": "",
    "component": "integrations-lib",
    "pr-id": "51",
    "commit-sha": "90298cef4bd997a3323b1a9edece3103c769b0a7"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "53",
    "commit-sha": "e7362f422edc18d3e3570980e66d9805c5bad530"
  },
  {
    "project": "",
    "component": "integrations-lib",
    "pr-id": "51",
    "commit-sha": "90298cef4bd997a3323b1a9edece3103c769b0a7"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "865",
    "commit-sha": "4b4071967814913b53548568443944fb9f85d97b"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "631",
    "commit-sha": "8eaa8f19cddbf8160f8c6cbcaa4cd686841cc262"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "865",
    "commit-sha": "4b4071967814913b53548568443944fb9f85d97b"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "631",
    "commit-sha": "05901c7767f0eca2b6d8427997c78b73f28f9d2e"
  },
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "53",
    "commit-sha": "e7362f422edc18d3e3570980e66d9805c5bad530"
  },
  {
    "project": "",
    "component": "integrations-lib",
    "pr-id": "51",
    "commit-sha": "90298cef4bd997a3323b1a9edece3103c769b0a7"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "631",
    "commit-sha": "10b6fa1430b73ce0018e78c75f0f75b9fa39e198"
  },
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "53",
    "commit-sha": "e7362f422edc18d3e3570980e66d9805c5bad530"
  },
  {
    "project": "",
    "component": "integrations-lib",
    "pr-id": "51",
    "commit-sha": "90298cef4bd997a3323b1a9edece3103c769b0a7"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "865",
    "commit-sha": "4b4071967814913b53548568443944fb9f85d97b"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "865",
    "commit-sha": "4b4071967814913b53548568443944fb9f85d97b"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "631",
    "commit-sha": "af5e779b3f3af8f947addd7671f9cbf0103d316b"
  },
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "53",
    "commit-sha": "e7362f422edc18d3e3570980e66d9805c5bad530"
  },
  {
    "project": "",
    "component": "integrations-lib",
    "pr-id": "51",
    "commit-sha": "90298cef4bd997a3323b1a9edece3103c769b0a7"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "53",
    "commit-sha": "e7362f422edc18d3e3570980e66d9805c5bad530"
  },
  {
    "project": "",
    "component": "integrations-lib",
    "pr-id": "51",
    "commit-sha": "90298cef4bd997a3323b1a9edece3103c769b0a7"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "865",
    "commit-sha": "4b4071967814913b53548568443944fb9f85d97b"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "631",
    "commit-sha": "62f523c911f6bb767148289e848dfb3e8ef5b1b4"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "865",
    "commit-sha": "4b4071967814913b53548568443944fb9f85d97b"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "631",
    "commit-sha": "b2224f37759c183a81288e5f8ac110804972d8b0"
  },
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "53",
    "commit-sha": "e7362f422edc18d3e3570980e66d9805c5bad530"
  },
  {
    "project": "",
    "component": "integrations-lib",
    "pr-id": "51",
    "commit-sha": "90298cef4bd997a3323b1a9edece3103c769b0a7"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "865",
    "commit-sha": "91029fae8a8f9e43f8288128598d641887b2fb89"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "631",
    "commit-sha": "b2224f37759c183a81288e5f8ac110804972d8b0"
  },
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "53",
    "commit-sha": "e7362f422edc18d3e3570980e66d9805c5bad530"
  },
  {
    "project": "",
    "component": "integrations-lib",
    "pr-id": "51",
    "commit-sha": "90298cef4bd997a3323b1a9edece3103c769b0a7"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "631",
    "commit-sha": "73d3b0620368feb4403064f5203a1013dbdc6ae6"
  },
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "53",
    "commit-sha": "e7362f422edc18d3e3570980e66d9805c5bad530"
  },
  {
    "project": "",
    "component": "integrations-lib",
    "pr-id": "51",
    "commit-sha": "90298cef4bd997a3323b1a9edece3103c769b0a7"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "865",
    "commit-sha": "91029fae8a8f9e43f8288128598d641887b2fb89"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "integrations-lib",
    "pr-id": "51",
    "commit-sha": "90298cef4bd997a3323b1a9edece3103c769b0a7"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "865",
    "commit-sha": "91029fae8a8f9e43f8288128598d641887b2fb89"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "631",
    "commit-sha": "91d30b7e092cf35f4ac615a0b36825908b204074"
  },
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "53",
    "commit-sha": "e7362f422edc18d3e3570980e66d9805c5bad530"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "865",
    "commit-sha": "91029fae8a8f9e43f8288128598d641887b2fb89"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "631",
    "commit-sha": "ab997ffbae93ffd1d1623a073f2120187e9280c2"
  },
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "53",
    "commit-sha": "e7362f422edc18d3e3570980e66d9805c5bad530"
  },
  {
    "project": "",
    "component": "integrations-lib",
    "pr-id": "51",
    "commit-sha": "90298cef4bd997a3323b1a9edece3103c769b0a7"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "631",
    "commit-sha": "ab997ffbae93ffd1d1623a073f2120187e9280c2"
  },
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "53",
    "commit-sha": "e7362f422edc18d3e3570980e66d9805c5bad530"
  },
  {
    "project": "",
    "component": "integrations-lib",
    "pr-id": "51",
    "commit-sha": "90298cef4bd997a3323b1a9edece3103c769b0a7"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "865",
    "commit-sha": "4f63218514982c85c08fc9b1eddd5ae7997d29fb"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "865",
    "commit-sha": "4f63218514982c85c08fc9b1eddd5ae7997d29fb"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "631",
    "commit-sha": "ab997ffbae93ffd1d1623a073f2120187e9280c2"
  },
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "53",
    "commit-sha": "e7362f422edc18d3e3570980e66d9805c5bad530"
  },
  {
    "project": "",
    "component": "integrations-lib",
    "pr-id": "51",
    "commit-sha": "90298cef4bd997a3323b1a9edece3103c769b0a7"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "631",
    "commit-sha": "ab997ffbae93ffd1d1623a073f2120187e9280c2"
  },
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "53",
    "commit-sha": "e7362f422edc18d3e3570980e66d9805c5bad530"
  },
  {
    "project": "",
    "component": "integrations-lib",
    "pr-id": "51",
    "commit-sha": "90298cef4bd997a3323b1a9edece3103c769b0a7"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "865",
    "commit-sha": "4f63218514982c85c08fc9b1eddd5ae7997d29fb"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "53",
    "commit-sha": "e7362f422edc18d3e3570980e66d9805c5bad530"
  },
  {
    "project": "",
    "component": "integrations-lib",
    "pr-id": "51",
    "commit-sha": "90298cef4bd997a3323b1a9edece3103c769b0a7"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "865",
    "commit-sha": "4f63218514982c85c08fc9b1eddd5ae7997d29fb"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "631",
    "commit-sha": "0e0a4e0261aa881e1bba451fd9645959377b849b"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "865",
    "commit-sha": "4f63218514982c85c08fc9b1eddd5ae7997d29fb"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "631",
    "commit-sha": "0e0a4e0261aa881e1bba451fd9645959377b849b"
  },
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "53",
    "commit-sha": "e7362f422edc18d3e3570980e66d9805c5bad530"
  },
  {
    "project": "",
    "component": "integrations-lib",
    "pr-id": "51",
    "commit-sha": "90298cef4bd997a3323b1a9edece3103c769b0a7"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "53",
    "commit-sha": "e7362f422edc18d3e3570980e66d9805c5bad530"
  },
  {
    "project": "",
    "component": "integrations-lib",
    "pr-id": "51",
    "commit-sha": "90298cef4bd997a3323b1a9edece3103c769b0a7"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "865",
    "commit-sha": "4f63218514982c85c08fc9b1eddd5ae7997d29fb"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "631",
    "commit-sha": "4b361c1afb39bd1e98c1fac4435abb8c92a5dbfc"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "integrations-lib",
    "pr-id": "51",
    "commit-sha": "90298cef4bd997a3323b1a9edece3103c769b0a7"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "865",
    "commit-sha": "4f63218514982c85c08fc9b1eddd5ae7997d29fb"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "631",
    "commit-sha": "8d677c893281ce9aa005f911a536304edb27987d"
  },
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "53",
    "commit-sha": "e7362f422edc18d3e3570980e66d9805c5bad530"
  }
]
```

**Pull request merged**
