### PR TITLE
fixed: do not mask errors

### PR DESCRIPTION
**Pull request by primalmotion**
will certainly not pass the tests.

### CODE REVIEW

**Comment by bvandewalle** [comment]
Good refactoring, well needed.

A lot of those errors were modified to (or were already) start with a capital letter. 
AFAIK, best practice is to start errors with a lower case

**Comment by primalmotion** [comment]
yeah, well I'll let that privilege to somebody else :)

**Comment by primalmotion** [comment]
Rah I did it :)

**Comment by bvandewalle** [comment]
I knew you wouldn't resist :)

**Pull request merged**
