### PR TITLE
reintroduce state=NEW

### PR DESCRIPTION
**Pull request by amitlimaye**
#### Description
*Changes proposed in this pull request.*

#### Test plan
*Outline the test plan used to test this change before merging it.*

> Fixes #.

### CODE REVIEW

**Comment by amitlimaye** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "flowlog_master",
    "component": "trireme-lib",
    "pr-id": "808",
    "commit-sha": "10988c18aeb3b6f76fa9b6d45661354a48d3f1b8"
  }
]
```

**Comment by amitlimaye** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "flowlog_master",
    "component": "enforcerd",
    "pr-id": "1212",
    "commit-sha": "d152778e4998f2338176ec1c2696e1d08b266356"
  },
  {
    "project": "flowlog_master",
    "component": "trireme-lib",
    "pr-id": "808",
    "commit-sha": "10988c18aeb3b6f76fa9b6d45661354a48d3f1b8"
  }
]
```

**Comment by amitlimaye** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "flowlog_master",
    "component": "enforcerd",
    "pr-id": "1212",
    "commit-sha": "d152778e4998f2338176ec1c2696e1d08b266356"
  },
  {
    "project": "flowlog_master",
    "component": "trireme-lib",
    "pr-id": "808",
    "commit-sha": "64edf2d3d148ab298840e5d0dbe5a542a88c01e0"
  }
]
```

**Comment by amitlimaye** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "flowlog_master",
    "component": "trireme-lib",
    "pr-id": "808",
    "commit-sha": "244e703327bb33328fa5fb2c03ece91caac72a01"
  },
  {
    "project": "flowlog_master",
    "component": "enforcerd",
    "pr-id": "1212",
    "commit-sha": "d152778e4998f2338176ec1c2696e1d08b266356"
  }
]
```

**Comment by amitlimaye** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "flowlog_master",
    "component": "trireme-lib",
    "pr-id": "808",
    "commit-sha": "244e703327bb33328fa5fb2c03ece91caac72a01"
  },
  {
    "project": "flowlog_master",
    "component": "enforcerd",
    "pr-id": "1212",
    "commit-sha": "d152778e4998f2338176ec1c2696e1d08b266356"
  }
]
```

**Comment by amitlimaye** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "flowlog_master",
    "component": "trireme-lib",
    "pr-id": "808",
    "commit-sha": "244e703327bb33328fa5fb2c03ece91caac72a01"
  },
  {
    "project": "flowlog_master",
    "component": "enforcerd",
    "pr-id": "1212",
    "commit-sha": "4be152641acc09f3471f328652aa0b4ed7bc0f3f"
  }
]
```

**Comment by amitlimaye** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "flowlog_master",
    "component": "trireme-lib",
    "pr-id": "808",
    "commit-sha": "459d449ff67fdc6f746da40aedd61f1c69ec7d8b"
  },
  {
    "project": "flowlog_master",
    "component": "enforcerd",
    "pr-id": "1212",
    "commit-sha": "4be152641acc09f3471f328652aa0b4ed7bc0f3f"
  }
]
```

**Review by sibicramesh — APPROVED** [review]

**Pull request merged**
