### PR TITLE
Use protocol numbers for iptable rules

### PR DESCRIPTION
**Pull request by varks**
On some os variants like alpine, protocol names like vrrp/l2tp are not defined in /etc/protocols. iptables would fail with "unknown protocol" error in such cases.

### CODE REVIEW

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "fix_protocols",
    "component": "enforcerd",
    "pr-id": "1046",
    "commit-sha": "e83d47168d98f91b8ffe029918d85b7cb4fbe4a9"
  },
  {
    "project": "fix_protocols",
    "component": "trireme-lib",
    "pr-id": "747",
    "commit-sha": "1be769e7398d24dbd4511f85dffa70a0d65e133f"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "fix_protocols",
    "component": "enforcerd",
    "pr-id": "1046",
    "commit-sha": "e83d47168d98f91b8ffe029918d85b7cb4fbe4a9"
  },
  {
    "project": "fix_protocols",
    "component": "trireme-lib",
    "pr-id": "747",
    "commit-sha": "f22a1a10213bfc222e2db523b81c5fedca172cfa"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "fix_protocols",
    "component": "enforcerd",
    "pr-id": "1046",
    "commit-sha": "e83d47168d98f91b8ffe029918d85b7cb4fbe4a9"
  },
  {
    "project": "fix_protocols",
    "component": "trireme-lib",
    "pr-id": "747",
    "commit-sha": "5c5923aeb6efda1275b3b23a875ec6b4b18a49af"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "fix_protocols",
    "component": "enforcerd",
    "pr-id": "1046",
    "commit-sha": "4aceff894550a2fae56260ed4c5c3735e3309f57"
  },
  {
    "project": "fix_protocols",
    "component": "trireme-lib",
    "pr-id": "747",
    "commit-sha": "5c5923aeb6efda1275b3b23a875ec6b4b18a49af"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "fix_protocols",
    "component": "enforcerd",
    "pr-id": "1046",
    "commit-sha": "4aceff894550a2fae56260ed4c5c3735e3309f57"
  },
  {
    "project": "fix_protocols",
    "component": "trireme-lib",
    "pr-id": "747",
    "commit-sha": "cc00582025f4fb883945c8f377b11a898e50b112"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "fix_protocols",
    "component": "enforcerd",
    "pr-id": "1046",
    "commit-sha": "4aceff894550a2fae56260ed4c5c3735e3309f57"
  },
  {
    "project": "fix_protocols",
    "component": "trireme-lib",
    "pr-id": "747",
    "commit-sha": "f317e333f6416e2bc5fe3a97b1b75161484f8922"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "fix_protocols",
    "component": "enforcerd",
    "pr-id": "1046",
    "commit-sha": "4aceff894550a2fae56260ed4c5c3735e3309f57"
  },
  {
    "project": "fix_protocols",
    "component": "trireme-lib",
    "pr-id": "747",
    "commit-sha": "f317e333f6416e2bc5fe3a97b1b75161484f8922"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "fix_protocols",
    "component": "enforcerd",
    "pr-id": "1046",
    "commit-sha": "4aceff894550a2fae56260ed4c5c3735e3309f57"
  },
  {
    "project": "fix_protocols",
    "component": "trireme-lib",
    "pr-id": "747",
    "commit-sha": "69a407a09c11802ad036f79984d05be0c9267db4"
  }
]
```

**Review by amitlimaye — APPROVED** [review]

**Pull request merged**
