### PR TITLE
Add metadata header in health requests

### PR DESCRIPTION
**Pull request by dstiliadis**
Mandates a metadata header in health requests to avoid data extrafiltration through SSRF.

### CODE REVIEW

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1322",
    "commit-sha": "10c3a517250206e50856935aa5a2459a99155bae"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "851",
    "commit-sha": "e87466e5e6ebcd1e070fe7c5418238f8573a3aec"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "metadata",
    "component": "apotests-lib",
    "pr-id": "178",
    "commit-sha": "0d91817852f538c2221e984923630d7780ae964b"
  },
  {
    "project": "metadata",
    "component": "trireme-lib",
    "pr-id": "851",
    "commit-sha": "e87466e5e6ebcd1e070fe7c5418238f8573a3aec"
  },
  {
    "project": "metadata",
    "component": "enforcerd",
    "pr-id": "1322",
    "commit-sha": "10c3a517250206e50856935aa5a2459a99155bae"
  },
  {
    "project": "metadata",
    "component": "aporeto-init-waitforpu",
    "pr-id": "3",
    "commit-sha": "09dfc209289728e13c73df4425f62a5f817c7d2d"
  },
  {
    "project": "metadata",
    "component": "apotests",
    "pr-id": "2188",
    "commit-sha": "57a42992dd5b608e35bfd0e973f1be6498911172"
  }
]
```

**Comment by abhijitherekar** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "metadata",
    "component": "trireme-lib",
    "pr-id": "851",
    "commit-sha": "e87466e5e6ebcd1e070fe7c5418238f8573a3aec"
  },
  {
    "project": "metadata",
    "component": "enforcerd",
    "pr-id": "1322",
    "commit-sha": "10c3a517250206e50856935aa5a2459a99155bae"
  },
  {
    "project": "metadata",
    "component": "aporeto-init-waitforpu",
    "pr-id": "3",
    "commit-sha": "1447355513b6e4d747a914889d9e3d9e15aec81d"
  },
  {
    "project": "metadata",
    "component": "apotests",
    "pr-id": "2188",
    "commit-sha": "57a42992dd5b608e35bfd0e973f1be6498911172"
  },
  {
    "project": "metadata",
    "component": "apotests-lib",
    "pr-id": "178",
    "commit-sha": "0d91817852f538c2221e984923630d7780ae964b"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "metadata",
    "component": "apotests-lib",
    "pr-id": "178",
    "commit-sha": "953aa32076bf568d92b16fd508e44baf9a2337d5"
  },
  {
    "project": "metadata",
    "component": "trireme-lib",
    "pr-id": "851",
    "commit-sha": "e87466e5e6ebcd1e070fe7c5418238f8573a3aec"
  },
  {
    "project": "metadata",
    "component": "enforcerd",
    "pr-id": "1322",
    "commit-sha": "10c3a517250206e50856935aa5a2459a99155bae"
  },
  {
    "project": "metadata",
    "component": "aporeto-init-waitforpu",
    "pr-id": "3",
    "commit-sha": "1447355513b6e4d747a914889d9e3d9e15aec81d"
  },
  {
    "project": "metadata",
    "component": "apotests",
    "pr-id": "2188",
    "commit-sha": "57a42992dd5b608e35bfd0e973f1be6498911172"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "metadata",
    "component": "apotests-lib",
    "pr-id": "178",
    "commit-sha": "953aa32076bf568d92b16fd508e44baf9a2337d5"
  },
  {
    "project": "metadata",
    "component": "trireme-lib",
    "pr-id": "851",
    "commit-sha": "e87466e5e6ebcd1e070fe7c5418238f8573a3aec"
  },
  {
    "project": "metadata",
    "component": "enforcerd",
    "pr-id": "1322",
    "commit-sha": "10c3a517250206e50856935aa5a2459a99155bae"
  },
  {
    "project": "metadata",
    "component": "aporeto-init-waitforpu",
    "pr-id": "3",
    "commit-sha": "1447355513b6e4d747a914889d9e3d9e15aec81d"
  },
  {
    "project": "metadata",
    "component": "apotests",
    "pr-id": "2188",
    "commit-sha": "57a42992dd5b608e35bfd0e973f1be6498911172"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "metadata",
    "component": "enforcerd",
    "pr-id": "1322",
    "commit-sha": "10c3a517250206e50856935aa5a2459a99155bae"
  },
  {
    "project": "metadata",
    "component": "apotests",
    "pr-id": "2188",
    "commit-sha": "57a42992dd5b608e35bfd0e973f1be6498911172"
  },
  {
    "project": "metadata",
    "component": "apotests-lib",
    "pr-id": "178",
    "commit-sha": "953aa32076bf568d92b16fd508e44baf9a2337d5"
  },
  {
    "project": "metadata",
    "component": "trireme-lib",
    "pr-id": "851",
    "commit-sha": "e87466e5e6ebcd1e070fe7c5418238f8573a3aec"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "metadata",
    "component": "apotests-lib",
    "pr-id": "178",
    "commit-sha": "a57e88b3870270f6e62568b2175b918e4e21be74"
  },
  {
    "project": "metadata",
    "component": "trireme-lib",
    "pr-id": "851",
    "commit-sha": "e87466e5e6ebcd1e070fe7c5418238f8573a3aec"
  },
  {
    "project": "metadata",
    "component": "enforcerd",
    "pr-id": "1322",
    "commit-sha": "10c3a517250206e50856935aa5a2459a99155bae"
  },
  {
    "project": "metadata",
    "component": "apotests",
    "pr-id": "2188",
    "commit-sha": "57a42992dd5b608e35bfd0e973f1be6498911172"
  }
]
```

**Pull request merged**
