### PR TITLE
Windows enforcer pid allow

### PR DESCRIPTION
**Pull request by philipatl**
Allow enforcer self-traffic

Using new Frontmand v1.0.2 which allows for rules based on pid.

### CODE REVIEW

**Comment by philipatl** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "windows-enforcer-pid-allow",
    "component": "trireme-lib",
    "pr-id": "1027",
    "commit-sha": "a062851552910d514e622e5577e01011c70fc426",
    "pipeline": "master"
  },
  {
    "project": "windows-enforcer-pid-allow",
    "component": "enforcerd",
    "pr-id": "1824",
    "commit-sha": "37634b92b33a9731df9a3facb370084feacb83bc",
    "pipeline": "master"
  }
]
```

**Comment by philipatl** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "windows-enforcer-pid-allow",
    "component": "enforcerd",
    "pr-id": "1824",
    "commit-sha": "37634b92b33a9731df9a3facb370084feacb83bc",
    "pipeline": "master"
  },
  {
    "project": "windows-enforcer-pid-allow",
    "component": "trireme-lib",
    "pr-id": "1027",
    "commit-sha": "a062851552910d514e622e5577e01011c70fc426",
    "pipeline": "master"
  }
]
```

**Comment by philipatl** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "windows-enforcer-pid-allow",
    "component": "enforcerd",
    "pr-id": "1824",
    "commit-sha": "37634b92b33a9731df9a3facb370084feacb83bc",
    "pipeline": "master"
  },
  {
    "project": "windows-enforcer-pid-allow",
    "component": "trireme-lib",
    "pr-id": "1027",
    "commit-sha": "a062851552910d514e622e5577e01011c70fc426",
    "pipeline": "master"
  }
]
```

**Comment by philipatl** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "1027",
    "commit-sha": "a062851552910d514e622e5577e01011c70fc426",
    "pipeline": "master"
  }
]
```

**Comment by philipatl** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "windows-enforcer-pid-allow",
    "component": "enforcerd",
    "pr-id": "1824",
    "commit-sha": "37634b92b33a9731df9a3facb370084feacb83bc",
    "pipeline": "master"
  },
  {
    "project": "windows-enforcer-pid-allow",
    "component": "trireme-lib",
    "pr-id": "1027",
    "commit-sha": "a062851552910d514e622e5577e01011c70fc426",
    "pipeline": "master"
  }
]
```

**Comment by philipatl** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "windows-enforcer-pid-allow",
    "component": "enforcerd",
    "pr-id": "1824",
    "commit-sha": "37634b92b33a9731df9a3facb370084feacb83bc",
    "pipeline": "release-3.14.0"
  },
  {
    "project": "windows-enforcer-pid-allow",
    "component": "trireme-lib",
    "pr-id": "1027",
    "commit-sha": "a062851552910d514e622e5577e01011c70fc426",
    "pipeline": "release-3.14.0"
  }
]
```

**Comment by philipatl** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "windows-enforcer-pid-allow",
    "component": "enforcerd",
    "pr-id": "1824",
    "commit-sha": "37634b92b33a9731df9a3facb370084feacb83bc",
    "pipeline": "release-3.14.0"
  },
  {
    "project": "windows-enforcer-pid-allow",
    "component": "trireme-lib",
    "pr-id": "1027",
    "commit-sha": "a062851552910d514e622e5577e01011c70fc426",
    "pipeline": "release-3.14.0"
  }
]
```

**Comment by philipatl** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "windows-enforcer-pid-allow",
    "component": "enforcerd",
    "pr-id": "1824",
    "commit-sha": "d7f1dde78dbcf610173227796b7cac833942b89e",
    "pipeline": "release-3.14.0"
  },
  {
    "project": "windows-enforcer-pid-allow",
    "component": "trireme-lib",
    "pr-id": "1027",
    "commit-sha": "a062851552910d514e622e5577e01011c70fc426",
    "pipeline": "release-3.14.0"
  }
]
```

**Comment by philipatl** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "windows-enforcer-pid-allow",
    "component": "enforcerd",
    "pr-id": "1824",
    "commit-sha": "d7f1dde78dbcf610173227796b7cac833942b89e",
    "pipeline": "release-3.14.0"
  },
  {
    "project": "windows-enforcer-pid-allow",
    "component": "trireme-lib",
    "pr-id": "1027",
    "commit-sha": "a062851552910d514e622e5577e01011c70fc426",
    "pipeline": "release-3.14.0"
  }
]
```

**Comment by philipatl** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "windows-enforcer-pid-allow",
    "component": "enforcerd",
    "pr-id": "1824",
    "commit-sha": "29a1c5c5e7560e973671acab8874ae57728170bb",
    "pipeline": "release-3.14.0"
  },
  {
    "project": "windows-enforcer-pid-allow",
    "component": "trireme-lib",
    "pr-id": "1027",
    "commit-sha": "a062851552910d514e622e5577e01011c70fc426",
    "pipeline": "release-3.14.0"
  }
]
```

**Review by tillery-aporeto — APPROVED** [review]

**Review by amitlimaye — APPROVED** [review]

**Review by mheese — APPROVED** [review]

**Pull request merged**
