### PR TITLE
drop duplicate ack packets with fast open

### PR DESCRIPTION
**Pull request by 0xmchadha**
#### Description
*Changes proposed in this pull request.*

#### Test plan
*Outline the test plan used to test this change before merging it.*

> Fixes #.

### CODE REVIEW

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1604",
    "commit-sha": "a5e69aa277e3c8e79d3bccad71488ee2b31d98a7",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "983",
    "commit-sha": "f4fd639a963426e4155364bd35b346ed1466f0e9",
    "pipeline": "master"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1604",
    "commit-sha": "a5e69aa277e3c8e79d3bccad71488ee2b31d98a7",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "983",
    "commit-sha": "1cbb70ea6502b157ee0de91b28fe14c9ced9c002",
    "pipeline": "master"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1604",
    "commit-sha": "a5e69aa277e3c8e79d3bccad71488ee2b31d98a7",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "983",
    "commit-sha": "31d916b4b11914a4236643a963ed5e143c7aa66a",
    "pipeline": "master"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1604",
    "commit-sha": "a5e69aa277e3c8e79d3bccad71488ee2b31d98a7",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "983",
    "commit-sha": "b9096afeae2f3c1aac3aabc1c5f78f6806840170",
    "pipeline": "master"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1604",
    "commit-sha": "a5e69aa277e3c8e79d3bccad71488ee2b31d98a7",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "983",
    "commit-sha": "b9096afeae2f3c1aac3aabc1c5f78f6806840170",
    "pipeline": "master"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1604",
    "commit-sha": "95de8beef21cda01d499d4605efd0878527b99f8",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "983",
    "commit-sha": "b9096afeae2f3c1aac3aabc1c5f78f6806840170",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "458",
    "commit-sha": "c17abba71e50c11f1c96f6c9dbe3a11e35f96ad5",
    "pipeline": "master"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "983",
    "commit-sha": "b9096afeae2f3c1aac3aabc1c5f78f6806840170",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "458",
    "commit-sha": "c17abba71e50c11f1c96f6c9dbe3a11e35f96ad5",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1604",
    "commit-sha": "95de8beef21cda01d499d4605efd0878527b99f8",
    "pipeline": "master"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1604",
    "commit-sha": "95de8beef21cda01d499d4605efd0878527b99f8",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "983",
    "commit-sha": "b9096afeae2f3c1aac3aabc1c5f78f6806840170",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "458",
    "commit-sha": "c17abba71e50c11f1c96f6c9dbe3a11e35f96ad5",
    "pipeline": "master"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1604",
    "commit-sha": "95de8beef21cda01d499d4605efd0878527b99f8",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "983",
    "commit-sha": "b9096afeae2f3c1aac3aabc1c5f78f6806840170",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "458",
    "commit-sha": "c17abba71e50c11f1c96f6c9dbe3a11e35f96ad5",
    "pipeline": "master"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1604",
    "commit-sha": "95de8beef21cda01d499d4605efd0878527b99f8",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "983",
    "commit-sha": "b9096afeae2f3c1aac3aabc1c5f78f6806840170",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "458",
    "commit-sha": "09f9d5a283c77636087a874a38d40a6dfbdfe786",
    "pipeline": "master"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1604",
    "commit-sha": "95de8beef21cda01d499d4605efd0878527b99f8",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "983",
    "commit-sha": "b9096afeae2f3c1aac3aabc1c5f78f6806840170",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "458",
    "commit-sha": "09f9d5a283c77636087a874a38d40a6dfbdfe786",
    "pipeline": "master"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1604",
    "commit-sha": "976810f6c8a139dfadca1e4f1af89673f40439a1",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "983",
    "commit-sha": "b9096afeae2f3c1aac3aabc1c5f78f6806840170",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "458",
    "commit-sha": "09f9d5a283c77636087a874a38d40a6dfbdfe786",
    "pipeline": "master"
  }
]
```

**Review by amitlimaye — DISMISSED** [review]

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1604",
    "commit-sha": "976810f6c8a139dfadca1e4f1af89673f40439a1",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "983",
    "commit-sha": "b9096afeae2f3c1aac3aabc1c5f78f6806840170",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "458",
    "commit-sha": "09f9d5a283c77636087a874a38d40a6dfbdfe786",
    "pipeline": "master"
  }
]
```

**Review by dstiliadis — DISMISSED** [review]
Should work

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1604",
    "commit-sha": "06305f3c66796de1773aa8c0b4c98da970709223",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "983",
    "commit-sha": "b9096afeae2f3c1aac3aabc1c5f78f6806840170",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "458",
    "commit-sha": "09f9d5a283c77636087a874a38d40a6dfbdfe786",
    "pipeline": "master"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1604",
    "commit-sha": "06305f3c66796de1773aa8c0b4c98da970709223",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "983",
    "commit-sha": "b9096afeae2f3c1aac3aabc1c5f78f6806840170",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "458",
    "commit-sha": "09f9d5a283c77636087a874a38d40a6dfbdfe786",
    "pipeline": "master"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1604",
    "commit-sha": "06305f3c66796de1773aa8c0b4c98da970709223",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "983",
    "commit-sha": "b9096afeae2f3c1aac3aabc1c5f78f6806840170",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "458",
    "commit-sha": "09f9d5a283c77636087a874a38d40a6dfbdfe786",
    "pipeline": "master"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "458",
    "commit-sha": "09f9d5a283c77636087a874a38d40a6dfbdfe786",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1604",
    "commit-sha": "06305f3c66796de1773aa8c0b4c98da970709223",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "983",
    "commit-sha": "b9096afeae2f3c1aac3aabc1c5f78f6806840170",
    "pipeline": "master"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "458",
    "commit-sha": "09f9d5a283c77636087a874a38d40a6dfbdfe786",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1604",
    "commit-sha": "06305f3c66796de1773aa8c0b4c98da970709223",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "983",
    "commit-sha": "b9096afeae2f3c1aac3aabc1c5f78f6806840170",
    "pipeline": "master"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "983",
    "commit-sha": "6c61bac08599db5513e2b328da48c1225e624026",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "458",
    "commit-sha": "09f9d5a283c77636087a874a38d40a6dfbdfe786",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1604",
    "commit-sha": "06305f3c66796de1773aa8c0b4c98da970709223",
    "pipeline": "master"
  }
]
```

**Review by amitlimaye — APPROVED** [review]

**Pull request merged**
