### PR TITLE
Update: Bump build to golang 1.12

### PR DESCRIPTION
**Pull request by ericrpowers**
#### Description
Move build environment to golang v1.12 and any necessary changes along the way.

### CODE REVIEW

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "golang-112",
    "component": "claire",
    "pr-id": "62",
    "commit-sha": "4f0556f7ccb88e5c24d220bb7ee80afe8b469ab1"
  },
  {
    "project": "golang-112",
    "component": "mu",
    "pr-id": "9",
    "commit-sha": "04261f8b7828ab72c0b38f131ed8db2ead889e6e"
  },
  {
    "project": "golang-112",
    "component": "aporeto-init-waitforpu",
    "pr-id": "2",
    "commit-sha": "7d991d7faca0c12d5a552eb599ee3a7bae3b7bcb"
  },
  {
    "project": "golang-112",
    "component": "trireme-lib",
    "pr-id": "753",
    "commit-sha": "589b4dd2a38c39d961fe21430b631b4a1da44782"
  },
  {
    "project": "golang-112",
    "component": "backend",
    "pr-id": "318",
    "commit-sha": "aa405ffba854f3bf7649a5cd8e7bf3afeea50d6c"
  },
  {
    "project": "golang-112",
    "component": "enforcerd",
    "pr-id": "1071",
    "commit-sha": "8b37fdb25fbabd7ef66baa54eba1683d30e84616"
  },
  {
    "project": "golang-112",
    "component": "aporeto-operator",
    "pr-id": "41",
    "commit-sha": "48707786f7add45246e19dc92663d930c0464353"
  },
  {
    "project": "golang-112",
    "component": "domingo",
    "pr-id": "67",
    "commit-sha": "a64c76d66fc57e8674435e1c0a8a2abd7b5d8edd"
  },
  {
    "project": "golang-112",
    "component": "concourse-tools",
    "pr-id": "60",
    "commit-sha": "99e65f78f2dd12864216c8db1d0ec0e52e806e53"
  },
  {
    "project": "golang-112",
    "component": "wedge",
    "pr-id": "88",
    "commit-sha": "30cdeb43ebb6b3df2aedd8f77ca9753c70cdae34"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "753",
    "commit-sha": "589b4dd2a38c39d961fe21430b631b4a1da44782"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1071",
    "commit-sha": "8b37fdb25fbabd7ef66baa54eba1683d30e84616"
  },
  {
    "project": "",
    "component": "backend",
    "pr-id": "318",
    "commit-sha": "aa405ffba854f3bf7649a5cd8e7bf3afeea50d6c"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "753",
    "commit-sha": "589b4dd2a38c39d961fe21430b631b4a1da44782"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1071",
    "commit-sha": "8b37fdb25fbabd7ef66baa54eba1683d30e84616"
  },
  {
    "project": "",
    "component": "backend",
    "pr-id": "318",
    "commit-sha": "aa405ffba854f3bf7649a5cd8e7bf3afeea50d6c"
  },
  {
    "project": "",
    "component": "aporeto-init-waitforpu",
    "pr-id": "2",
    "commit-sha": "6325b10dec3482766cf10dacbb73faebd5d9d9fe"
  },
  {
    "project": "",
    "component": "claire",
    "pr-id": "62",
    "commit-sha": "4f0556f7ccb88e5c24d220bb7ee80afe8b469ab1"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "753",
    "commit-sha": "589b4dd2a38c39d961fe21430b631b4a1da44782"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1071",
    "commit-sha": "8b37fdb25fbabd7ef66baa54eba1683d30e84616"
  },
  {
    "project": "",
    "component": "claire",
    "pr-id": "62",
    "commit-sha": "71e874473dd0d8365271a72b980c7c0ee821ba2d"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "753",
    "commit-sha": "589b4dd2a38c39d961fe21430b631b4a1da44782"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1071",
    "commit-sha": "04f06a77635195d47b144160fabe844c7a71a8bc"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "golang-112",
    "component": "backend",
    "pr-id": "318",
    "commit-sha": "283354968d76d12b066e94278d65656cca1ca7f1"
  },
  {
    "project": "golang-112",
    "component": "enforcerd",
    "pr-id": "1071",
    "commit-sha": "c5de26a33927bd0b1915fa73b1821195e5d6497f"
  },
  {
    "project": "golang-112",
    "component": "claire",
    "pr-id": "62",
    "commit-sha": "71e874473dd0d8365271a72b980c7c0ee821ba2d"
  },
  {
    "project": "golang-112",
    "component": "wedge",
    "pr-id": "88",
    "commit-sha": "30cdeb43ebb6b3df2aedd8f77ca9753c70cdae34"
  },
  {
    "project": "golang-112",
    "component": "mu",
    "pr-id": "9",
    "commit-sha": "04261f8b7828ab72c0b38f131ed8db2ead889e6e"
  },
  {
    "project": "golang-112",
    "component": "aporeto-operator",
    "pr-id": "41",
    "commit-sha": "48707786f7add45246e19dc92663d930c0464353"
  },
  {
    "project": "golang-112",
    "component": "aporeto-init-waitforpu",
    "pr-id": "2",
    "commit-sha": "6325b10dec3482766cf10dacbb73faebd5d9d9fe"
  },
  {
    "project": "golang-112",
    "component": "trireme-lib",
    "pr-id": "753",
    "commit-sha": "589b4dd2a38c39d961fe21430b631b4a1da44782"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "wedge",
    "pr-id": "88",
    "commit-sha": "8c8dcf62ea41f1decb90df8823a3987aaf99bf70"
  },
  {
    "project": "",
    "component": "aporeto-operator",
    "pr-id": "41",
    "commit-sha": "87138ae21ee2c171ef0c7bf9bd813b082a3753ff"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "753",
    "commit-sha": "589b4dd2a38c39d961fe21430b631b4a1da44782"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1071",
    "commit-sha": "c5de26a33927bd0b1915fa73b1821195e5d6497f"
  },
  {
    "project": "",
    "component": "backend",
    "pr-id": "318",
    "commit-sha": "283354968d76d12b066e94278d65656cca1ca7f1"
  },
  {
    "project": "",
    "component": "claire",
    "pr-id": "62",
    "commit-sha": "28d0bcc4b5af6262adfe72cb7e142f2712225691"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "753",
    "commit-sha": "589b4dd2a38c39d961fe21430b631b4a1da44782"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1071",
    "commit-sha": "c5de26a33927bd0b1915fa73b1821195e5d6497f"
  },
  {
    "project": "",
    "component": "backend",
    "pr-id": "318",
    "commit-sha": "283354968d76d12b066e94278d65656cca1ca7f1"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "753",
    "commit-sha": "589b4dd2a38c39d961fe21430b631b4a1da44782"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1071",
    "commit-sha": "c5de26a33927bd0b1915fa73b1821195e5d6497f"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "golang-112",
    "component": "trireme-lib",
    "pr-id": "753",
    "commit-sha": "a01dfb9444c1dc2cea0c06161673b3cd83903e8a"
  },
  {
    "project": "golang-112",
    "component": "backend",
    "pr-id": "318",
    "commit-sha": "623798c87a730601a00da0403f0e143da62191df"
  },
  {
    "project": "golang-112",
    "component": "enforcerd",
    "pr-id": "1071",
    "commit-sha": "47528d77f96b5d44e4eb18fa1d46bbe9a2c1f889"
  },
  {
    "project": "golang-112",
    "component": "claire",
    "pr-id": "62",
    "commit-sha": "28d0bcc4b5af6262adfe72cb7e142f2712225691"
  },
  {
    "project": "golang-112",
    "component": "wedge",
    "pr-id": "88",
    "commit-sha": "8c8dcf62ea41f1decb90df8823a3987aaf99bf70"
  },
  {
    "project": "golang-112",
    "component": "aporeto-operator",
    "pr-id": "41",
    "commit-sha": "e3f5d9f78b04779b636a9f191f18866f7a1872d6"
  },
  {
    "project": "golang-112",
    "component": "mu",
    "pr-id": "9",
    "commit-sha": "04261f8b7828ab72c0b38f131ed8db2ead889e6e"
  },
  {
    "project": "golang-112",
    "component": "aporeto-init-waitforpu",
    "pr-id": "2",
    "commit-sha": "6325b10dec3482766cf10dacbb73faebd5d9d9fe"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "golang-112",
    "component": "backend",
    "pr-id": "318",
    "commit-sha": "ad3809e97eae60542821b3eda75b2a86b4d5f83c"
  },
  {
    "project": "golang-112",
    "component": "enforcerd",
    "pr-id": "1071",
    "commit-sha": "47528d77f96b5d44e4eb18fa1d46bbe9a2c1f889"
  },
  {
    "project": "golang-112",
    "component": "claire",
    "pr-id": "62",
    "commit-sha": "37066c07e5a68cc3a5c5a7748eee69e3820f0063"
  },
  {
    "project": "golang-112",
    "component": "wedge",
    "pr-id": "88",
    "commit-sha": "8c8dcf62ea41f1decb90df8823a3987aaf99bf70"
  },
  {
    "project": "golang-112",
    "component": "aporeto-operator",
    "pr-id": "41",
    "commit-sha": "bc6495a62304514ab42cd59fdaae3f744fc21c01"
  },
  {
    "project": "golang-112",
    "component": "mu",
    "pr-id": "9",
    "commit-sha": "04261f8b7828ab72c0b38f131ed8db2ead889e6e"
  },
  {
    "project": "golang-112",
    "component": "aporeto-init-waitforpu",
    "pr-id": "2",
    "commit-sha": "6325b10dec3482766cf10dacbb73faebd5d9d9fe"
  },
  {
    "project": "golang-112",
    "component": "trireme-lib",
    "pr-id": "753",
    "commit-sha": "46860be61320f4f9fd3bdbcf6af198e615872cfa"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "318",
    "commit-sha": "ad3809e97eae60542821b3eda75b2a86b4d5f83c"
  },
  {
    "project": "",
    "component": "wedge",
    "pr-id": "88",
    "commit-sha": "8c8dcf62ea41f1decb90df8823a3987aaf99bf70"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1071",
    "commit-sha": "47528d77f96b5d44e4eb18fa1d46bbe9a2c1f889"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "753",
    "commit-sha": "46860be61320f4f9fd3bdbcf6af198e615872cfa"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "318",
    "commit-sha": "ad3809e97eae60542821b3eda75b2a86b4d5f83c"
  },
  {
    "project": "",
    "component": "wedge",
    "pr-id": "88",
    "commit-sha": "8c8dcf62ea41f1decb90df8823a3987aaf99bf70"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1071",
    "commit-sha": "47528d77f96b5d44e4eb18fa1d46bbe9a2c1f889"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "753",
    "commit-sha": "46860be61320f4f9fd3bdbcf6af198e615872cfa"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "318",
    "commit-sha": "ad3809e97eae60542821b3eda75b2a86b4d5f83c"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1071",
    "commit-sha": "47528d77f96b5d44e4eb18fa1d46bbe9a2c1f889"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "753",
    "commit-sha": "46860be61320f4f9fd3bdbcf6af198e615872cfa"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "wedge",
    "pr-id": "88",
    "commit-sha": "b8b98c644d317b9267e7cd0e2d00426e196781aa"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1071",
    "commit-sha": "1ed468f00f431afd238a479c12e46429fad9b8b7"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "753",
    "commit-sha": "90bd53f82c676f97abe4c6d044a84d71d305e2a3"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "wedge",
    "pr-id": "88",
    "commit-sha": "b8b98c644d317b9267e7cd0e2d00426e196781aa"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1071",
    "commit-sha": "1ed468f00f431afd238a479c12e46429fad9b8b7"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "753",
    "commit-sha": "90bd53f82c676f97abe4c6d044a84d71d305e2a3"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1071",
    "commit-sha": "1ed468f00f431afd238a479c12e46429fad9b8b7"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "753",
    "commit-sha": "90bd53f82c676f97abe4c6d044a84d71d305e2a3"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1071",
    "commit-sha": "440a5d66e894f076a2e86f1b83076c00eb31f9e9"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "753",
    "commit-sha": "90bd53f82c676f97abe4c6d044a84d71d305e2a3"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "753",
    "commit-sha": "90bd53f82c676f97abe4c6d044a84d71d305e2a3"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1071",
    "commit-sha": "440a5d66e894f076a2e86f1b83076c00eb31f9e9"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1071",
    "commit-sha": "440a5d66e894f076a2e86f1b83076c00eb31f9e9"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "753",
    "commit-sha": "90bd53f82c676f97abe4c6d044a84d71d305e2a3"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "753",
    "commit-sha": "90bd53f82c676f97abe4c6d044a84d71d305e2a3"
  },
  {
    "project": "",
    "component": "backend",
    "pr-id": "318",
    "commit-sha": "de1005744f384e6ccdac66ece1f78042ddb4732f"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1071",
    "commit-sha": "440a5d66e894f076a2e86f1b83076c00eb31f9e9"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1071",
    "commit-sha": "440a5d66e894f076a2e86f1b83076c00eb31f9e9"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "753",
    "commit-sha": "90bd53f82c676f97abe4c6d044a84d71d305e2a3"
  },
  {
    "project": "",
    "component": "backend",
    "pr-id": "318",
    "commit-sha": "de1005744f384e6ccdac66ece1f78042ddb4732f"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "318",
    "commit-sha": "f374ec901243780a1e3fb9921d95af658b600133"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1071",
    "commit-sha": "440a5d66e894f076a2e86f1b83076c00eb31f9e9"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "753",
    "commit-sha": "b2b1aff56c0f41366809b2933643eb6df00df155"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1071",
    "commit-sha": "440a5d66e894f076a2e86f1b83076c00eb31f9e9"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "753",
    "commit-sha": "b2b1aff56c0f41366809b2933643eb6df00df155"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "golang-112",
    "component": "enforcerd",
    "pr-id": "1071",
    "commit-sha": "fedd9c3112c2884a3a39e83d96f5a8a35aa13f08"
  },
  {
    "project": "golang-112",
    "component": "backend",
    "pr-id": "318",
    "commit-sha": "f374ec901243780a1e3fb9921d95af658b600133"
  },
  {
    "project": "golang-112",
    "component": "wedge",
    "pr-id": "88",
    "commit-sha": "b8b98c644d317b9267e7cd0e2d00426e196781aa"
  },
  {
    "project": "golang-112",
    "component": "claire",
    "pr-id": "62",
    "commit-sha": "f53fd4adc9bb272aa2425bfcc199d52547fed87c"
  },
  {
    "project": "golang-112",
    "component": "aporeto-operator",
    "pr-id": "41",
    "commit-sha": "f13f6cc9ed9aec5bd00cbeeb7bce7cc106488ea8"
  },
  {
    "project": "golang-112",
    "component": "mu",
    "pr-id": "9",
    "commit-sha": "04261f8b7828ab72c0b38f131ed8db2ead889e6e"
  },
  {
    "project": "golang-112",
    "component": "aporeto-init-waitforpu",
    "pr-id": "2",
    "commit-sha": "6325b10dec3482766cf10dacbb73faebd5d9d9fe"
  },
  {
    "project": "golang-112",
    "component": "trireme-lib",
    "pr-id": "753",
    "commit-sha": "74294f8ceee30d09adf9de5844d8bcf39c88d650"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "golang-112",
    "component": "claire",
    "pr-id": "62",
    "commit-sha": "f53fd4adc9bb272aa2425bfcc199d52547fed87c"
  },
  {
    "project": "golang-112",
    "component": "aporeto-operator",
    "pr-id": "41",
    "commit-sha": "f13f6cc9ed9aec5bd00cbeeb7bce7cc106488ea8"
  },
  {
    "project": "golang-112",
    "component": "mu",
    "pr-id": "9",
    "commit-sha": "1e87d3e6605da1addf5c4260ca80c9ff6dca3abd"
  },
  {
    "project": "golang-112",
    "component": "aporeto-init-waitforpu",
    "pr-id": "2",
    "commit-sha": "6325b10dec3482766cf10dacbb73faebd5d9d9fe"
  },
  {
    "project": "golang-112",
    "component": "trireme-lib",
    "pr-id": "753",
    "commit-sha": "74294f8ceee30d09adf9de5844d8bcf39c88d650"
  },
  {
    "project": "golang-112",
    "component": "enforcerd",
    "pr-id": "1071",
    "commit-sha": "fedd9c3112c2884a3a39e83d96f5a8a35aa13f08"
  },
  {
    "project": "golang-112",
    "component": "backend",
    "pr-id": "318",
    "commit-sha": "fd5f2c9d5f9a0caa961066c1f323c3e3a6885a48"
  },
  {
    "project": "golang-112",
    "component": "wedge",
    "pr-id": "88",
    "commit-sha": "b8b98c644d317b9267e7cd0e2d00426e196781aa"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1071",
    "commit-sha": "fedd9c3112c2884a3a39e83d96f5a8a35aa13f08"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "753",
    "commit-sha": "74294f8ceee30d09adf9de5844d8bcf39c88d650"
  },
  {
    "project": "",
    "component": "backend",
    "pr-id": "318",
    "commit-sha": "fd5f2c9d5f9a0caa961066c1f323c3e3a6885a48"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "golang-112",
    "component": "enforcerd",
    "pr-id": "1071",
    "commit-sha": "bd35c89afc6d20cecdea60b6f7c60b7cb39cf0ad"
  },
  {
    "project": "golang-112",
    "component": "backend",
    "pr-id": "318",
    "commit-sha": "a89ed85b3c5d0e769ecb7a61266719343249b40b"
  },
  {
    "project": "golang-112",
    "component": "wedge",
    "pr-id": "88",
    "commit-sha": "7e259e53f136e3e3bab80810185d828ee4d2a1d5"
  },
  {
    "project": "golang-112",
    "component": "claire",
    "pr-id": "62",
    "commit-sha": "4318569d6119d0ef91ff80d9b3f6a30095072b64"
  },
  {
    "project": "golang-112",
    "component": "aporeto-operator",
    "pr-id": "41",
    "commit-sha": "0a4fcb9cc8e8c15409d92a2ce72933bb4b5a35b8"
  },
  {
    "project": "golang-112",
    "component": "aporeto-init-waitforpu",
    "pr-id": "2",
    "commit-sha": "6325b10dec3482766cf10dacbb73faebd5d9d9fe"
  },
  {
    "project": "golang-112",
    "component": "trireme-lib",
    "pr-id": "753",
    "commit-sha": "76397b3447263a993d809449286f270473405787"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1071",
    "commit-sha": "e6b74cb8b18120714759abb52c9a50e43fde4dd3"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "753",
    "commit-sha": "76397b3447263a993d809449286f270473405787"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1071",
    "commit-sha": "87d276f76d2f632f4e2d2e6779a0a6a63d4138c3"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "753",
    "commit-sha": "76397b3447263a993d809449286f270473405787"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1071",
    "commit-sha": "283d086e6fba4de4da0d7674a58b79ceb2e65192"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "753",
    "commit-sha": "76397b3447263a993d809449286f270473405787"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1071",
    "commit-sha": "8866ae6e06bd0662d2965bb95577b6c63e0e7818"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "753",
    "commit-sha": "77c0b84a1488c5124d5ab3f495809c2c1509a7ef"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "golang-112",
    "component": "enforcerd",
    "pr-id": "1071",
    "commit-sha": "f539d949072e098716bb24559707774889bdea9d"
  },
  {
    "project": "golang-112",
    "component": "backend",
    "pr-id": "318",
    "commit-sha": "3706d1307875f160b06948b5d3f9cc4b5e5dd5b1"
  },
  {
    "project": "golang-112",
    "component": "wedge",
    "pr-id": "88",
    "commit-sha": "779da2ba3efc338fd3b03ab7b2661fc3f0dea28f"
  },
  {
    "project": "golang-112",
    "component": "claire",
    "pr-id": "62",
    "commit-sha": "5b3b1792a46605131140cc3b24d7470c320bb97a"
  },
  {
    "project": "golang-112",
    "component": "aporeto-operator",
    "pr-id": "41",
    "commit-sha": "0a4fcb9cc8e8c15409d92a2ce72933bb4b5a35b8"
  },
  {
    "project": "golang-112",
    "component": "aporeto-init-waitforpu",
    "pr-id": "2",
    "commit-sha": "6325b10dec3482766cf10dacbb73faebd5d9d9fe"
  },
  {
    "project": "golang-112",
    "component": "trireme-lib",
    "pr-id": "753",
    "commit-sha": "f1c15969001cbe9e27a8b3c83a9294e05a7c30c1"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "753",
    "commit-sha": "f1c15969001cbe9e27a8b3c83a9294e05a7c30c1"
  },
  {
    "project": "",
    "component": "claire",
    "pr-id": "62",
    "commit-sha": "5b3b1792a46605131140cc3b24d7470c320bb97a"
  },
  {
    "project": "",
    "component": "aporeto-operator",
    "pr-id": "41",
    "commit-sha": "ba3da966617e7f8d56ec4cf5215e4f88f821e6c8"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1071",
    "commit-sha": "f539d949072e098716bb24559707774889bdea9d"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1071",
    "commit-sha": "f539d949072e098716bb24559707774889bdea9d"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "753",
    "commit-sha": "f1c15969001cbe9e27a8b3c83a9294e05a7c30c1"
  },
  {
    "project": "",
    "component": "claire",
    "pr-id": "62",
    "commit-sha": "069086af5602aeb5866c6937a9dfbabab8da293f"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "golang-112",
    "component": "enforcerd",
    "pr-id": "1071",
    "commit-sha": "467439dbb1d31cb70bba29a349a23aab5bbe718a"
  },
  {
    "project": "golang-112",
    "component": "backend",
    "pr-id": "318",
    "commit-sha": "61c445bf27a291e2c042dca634cd123ba3c34d7e"
  },
  {
    "project": "golang-112",
    "component": "wedge",
    "pr-id": "88",
    "commit-sha": "779da2ba3efc338fd3b03ab7b2661fc3f0dea28f"
  },
  {
    "project": "golang-112",
    "component": "claire",
    "pr-id": "62",
    "commit-sha": "069086af5602aeb5866c6937a9dfbabab8da293f"
  },
  {
    "project": "golang-112",
    "component": "aporeto-operator",
    "pr-id": "41",
    "commit-sha": "39d468a8e71c6b1bf22977142bd7b72374055011"
  },
  {
    "project": "golang-112",
    "component": "aporeto-init-waitforpu",
    "pr-id": "2",
    "commit-sha": "6325b10dec3482766cf10dacbb73faebd5d9d9fe"
  },
  {
    "project": "golang-112",
    "component": "trireme-lib",
    "pr-id": "753",
    "commit-sha": "9b1604624b357aacdd498031e69359a9be443481"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "wedge",
    "pr-id": "88",
    "commit-sha": "2ff853273bcd21c9d8ec09537f642fe9793b3a8f"
  },
  {
    "project": "",
    "component": "claire",
    "pr-id": "62",
    "commit-sha": "8cc6c611829840de6fd815fd6d62fa98f22c0ba4"
  },
  {
    "project": "",
    "component": "aporeto-operator",
    "pr-id": "41",
    "commit-sha": "62215828b1e5c108ea148159fd9c68c14e135ae5"
  },
  {
    "project": "",
    "component": "aporeto-init-waitforpu",
    "pr-id": "2",
    "commit-sha": "6325b10dec3482766cf10dacbb73faebd5d9d9fe"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "753",
    "commit-sha": "c7b22fbb61817837802d101050309510ef815fa6"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1071",
    "commit-sha": "81cf6a2eeb3894ffe397ed837fe64c5f009b401a"
  },
  {
    "project": "",
    "component": "backend",
    "pr-id": "318",
    "commit-sha": "72e96c4f1c7f1129416b7f881484390cdc34af64"
  }
]
```

**Review by sibicramesh — APPROVED** [review]
LGTM

**Pull request merged**
