### PR TITLE
fix ip address in proxy

### PR DESCRIPTION
**Pull request by 0xmchadha**

### CODE REVIEW

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "972",
    "commit-sha": "72a470cfa7f5622eeeaa24d8111881b8440f78e1"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "712",
    "commit-sha": "746ffb75b3338f3d75d301550ee71e24a411fa7d"
  }
]
```

**Review by dstiliadis — DISMISSED** [review]

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "972",
    "commit-sha": "72a470cfa7f5622eeeaa24d8111881b8440f78e1"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "712",
    "commit-sha": "746ffb75b3338f3d75d301550ee71e24a411fa7d"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "983",
    "commit-sha": "5d0dbae31ac72c8814f725bd1fddea672602a58f"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "712",
    "commit-sha": "746ffb75b3338f3d75d301550ee71e24a411fa7d"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "983",
    "commit-sha": "5d0dbae31ac72c8814f725bd1fddea672602a58f"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "712",
    "commit-sha": "96bafca54094d631a691b0a7eb6daf29669f429f"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "983",
    "commit-sha": "5d0dbae31ac72c8814f725bd1fddea672602a58f"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "712",
    "commit-sha": "fd57fc3aee57e39e5239bd9a64109ec6c141c4ae"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "983",
    "commit-sha": "5d0dbae31ac72c8814f725bd1fddea672602a58f"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "712",
    "commit-sha": "57ce3a2fef6932cdf4afe9d9e0d600b1c073dd87"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "983",
    "commit-sha": "10d0496ef6038008fbf8374f5b5bcb0c4b00fb02"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "712",
    "commit-sha": "22087acde638e670633a6ee1ce8bd776f8de852e"
  }
]
```

**Review by varks — APPROVED** [review]

**Pull request merged**
