### PR TITLE
Fix: Standardize tags

### PR DESCRIPTION
**Pull request by sibicramesh**
--> [tag categories](https://docs.google.com/spreadsheets/d/1LXkYorqnv0Oi_nsMW-vgX4oBGS8gm4XIWqU-bDBUuHc/edit#gid=672738717)
--> [tag guidelines](https://docs.google.com/document/d/1oMM0AEZv0VlHja2EksKIqy1kuQvdmK7hoK4GdFp7WGU/edit#)
--> [project](https://github.com/orgs/aporeto-inc/projects/286)
--> [issue](https://github.com/aporeto-inc/aporeto/issues/844)

**NOTE**: Search for `OLDTAGS` and remove them in the next release

### CODE REVIEW

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "standardize-tags",
    "component": "enforcerd",
    "pr-id": "1007",
    "commit-sha": "ece2f26c6222733becdfc740e8cc0570e662ab2f"
  },
  {
    "project": "standardize-tags",
    "component": "trireme-lib",
    "pr-id": "726",
    "commit-sha": "bb05262a6e660833ad3507affcf160af80a7479e"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "standardize-tags",
    "component": "enforcerd",
    "pr-id": "1007",
    "commit-sha": "97a6aa7c0e90fd37086af5ffa026e74a3241d718"
  },
  {
    "project": "standardize-tags",
    "component": "trireme-lib",
    "pr-id": "726",
    "commit-sha": "7394d45adc7d63875896575c6cc0c0872bfdec61"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "standardize-tags",
    "component": "enforcerd",
    "pr-id": "1007",
    "commit-sha": "53b516de6cd14971f5635664ef758b3762d411cd"
  },
  {
    "project": "standardize-tags",
    "component": "trireme-lib",
    "pr-id": "726",
    "commit-sha": "fcef0e2dc71a9e2b8ba58bc5229ee9c6b89bce89"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "standardize-tags",
    "component": "enforcerd",
    "pr-id": "1007",
    "commit-sha": "df9e3bec83785b93daae332710c77175b4186882"
  },
  {
    "project": "standardize-tags",
    "component": "trireme-lib",
    "pr-id": "726",
    "commit-sha": "fcef0e2dc71a9e2b8ba58bc5229ee9c6b89bce89"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "standardize-tags",
    "component": "enforcerd",
    "pr-id": "1007",
    "commit-sha": "df01f525c81addb41fb3e2ae2bd631705039b929"
  },
  {
    "project": "standardize-tags",
    "component": "trireme-lib",
    "pr-id": "726",
    "commit-sha": "fcef0e2dc71a9e2b8ba58bc5229ee9c6b89bce89"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "standardize-tags",
    "component": "enforcerd",
    "pr-id": "1007",
    "commit-sha": "eef04e11510bf73bbd29cd136f2c52f8ba2ce99f"
  },
  {
    "project": "standardize-tags",
    "component": "trireme-lib",
    "pr-id": "726",
    "commit-sha": "fcef0e2dc71a9e2b8ba58bc5229ee9c6b89bce89"
  },
  {
    "project": "standardize-tags",
    "component": "underwater",
    "pr-id": "33",
    "commit-sha": "6807b0bfc2fd069ebeef77e0aa1a9c2280b99e98"
  },
  {
    "project": "standardize-tags",
    "component": "claire",
    "pr-id": "53",
    "commit-sha": "beace1d1d4254d473e4bbdb52c9880d48c36385e"
  },
  {
    "project": "standardize-tags",
    "component": "wedge",
    "pr-id": "74",
    "commit-sha": "d12f6c6dd548a4a06778ee955b030f08e863a816"
  }
]
```

**Comment by t00f** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "standardize-tags",
    "component": "wedge",
    "pr-id": "74",
    "commit-sha": "d12f6c6dd548a4a06778ee955b030f08e863a816"
  },
  {
    "project": "standardize-tags",
    "component": "enforcerd",
    "pr-id": "1007",
    "commit-sha": "eef04e11510bf73bbd29cd136f2c52f8ba2ce99f"
  },
  {
    "project": "standardize-tags",
    "component": "trireme-lib",
    "pr-id": "726",
    "commit-sha": "fcef0e2dc71a9e2b8ba58bc5229ee9c6b89bce89"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "standardize-tags",
    "component": "enforcerd",
    "pr-id": "1007",
    "commit-sha": "097dc9ba522fb0833b3607e42d268c97c74e7fff"
  },
  {
    "project": "standardize-tags",
    "component": "trireme-lib",
    "pr-id": "726",
    "commit-sha": "d896fed3861dd5a5b08c03fc38147d05ae72980c"
  },
  {
    "project": "standardize-tags",
    "component": "wedge",
    "pr-id": "74",
    "commit-sha": "a3c866d3f0162bb784f2e54bd4bea21ae06c4c57"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "standardize-tags",
    "component": "enforcerd",
    "pr-id": "1007",
    "commit-sha": "faf013fac847edc61f86da6f1118ecafe05f5f19"
  },
  {
    "project": "standardize-tags",
    "component": "trireme-lib",
    "pr-id": "726",
    "commit-sha": "d896fed3861dd5a5b08c03fc38147d05ae72980c"
  },
  {
    "project": "standardize-tags",
    "component": "wedge",
    "pr-id": "74",
    "commit-sha": "a3c866d3f0162bb784f2e54bd4bea21ae06c4c57"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "standardize-tags",
    "component": "enforcerd",
    "pr-id": "1007",
    "commit-sha": "807005574a89b5f07f48b93ebf1dd6e5fc421ce2"
  },
  {
    "project": "standardize-tags",
    "component": "trireme-lib",
    "pr-id": "726",
    "commit-sha": "d896fed3861dd5a5b08c03fc38147d05ae72980c"
  },
  {
    "project": "standardize-tags",
    "component": "wedge",
    "pr-id": "74",
    "commit-sha": "a3c866d3f0162bb784f2e54bd4bea21ae06c4c57"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "standardize-tags",
    "component": "enforcerd",
    "pr-id": "1007",
    "commit-sha": "dc59d2846ad9f3d0f96a5d17ef68f206d8fc1df5"
  },
  {
    "project": "standardize-tags",
    "component": "trireme-lib",
    "pr-id": "726",
    "commit-sha": "d896fed3861dd5a5b08c03fc38147d05ae72980c"
  },
  {
    "project": "standardize-tags",
    "component": "wedge",
    "pr-id": "74",
    "commit-sha": "a3c866d3f0162bb784f2e54bd4bea21ae06c4c57"
  }
]
```

**Review by dstiliadis — APPROVED** [review]

**Pull request merged**
