### PR TITLE
new: management namespace

### PR DESCRIPTION
**Pull request by sibicramesh**
--> Trireme supports one more sub identifier called `managementNamespace`, which can be used to group PU's.

### CODE REVIEW

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "management-ns",
    "component": "trireme-lib",
    "pr-id": "821",
    "commit-sha": "2d74a3aeb4982a31cfada82cb3b24bbe717a2bd5"
  },
  {
    "project": "management-ns",
    "component": "gaia",
    "pr-id": "351",
    "commit-sha": "612fb92c96f8423bb735b971781bb3de04eb8ecb"
  },
  {
    "project": "management-ns",
    "component": "enforcerd",
    "pr-id": "1250",
    "commit-sha": "f72cf1525ed50e12220d16f0b244d1cde27f9f20"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "management-ns",
    "component": "enforcerd",
    "pr-id": "1250",
    "commit-sha": "65c3b919ddb057412a27efb0d7a8f0d62e1776ed"
  },
  {
    "project": "management-ns",
    "component": "trireme-lib",
    "pr-id": "821",
    "commit-sha": "2d74a3aeb4982a31cfada82cb3b24bbe717a2bd5"
  },
  {
    "project": "management-ns",
    "component": "gaia",
    "pr-id": "351",
    "commit-sha": "612fb92c96f8423bb735b971781bb3de04eb8ecb"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "management-ns",
    "component": "enforcerd",
    "pr-id": "1250",
    "commit-sha": "6c73f1a53a0b1c7fb14210737c44ab06fff1d035"
  },
  {
    "project": "management-ns",
    "component": "trireme-lib",
    "pr-id": "821",
    "commit-sha": "4e0234bc033b286d9e25f5d6ca871599b10ceb11"
  },
  {
    "project": "management-ns",
    "component": "gaia",
    "pr-id": "351",
    "commit-sha": "612fb92c96f8423bb735b971781bb3de04eb8ecb"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "management-ns",
    "component": "enforcerd",
    "pr-id": "1250",
    "commit-sha": "cf379872f7b381807c8a73f9fdd277d3bb16965d"
  },
  {
    "project": "management-ns",
    "component": "trireme-lib",
    "pr-id": "821",
    "commit-sha": "4e0234bc033b286d9e25f5d6ca871599b10ceb11"
  },
  {
    "project": "management-ns",
    "component": "gaia",
    "pr-id": "351",
    "commit-sha": "612fb92c96f8423bb735b971781bb3de04eb8ecb"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "management-ns",
    "component": "enforcerd",
    "pr-id": "1250",
    "commit-sha": "d287948e9f4afa3a93725c8826ac325e2476db1c"
  },
  {
    "project": "management-ns",
    "component": "trireme-lib",
    "pr-id": "821",
    "commit-sha": "4e0234bc033b286d9e25f5d6ca871599b10ceb11"
  },
  {
    "project": "management-ns",
    "component": "gaia",
    "pr-id": "351",
    "commit-sha": "612fb92c96f8423bb735b971781bb3de04eb8ecb"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "management-ns",
    "component": "enforcerd",
    "pr-id": "1250",
    "commit-sha": "d1b7671381dcd18e55fcb6d34ea3174aefcb41d4"
  },
  {
    "project": "management-ns",
    "component": "trireme-lib",
    "pr-id": "821",
    "commit-sha": "4e0234bc033b286d9e25f5d6ca871599b10ceb11"
  },
  {
    "project": "management-ns",
    "component": "gaia",
    "pr-id": "351",
    "commit-sha": "612fb92c96f8423bb735b971781bb3de04eb8ecb"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "management-ns",
    "component": "trireme-lib",
    "pr-id": "821",
    "commit-sha": "4e0234bc033b286d9e25f5d6ca871599b10ceb11"
  },
  {
    "project": "management-ns",
    "component": "gaia",
    "pr-id": "351",
    "commit-sha": "612fb92c96f8423bb735b971781bb3de04eb8ecb"
  },
  {
    "project": "management-ns",
    "component": "enforcerd",
    "pr-id": "1250",
    "commit-sha": "6f6e8fcd389cbf5304dfa0be5768e7c68d126add"
  }
]
```

**Review by dstiliadis — DISMISSED** [review]

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "management-ns",
    "component": "enforcerd",
    "pr-id": "1250",
    "commit-sha": "8df510097794219da28831a5a3cd61170ddc7b34"
  },
  {
    "project": "management-ns",
    "component": "trireme-lib",
    "pr-id": "821",
    "commit-sha": "4e0234bc033b286d9e25f5d6ca871599b10ceb11"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "management-ns",
    "component": "enforcerd",
    "pr-id": "1250",
    "commit-sha": "8df510097794219da28831a5a3cd61170ddc7b34"
  },
  {
    "project": "management-ns",
    "component": "trireme-lib",
    "pr-id": "821",
    "commit-sha": "4e0234bc033b286d9e25f5d6ca871599b10ceb11"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "management-ns",
    "component": "enforcerd",
    "pr-id": "1250",
    "commit-sha": "8df510097794219da28831a5a3cd61170ddc7b34"
  },
  {
    "project": "management-ns",
    "component": "trireme-lib",
    "pr-id": "821",
    "commit-sha": "8566911fd562fbe0bbde9abb6c9aaacac75df81d"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "management-ns",
    "component": "enforcerd",
    "pr-id": "1250",
    "commit-sha": "19b4481592c0d1cb590a5c73138d981dbfb4c9ad"
  },
  {
    "project": "management-ns",
    "component": "trireme-lib",
    "pr-id": "821",
    "commit-sha": "8566911fd562fbe0bbde9abb6c9aaacac75df81d"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "management-ns",
    "component": "enforcerd",
    "pr-id": "1250",
    "commit-sha": "19b4481592c0d1cb590a5c73138d981dbfb4c9ad"
  },
  {
    "project": "management-ns",
    "component": "trireme-lib",
    "pr-id": "821",
    "commit-sha": "8566911fd562fbe0bbde9abb6c9aaacac75df81d"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "management-ns",
    "component": "enforcerd",
    "pr-id": "1250",
    "commit-sha": "b8955927a2200c1c6c408fd30372e384bca5000f"
  },
  {
    "project": "management-ns",
    "component": "trireme-lib",
    "pr-id": "821",
    "commit-sha": "8566911fd562fbe0bbde9abb6c9aaacac75df81d"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "management-ns",
    "component": "enforcerd",
    "pr-id": "1250",
    "commit-sha": "565a339c6d8d6809cb6c3588d3032dbe967edcc4"
  },
  {
    "project": "management-ns",
    "component": "trireme-lib",
    "pr-id": "821",
    "commit-sha": "2a942a324a598cd3685dd8505f0622c55291979d"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "management-ns",
    "component": "enforcerd",
    "pr-id": "1250",
    "commit-sha": "ec23ea44769553e4db72c206708829d5a0af5871"
  },
  {
    "project": "management-ns",
    "component": "trireme-lib",
    "pr-id": "821",
    "commit-sha": "2a942a324a598cd3685dd8505f0622c55291979d"
  },
  {
    "project": "management-ns",
    "component": "integrations-lib",
    "pr-id": "110",
    "commit-sha": "a59995a728b8e8bb8c5075bae6cc3258db36cf73"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "management-ns",
    "component": "enforcerd",
    "pr-id": "1250",
    "commit-sha": "3b6f74f1853d3590f72a64aa7d9127a9d0c4e5fd"
  },
  {
    "project": "management-ns",
    "component": "trireme-lib",
    "pr-id": "821",
    "commit-sha": "2a942a324a598cd3685dd8505f0622c55291979d"
  },
  {
    "project": "management-ns",
    "component": "integrations-lib",
    "pr-id": "110",
    "commit-sha": "a59995a728b8e8bb8c5075bae6cc3258db36cf73"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "management-ns",
    "component": "enforcerd",
    "pr-id": "1250",
    "commit-sha": "3b6f74f1853d3590f72a64aa7d9127a9d0c4e5fd"
  },
  {
    "project": "management-ns",
    "component": "trireme-lib",
    "pr-id": "821",
    "commit-sha": "2a942a324a598cd3685dd8505f0622c55291979d"
  },
  {
    "project": "management-ns",
    "component": "integrations-lib",
    "pr-id": "110",
    "commit-sha": "a59995a728b8e8bb8c5075bae6cc3258db36cf73"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "management-ns",
    "component": "trireme-lib",
    "pr-id": "821",
    "commit-sha": "2a942a324a598cd3685dd8505f0622c55291979d"
  },
  {
    "project": "management-ns",
    "component": "backend",
    "pr-id": "445",
    "commit-sha": "415c799e06779d681af870335dfc5e30ec6b9546"
  },
  {
    "project": "management-ns",
    "component": "enforcerd",
    "pr-id": "1250",
    "commit-sha": "3b6f74f1853d3590f72a64aa7d9127a9d0c4e5fd"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "management-ns",
    "component": "enforcerd",
    "pr-id": "1250",
    "commit-sha": "7e4b616b3d71aec8cc11258e1e1eaff76745f088"
  },
  {
    "project": "management-ns",
    "component": "trireme-lib",
    "pr-id": "821",
    "commit-sha": "2a942a324a598cd3685dd8505f0622c55291979d"
  },
  {
    "project": "management-ns",
    "component": "backend",
    "pr-id": "445",
    "commit-sha": "415c799e06779d681af870335dfc5e30ec6b9546"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "management-ns",
    "component": "enforcerd",
    "pr-id": "1250",
    "commit-sha": "71666f1e97b7cb0f8a2d8164360c2cf8278af961"
  },
  {
    "project": "management-ns",
    "component": "trireme-lib",
    "pr-id": "821",
    "commit-sha": "2a942a324a598cd3685dd8505f0622c55291979d"
  },
  {
    "project": "management-ns",
    "component": "backend",
    "pr-id": "445",
    "commit-sha": "415c799e06779d681af870335dfc5e30ec6b9546"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "management-ns",
    "component": "enforcerd",
    "pr-id": "1250",
    "commit-sha": "71666f1e97b7cb0f8a2d8164360c2cf8278af961"
  },
  {
    "project": "management-ns",
    "component": "trireme-lib",
    "pr-id": "821",
    "commit-sha": "2a942a324a598cd3685dd8505f0622c55291979d"
  },
  {
    "project": "management-ns",
    "component": "backend",
    "pr-id": "445",
    "commit-sha": "2eca90dd431c741606b907e21a0138e7f3a57e4d"
  }
]
```

**Review by dstiliadis — APPROVED** [review]

**Pull request merged**
