### PR TITLE
Enforcerd as sidecar container.

### PR DESCRIPTION
**Pull request by varks**
This is an initial PR to run enforcerd as a sidecar container. This introduces a new mode called Sidecar which creates a single PU for all the containers that share a network namespace as in a Kubernetes pod.

### CODE REVIEW

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "sidecar",
    "component": "enforcerd",
    "pr-id": "659",
    "commit-sha": "17f26f7e6d7dff50ab5a94ce80dc43653eff957e"
  },
  {
    "project": "sidecar",
    "component": "trireme-lib",
    "pr-id": "556",
    "commit-sha": "b73b34f05cf611970b78b8d388a89c1753d8e436"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "sidecar",
    "component": "trireme-lib",
    "pr-id": "556",
    "commit-sha": "b73b34f05cf611970b78b8d388a89c1753d8e436"
  },
  {
    "project": "sidecar",
    "component": "enforcerd",
    "pr-id": "659",
    "commit-sha": "17f26f7e6d7dff50ab5a94ce80dc43653eff957e"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "sidecar",
    "component": "enforcerd",
    "pr-id": "659",
    "commit-sha": "ac3f3dc2148ba5c5a11f3726166f5f665c765f41"
  },
  {
    "project": "sidecar",
    "component": "trireme-lib",
    "pr-id": "556",
    "commit-sha": "b73b34f05cf611970b78b8d388a89c1753d8e436"
  }
]
```

**Review by satyamsi — APPROVED** [review]

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "sidecar",
    "component": "enforcerd",
    "pr-id": "659",
    "commit-sha": "cce5f91485a040994c08b0566a78f65aa7ffb59d"
  },
  {
    "project": "sidecar",
    "component": "trireme-lib",
    "pr-id": "556",
    "commit-sha": "49ae3d22ff01bffc1d6e89bf3317612d627ef2b4"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "sidecar",
    "component": "enforcerd",
    "pr-id": "659",
    "commit-sha": "cce5f91485a040994c08b0566a78f65aa7ffb59d"
  },
  {
    "project": "sidecar",
    "component": "trireme-lib",
    "pr-id": "556",
    "commit-sha": "49ae3d22ff01bffc1d6e89bf3317612d627ef2b4"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "sidecar",
    "component": "enforcerd",
    "pr-id": "659",
    "commit-sha": "cce5f91485a040994c08b0566a78f65aa7ffb59d"
  },
  {
    "project": "sidecar",
    "component": "trireme-lib",
    "pr-id": "556",
    "commit-sha": "49ae3d22ff01bffc1d6e89bf3317612d627ef2b4"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "sidecar",
    "component": "enforcerd",
    "pr-id": "659",
    "commit-sha": "91f11b387930d5021272ae0e6d0472a0de08fc75"
  },
  {
    "project": "sidecar",
    "component": "trireme-lib",
    "pr-id": "556",
    "commit-sha": "49ae3d22ff01bffc1d6e89bf3317612d627ef2b4"
  }
]
```

**Review by satyamsi — APPROVED** [review]

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "sidecar",
    "component": "enforcerd",
    "pr-id": "659",
    "commit-sha": "80479a09885b114888cc0d2fa765a0a3d8df42b5"
  },
  {
    "project": "sidecar",
    "component": "trireme-lib",
    "pr-id": "556",
    "commit-sha": "49ae3d22ff01bffc1d6e89bf3317612d627ef2b4"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "sidecar",
    "component": "enforcerd",
    "pr-id": "659",
    "commit-sha": "6ea268b5fb8082829cab099d8a7877fc92028f56"
  },
  {
    "project": "sidecar",
    "component": "trireme-lib",
    "pr-id": "556",
    "commit-sha": "49ae3d22ff01bffc1d6e89bf3317612d627ef2b4"
  },
  {
    "project": "sidecar",
    "component": "concourse-pipelines",
    "pr-id": "537",
    "commit-sha": "62dfdc72f3dc9e55b01500788f76bda1ec9c073d"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "sidecar",
    "component": "trireme-lib",
    "pr-id": "556",
    "commit-sha": "49ae3d22ff01bffc1d6e89bf3317612d627ef2b4"
  },
  {
    "project": "sidecar",
    "component": "concourse-pipelines",
    "pr-id": "537",
    "commit-sha": "62dfdc72f3dc9e55b01500788f76bda1ec9c073d"
  },
  {
    "project": "sidecar",
    "component": "enforcerd",
    "pr-id": "659",
    "commit-sha": "dde9a27db3b95acc8d4f94de92ac7d43de17fd9c"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "sidecar",
    "component": "trireme-lib",
    "pr-id": "556",
    "commit-sha": "49ae3d22ff01bffc1d6e89bf3317612d627ef2b4"
  },
  {
    "project": "sidecar",
    "component": "concourse-pipelines",
    "pr-id": "537",
    "commit-sha": "62dfdc72f3dc9e55b01500788f76bda1ec9c073d"
  },
  {
    "project": "sidecar",
    "component": "enforcerd",
    "pr-id": "659",
    "commit-sha": "0b74a020059b83e1a2e2eaf2d95a446bfc7942e7"
  }
]
```

**Review by satyamsi — APPROVED** [review]

**Pull request merged**
