### PR TITLE
Fix the AMI install

### PR DESCRIPTION
**Pull request by dstiliadis**
Fix the AMI install by using the configurable cgroup path.

### CODE REVIEW

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1319",
    "commit-sha": "5a775f29e082b4ff4b4a4591cbce208a0c6488d9"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "848",
    "commit-sha": "4a2e2ad579402f0e3a711f5542de89926d4a8d07"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "848",
    "commit-sha": "68dc7721965f03e8e856976ebd7b2a84c9bc2961"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1319",
    "commit-sha": "5a775f29e082b4ff4b4a4591cbce208a0c6488d9"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1319",
    "commit-sha": "5a775f29e082b4ff4b4a4591cbce208a0c6488d9"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "848",
    "commit-sha": "a6c623c7da919766c9c17d66538a66828d042b9f"
  }
]
```

**Comment by amitlimaye** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1319",
    "commit-sha": "5a775f29e082b4ff4b4a4591cbce208a0c6488d9"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "848",
    "commit-sha": "9e04ed9998efd7d7563151c260744aebef5cd422"
  }
]
```

**Pull request merged**
