### PR TITLE
 Add “!” Operator to External Networks 3.14

### PR DESCRIPTION
**Pull request by philipatl**
Add “!” Operator to External Networks

### CODE REVIEW

**Comment by philipatl** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "extnet-not-3.14",
    "component": "enforcerd",
    "pr-id": "1979",
    "commit-sha": "659541fbad593e32e0a0d944c7487198bca6383c",
    "pipeline": "release-3.14.0"
  },
  {
    "project": "extnet-not-3.14",
    "component": "trireme-lib",
    "pr-id": "1036",
    "commit-sha": "53ddec81f7faf5841ea213fcf9394fb2bbbe19d7",
    "pipeline": "release-3.14.0"
  }
]
```

**Comment by philipatl** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "extnet-not-3.14",
    "component": "enforcerd",
    "pr-id": "1979",
    "commit-sha": "659541fbad593e32e0a0d944c7487198bca6383c",
    "pipeline": "release-3.14.0"
  },
  {
    "project": "extnet-not-3.14",
    "component": "trireme-lib",
    "pr-id": "1036",
    "commit-sha": "53ddec81f7faf5841ea213fcf9394fb2bbbe19d7",
    "pipeline": "release-3.14.0"
  },
  {
    "project": "extnet-not-3.14",
    "component": "gaia",
    "pr-id": "536",
    "commit-sha": "2246ee2aee5d0c2e10bddaf04e0d5902e9e36d57",
    "pipeline": "release-3.14.0"
  },
  {
    "project": "extnet-not-3.14",
    "component": "backend",
    "pr-id": "843",
    "commit-sha": "576ad99332ca314d8276ebcaff7781879ea544db",
    "pipeline": "release-3.14.0"
  }
]
```

**Comment by philipatl** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "extnet-not-3.14",
    "component": "backend",
    "pr-id": "843",
    "commit-sha": "576ad99332ca314d8276ebcaff7781879ea544db",
    "pipeline": "release-3.14.0"
  },
  {
    "project": "extnet-not-3.14",
    "component": "integrations-lib",
    "pr-id": "182",
    "commit-sha": "92e3c7aa29515c1bb33877d496c417dec317ab9b",
    "pipeline": "release-3.14.0"
  },
  {
    "project": "extnet-not-3.14",
    "component": "enforcerd",
    "pr-id": "1979",
    "commit-sha": "6928825bbe961576df4927d7f60589ec81f0c707",
    "pipeline": "release-3.14.0"
  },
  {
    "project": "extnet-not-3.14",
    "component": "trireme-lib",
    "pr-id": "1036",
    "commit-sha": "53ddec81f7faf5841ea213fcf9394fb2bbbe19d7",
    "pipeline": "release-3.14.0"
  },
  {
    "project": "extnet-not-3.14",
    "component": "gaia",
    "pr-id": "536",
    "commit-sha": "2246ee2aee5d0c2e10bddaf04e0d5902e9e36d57",
    "pipeline": "release-3.14.0"
  }
]
```

**Comment by itsai220** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "extnet-not-3.14",
    "component": "integrations-lib",
    "pr-id": "182",
    "commit-sha": "92e3c7aa29515c1bb33877d496c417dec317ab9b",
    "pipeline": "release-3.14.0"
  },
  {
    "project": "extnet-not-3.14",
    "component": "enforcerd",
    "pr-id": "1979",
    "commit-sha": "6928825bbe961576df4927d7f60589ec81f0c707",
    "pipeline": "release-3.14.0"
  },
  {
    "project": "extnet-not-3.14",
    "component": "trireme-lib",
    "pr-id": "1036",
    "commit-sha": "53ddec81f7faf5841ea213fcf9394fb2bbbe19d7",
    "pipeline": "release-3.14.0"
  },
  {
    "project": "extnet-not-3.14",
    "component": "gaia",
    "pr-id": "536",
    "commit-sha": "2246ee2aee5d0c2e10bddaf04e0d5902e9e36d57",
    "pipeline": "release-3.14.0"
  },
  {
    "project": "extnet-not-3.14",
    "component": "backend",
    "pr-id": "843",
    "commit-sha": "576ad99332ca314d8276ebcaff7781879ea544db",
    "pipeline": "release-3.14.0"
  }
]
```

**Review by brianonn — APPROVED** [review]
lgtm

**Review by tillery-aporeto — APPROVED** [review]

**Pull request merged**
