### PR TITLE
adding unit tests for dns

### PR DESCRIPTION
**Pull request by 0xmchadha**
#### Description
Unit tests for dns resolving feature. This test ensures that if an external network is created using FQDN then the appropriate calls are made. It also checks if the resolved IP is used to access the network then the packet is accepted.

### CODE REVIEW

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "597",
    "commit-sha": "1bb484218397a88d5372ae28109a3b4a3e852743"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "747",
    "commit-sha": "55b49db363da9715701ff914ee0734374b92661f"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "747",
    "commit-sha": "55b49db363da9715701ff914ee0734374b92661f"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "597",
    "commit-sha": "0398a991fc9d05b51c4fd60ea1f67aec35dcb367"
  }
]
```

**Review by varks — APPROVED** [review]

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "747",
    "commit-sha": "f3966d4d8f459f83241ea982e668f78e486ee13f"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "597",
    "commit-sha": "0398a991fc9d05b51c4fd60ea1f67aec35dcb367"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "747",
    "commit-sha": "0c10a9372c545bd829b17302cbadfdd51807ccb9"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "597",
    "commit-sha": "0398a991fc9d05b51c4fd60ea1f67aec35dcb367"
  }
]
```

**Review by dstiliadis — APPROVED** [review]

**Pull request merged**
