### PR TITLE
add proxy rules for uidpam pus

### PR DESCRIPTION
**Pull request by varks**
This PR adds proxy redirect rules for uid pam pus. It also fixes nat exclusion rules.

### CODE REVIEW

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "fix_proxy",
    "component": "enforcerd",
    "pr-id": "1011",
    "commit-sha": "c1a53a9dc50e04915dd322633e0e569ddc5be335"
  },
  {
    "project": "fix_proxy",
    "component": "trireme-lib",
    "pr-id": "749",
    "commit-sha": "ae01911323032c8812ab31beb75e81b57a123105"
  }
]
```

**Review by dstiliadis — CHANGES_REQUESTED** [review]
Please submit comments with pre/post PR changes in the iptables rules.

**Review by varks — COMMENTED** [review]
Proxy Nat rules before the change:

```
Chain RedirProxy-App (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     tcp  --  *      *       35.188.177.106       0.0.0.0/0            match-set dst-Proxy-ubun2zZ- dst,dst mark match ! 0x40 cgroup 101
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x40

Chain RedirProxy-Net (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     tcp  --  *      *       35.188.177.106       0.0.0.0/0            match-set srv-Proxy-ubun2zZ- dst mark match ! 0x40
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x40
```

Proxy Nat rules after the change. Notice the addition of uid rules and fixing the src and dst filter for nat exclusion rules.

```
Chain RedirProxy-App (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            35.188.177.106       match-set dst-Proxy-ubun2zZ- dst,dst mark match ! 0x40 cgroup 101
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x40
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set dst-Proxy-ubun2zZ- dst,dst mark match ! 0x40 owner UID match 1001 redir ports 21015

Chain RedirProxy-Net (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     tcp  --  *      *       35.188.177.106       0.0.0.0/0            match-set srv-Proxy-ubun2zZ- dst mark match ! 0x40
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x40
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set srv-Proxy-ubun2zZ- dst mark match ! 0x40 redir ports 21015
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "fix_proxy",
    "component": "enforcerd",
    "pr-id": "1011",
    "commit-sha": "e11494be8fd9da887e0670b6c78d7782b200d3da"
  },
  {
    "project": "fix_proxy",
    "component": "trireme-lib",
    "pr-id": "749",
    "commit-sha": "9c74431ad6417873b1aaa0791ef58d446a2a5278"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "fix_proxy",
    "component": "trireme-lib",
    "pr-id": "749",
    "commit-sha": "9939f98da577779e9a8952ea9508b1abbd673b76"
  },
  {
    "project": "fix_proxy",
    "component": "enforcerd",
    "pr-id": "1011",
    "commit-sha": "e11494be8fd9da887e0670b6c78d7782b200d3da"
  }
]
```

**Comment by varks** [comment]
Moving back to cgroup instead of uid owner
Pre:

```
Chain RedirProxy-App (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     tcp  --  *      *       35.188.177.106       0.0.0.0/0            match-set dst-Proxy-ubun2zZ- dst,dst mark match ! 0x40 cgroup 101
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x40

Chain RedirProxy-Net (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     tcp  --  *      *       35.188.177.106       0.0.0.0/0            match-set srv-Proxy-ubun2zZ- dst mark match ! 0x40
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x40
```

Post:
Notice the uid pu has a redirect.
```
Chain RedirProxy-App (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            35.188.177.106       match-set dst-Proxy-ubun2zZ- dst,dst mark match ! 0x40 cgroup 101
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x40
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set dst-Proxy-ubun2zZ- dst,dst mark match ! 0x40 cgroup 101 redir ports 21015

Chain RedirProxy-Net (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     tcp  --  *      *       35.188.177.106       0.0.0.0/0            match-set srv-Proxy-ubun2zZ- dst mark match ! 0x40
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x40
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set srv-Proxy-ubun2zZ- dst mark match ! 0x40 redir ports 21015
```

**Review by dstiliadis — DISMISSED** [review]

**Review by amitlimaye — DISMISSED** [review]

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "749",
    "commit-sha": "bfe61fa9bc374688ebc232558fa815e3914309b8"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "749",
    "commit-sha": "1a08780fb88d2115943743752a091b9f8401012d"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "fix_proxy",
    "component": "trireme-lib",
    "pr-id": "749",
    "commit-sha": "1a08780fb88d2115943743752a091b9f8401012d"
  },
  {
    "project": "fix_proxy",
    "component": "enforcerd",
    "pr-id": "1011",
    "commit-sha": "e11494be8fd9da887e0670b6c78d7782b200d3da"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "fix_proxy",
    "component": "trireme-lib",
    "pr-id": "749",
    "commit-sha": "49a4c342bdd01cde68d4acd3255908287804c471"
  },
  {
    "project": "fix_proxy",
    "component": "enforcerd",
    "pr-id": "1011",
    "commit-sha": "f578441da57b6471d7dc8aa1629a9ff4f42643a0"
  }
]
```

**Review by amitlimaye — APPROVED** [review]

**Pull request merged**
