### PR TITLE
Create static error objects and some refactoring

### PR DESCRIPTION
**Pull request by 0xmchadha**
1)  Create static objects for errors.
2)  Refactoring datapath code
3)  Add Debug messages

### CODE REVIEW

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "989",
    "commit-sha": "7b19915d139d54f23abbf08ea16f014c1effe3f6"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "717",
    "commit-sha": "ddbf9905681ff5d9de7bf329a52e32245530ad00"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "989",
    "commit-sha": "7b19915d139d54f23abbf08ea16f014c1effe3f6"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "717",
    "commit-sha": "ddbf9905681ff5d9de7bf329a52e32245530ad00"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "989",
    "commit-sha": "7b19915d139d54f23abbf08ea16f014c1effe3f6"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "717",
    "commit-sha": "e068b82fc6f2f112b49a35483c80e0564b3276f1"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "989",
    "commit-sha": "7b19915d139d54f23abbf08ea16f014c1effe3f6"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "717",
    "commit-sha": "e068b82fc6f2f112b49a35483c80e0564b3276f1"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "989",
    "commit-sha": "10b197b86758fdbf9af22b3c11c36e33a74c973b"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "717",
    "commit-sha": "aa3d6a28c9e28db99d35f17ae59654ec58e56c3e"
  }
]
```

**Review by dstiliadis — DISMISSED** [review]

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "989",
    "commit-sha": "70460a784cff9e8de19bc76ae1ad2831e71d6ff9"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "717",
    "commit-sha": "7ed7975c42e888e6dcf399476a3e33408e65f43b"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "989",
    "commit-sha": "70460a784cff9e8de19bc76ae1ad2831e71d6ff9"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "717",
    "commit-sha": "7ed7975c42e888e6dcf399476a3e33408e65f43b"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "989",
    "commit-sha": "70460a784cff9e8de19bc76ae1ad2831e71d6ff9"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "717",
    "commit-sha": "7ed7975c42e888e6dcf399476a3e33408e65f43b"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "989",
    "commit-sha": "70460a784cff9e8de19bc76ae1ad2831e71d6ff9"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "717",
    "commit-sha": "7ed7975c42e888e6dcf399476a3e33408e65f43b"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "989",
    "commit-sha": "70460a784cff9e8de19bc76ae1ad2831e71d6ff9"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "717",
    "commit-sha": "7ed7975c42e888e6dcf399476a3e33408e65f43b"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "989",
    "commit-sha": "32dd5960fdc44e247c1dd7277bd86db1d495c94d"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "717",
    "commit-sha": "7ed7975c42e888e6dcf399476a3e33408e65f43b"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "989",
    "commit-sha": "32dd5960fdc44e247c1dd7277bd86db1d495c94d"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "717",
    "commit-sha": "7ed7975c42e888e6dcf399476a3e33408e65f43b"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "994",
    "commit-sha": "cf09c20b6a0bbd97990d7e59d19002bd2a5275a4"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "717",
    "commit-sha": "7ed7975c42e888e6dcf399476a3e33408e65f43b"
  }
]
```

**Comment by 0xmchadha** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "994",
    "commit-sha": "cf09c20b6a0bbd97990d7e59d19002bd2a5275a4"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "717",
    "commit-sha": "083f2e870752a2a4dcee8400521d1dd37d33a35f"
  }
]
```

**Review by varks — APPROVED** [review]

**Pull request merged**
