### PR TITLE
new: error counters

### PR DESCRIPTION
**Pull request by sibicramesh**

### CODE REVIEW

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "custom-errors",
    "component": "enforcerd",
    "pr-id": "1592",
    "commit-sha": "e22b38dc7d1947aefa578732ce6e5e0c908cf6d8",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "trireme-lib",
    "pr-id": "975",
    "commit-sha": "d7ffe2efc9b36ea3693016538af442c7944af1cf",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "backend",
    "pr-id": "700",
    "commit-sha": "7b717121e5085a5d739f8f5847e16952c0ade884",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "gaia",
    "pr-id": "457",
    "commit-sha": "c3d0d5a0e8b4aebffeb4261d9032b9da249310b8",
    "pipeline": "master"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "custom-errors",
    "component": "enforcerd",
    "pr-id": "1592",
    "commit-sha": "e22b38dc7d1947aefa578732ce6e5e0c908cf6d8",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "trireme-lib",
    "pr-id": "975",
    "commit-sha": "1ecd874dc19182818821c316127048261f9784bf",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "backend",
    "pr-id": "700",
    "commit-sha": "7b717121e5085a5d739f8f5847e16952c0ade884",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "gaia",
    "pr-id": "457",
    "commit-sha": "c3d0d5a0e8b4aebffeb4261d9032b9da249310b8",
    "pipeline": "master"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "custom-errors",
    "component": "enforcerd",
    "pr-id": "1592",
    "commit-sha": "71872b2303d4c9cc361019903f23235548fe4650",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "trireme-lib",
    "pr-id": "975",
    "commit-sha": "2401837f706b66097b710dd1b88299f63aa8e04f",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "backend",
    "pr-id": "700",
    "commit-sha": "ee15cf82f4aca81cb9da207796d1d66af65ad6ca",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "gaia",
    "pr-id": "457",
    "commit-sha": "9bee8206c3981ace03ca69a6cc9777d5cb3ef7a9",
    "pipeline": "master"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "custom-errors",
    "component": "enforcerd",
    "pr-id": "1592",
    "commit-sha": "71872b2303d4c9cc361019903f23235548fe4650",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "trireme-lib",
    "pr-id": "975",
    "commit-sha": "207e3dfd6ab50588231b27e0cd0c3c3e4be4c2b8",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "backend",
    "pr-id": "700",
    "commit-sha": "efd3d60755be0a1d561de7f471dc98ee5feaa11c",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "gaia",
    "pr-id": "457",
    "commit-sha": "9bee8206c3981ace03ca69a6cc9777d5cb3ef7a9",
    "pipeline": "master"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "custom-errors",
    "component": "backend",
    "pr-id": "700",
    "commit-sha": "91732a8bea381b65b9d73482e2880cc182a66ff8",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "gaia",
    "pr-id": "457",
    "commit-sha": "9bee8206c3981ace03ca69a6cc9777d5cb3ef7a9",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "enforcerd",
    "pr-id": "1592",
    "commit-sha": "a37a45ee739098cf177a615bf57aa6c58bc9ef13",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "trireme-lib",
    "pr-id": "975",
    "commit-sha": "f2662cfe315eda227334caf35fb74ca719f010ed",
    "pipeline": "master"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "custom-errors",
    "component": "trireme-lib",
    "pr-id": "975",
    "commit-sha": "13982625b36d40ee43a8d44d3f9a659cc809e42b",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "backend",
    "pr-id": "700",
    "commit-sha": "91732a8bea381b65b9d73482e2880cc182a66ff8",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "gaia",
    "pr-id": "457",
    "commit-sha": "9bee8206c3981ace03ca69a6cc9777d5cb3ef7a9",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "enforcerd",
    "pr-id": "1592",
    "commit-sha": "cf33ee9643c4bf438eaebd36231d3e602e7cc942",
    "pipeline": "master"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "custom-errors",
    "component": "gaia",
    "pr-id": "457",
    "commit-sha": "9bee8206c3981ace03ca69a6cc9777d5cb3ef7a9",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "enforcerd",
    "pr-id": "1592",
    "commit-sha": "8cee6f014d8f52e8d5fa576162827b76eb4d49c1",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "trireme-lib",
    "pr-id": "975",
    "commit-sha": "1f9a80f98d5fd501eda639b133f500cb2ccdfac2",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "backend",
    "pr-id": "700",
    "commit-sha": "91732a8bea381b65b9d73482e2880cc182a66ff8",
    "pipeline": "master"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "custom-errors",
    "component": "enforcerd",
    "pr-id": "1592",
    "commit-sha": "8cee6f014d8f52e8d5fa576162827b76eb4d49c1",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "trireme-lib",
    "pr-id": "975",
    "commit-sha": "e12bcab6228c47a95ead52ea9bf01ac94ce13c73",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "backend",
    "pr-id": "700",
    "commit-sha": "91732a8bea381b65b9d73482e2880cc182a66ff8",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "gaia",
    "pr-id": "457",
    "commit-sha": "9bee8206c3981ace03ca69a6cc9777d5cb3ef7a9",
    "pipeline": "master"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "custom-errors",
    "component": "enforcerd",
    "pr-id": "1592",
    "commit-sha": "8cee6f014d8f52e8d5fa576162827b76eb4d49c1",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "trireme-lib",
    "pr-id": "975",
    "commit-sha": "63a9941546224d3653f6a380b1fb5283f443962f",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "backend",
    "pr-id": "700",
    "commit-sha": "91732a8bea381b65b9d73482e2880cc182a66ff8",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "gaia",
    "pr-id": "457",
    "commit-sha": "9bee8206c3981ace03ca69a6cc9777d5cb3ef7a9",
    "pipeline": "master"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "custom-errors",
    "component": "enforcerd",
    "pr-id": "1592",
    "commit-sha": "5e87aad5c1c54c9a7aef6d8f0d66e647d6fc2479",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "trireme-lib",
    "pr-id": "975",
    "commit-sha": "49f8ab91a8564efc3714ef9ac37eb1873ea6ae9a",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "backend",
    "pr-id": "700",
    "commit-sha": "91732a8bea381b65b9d73482e2880cc182a66ff8",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "gaia",
    "pr-id": "457",
    "commit-sha": "9bee8206c3981ace03ca69a6cc9777d5cb3ef7a9",
    "pipeline": "master"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "custom-errors",
    "component": "gaia",
    "pr-id": "457",
    "commit-sha": "aff5d87fc08f6e0b7d355d53f18a8bd584794720",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "enforcerd",
    "pr-id": "1592",
    "commit-sha": "c411fac42befe8f593cdfdabff4b28d96b71de43",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "trireme-lib",
    "pr-id": "975",
    "commit-sha": "49f8ab91a8564efc3714ef9ac37eb1873ea6ae9a",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "backend",
    "pr-id": "700",
    "commit-sha": "0988935aeef65d03e343d35985eb35a622fa2935",
    "pipeline": "master"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "custom-errors",
    "component": "enforcerd",
    "pr-id": "1592",
    "commit-sha": "c411fac42befe8f593cdfdabff4b28d96b71de43",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "trireme-lib",
    "pr-id": "975",
    "commit-sha": "1912aa35f5f27715d2502c14781ac6b556b43f10",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "backend",
    "pr-id": "700",
    "commit-sha": "b59346b9f64f4be74117fb002cba3f6e52c1a7a8",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "gaia",
    "pr-id": "457",
    "commit-sha": "fc6c8acdfd18bfd33dfe6eae1429c4aac5df8ca5",
    "pipeline": "master"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "custom-errors",
    "component": "enforcerd",
    "pr-id": "1592",
    "commit-sha": "5f7f263b856f5287c2c46509d04a4c1d34ce9833",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "trireme-lib",
    "pr-id": "975",
    "commit-sha": "d0b881fc82b37284675b40d1d3be6cf4b4372010",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "backend",
    "pr-id": "700",
    "commit-sha": "7a7c01e73321e448c2d9442209a0a1cf7ba3ef81",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "gaia",
    "pr-id": "457",
    "commit-sha": "c01027802d137763d5fd134073fc7e1d11c31014",
    "pipeline": "master"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "custom-errors",
    "component": "trireme-lib",
    "pr-id": "975",
    "commit-sha": "81098e3de094dc41e586294bc5ae264c0f8febb5",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "backend",
    "pr-id": "700",
    "commit-sha": "918f5298b558586a27430e9c81fb4523eed3494a",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "gaia",
    "pr-id": "457",
    "commit-sha": "4db31ec297d2424e8c2d95a4ab7126480bbbd7d2",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "enforcerd",
    "pr-id": "1592",
    "commit-sha": "d2722efe39f9fd8f2b5fdfa8b21c4c54874ce180",
    "pipeline": "master"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "custom-errors",
    "component": "enforcerd",
    "pr-id": "1592",
    "commit-sha": "4e59b2ff7da258f6bca14097607e1d34b03f92cc",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "trireme-lib",
    "pr-id": "975",
    "commit-sha": "3ec38158c0eb5e58fd2e4b726a9fb76d232f1e5c",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "backend",
    "pr-id": "700",
    "commit-sha": "918f5298b558586a27430e9c81fb4523eed3494a",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "gaia",
    "pr-id": "457",
    "commit-sha": "4db31ec297d2424e8c2d95a4ab7126480bbbd7d2",
    "pipeline": "master"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "custom-errors",
    "component": "trireme-lib",
    "pr-id": "975",
    "commit-sha": "d7ac015c80ea3f9558dd4f1d77fae4fa77760628",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "backend",
    "pr-id": "700",
    "commit-sha": "918f5298b558586a27430e9c81fb4523eed3494a",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "gaia",
    "pr-id": "457",
    "commit-sha": "4db31ec297d2424e8c2d95a4ab7126480bbbd7d2",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "enforcerd",
    "pr-id": "1592",
    "commit-sha": "3c0e0b0a03e33a66ee7f322cb4c77f51cfd9a1fa",
    "pipeline": "master"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "custom-errors",
    "component": "enforcerd",
    "pr-id": "1592",
    "commit-sha": "e081db585135a788827aba88519ae9c51ffc905a",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "trireme-lib",
    "pr-id": "975",
    "commit-sha": "d7ac015c80ea3f9558dd4f1d77fae4fa77760628",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "backend",
    "pr-id": "700",
    "commit-sha": "918f5298b558586a27430e9c81fb4523eed3494a",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "gaia",
    "pr-id": "457",
    "commit-sha": "4db31ec297d2424e8c2d95a4ab7126480bbbd7d2",
    "pipeline": "master"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "custom-errors",
    "component": "trireme-lib",
    "pr-id": "975",
    "commit-sha": "d7ac015c80ea3f9558dd4f1d77fae4fa77760628",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "backend",
    "pr-id": "700",
    "commit-sha": "918f5298b558586a27430e9c81fb4523eed3494a",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "gaia",
    "pr-id": "457",
    "commit-sha": "4db31ec297d2424e8c2d95a4ab7126480bbbd7d2",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "enforcerd",
    "pr-id": "1592",
    "commit-sha": "3221883537825192eba83219da7fd151b39e6dca",
    "pipeline": "master"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "custom-errors",
    "component": "enforcerd",
    "pr-id": "1592",
    "commit-sha": "1a7813f9bc5ae3f5d44235995f89de5f1bf4d1f2",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "trireme-lib",
    "pr-id": "975",
    "commit-sha": "d7ac015c80ea3f9558dd4f1d77fae4fa77760628",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "backend",
    "pr-id": "700",
    "commit-sha": "918f5298b558586a27430e9c81fb4523eed3494a",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "gaia",
    "pr-id": "457",
    "commit-sha": "4db31ec297d2424e8c2d95a4ab7126480bbbd7d2",
    "pipeline": "master"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "custom-errors",
    "component": "backend",
    "pr-id": "700",
    "commit-sha": "918f5298b558586a27430e9c81fb4523eed3494a",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "gaia",
    "pr-id": "457",
    "commit-sha": "4db31ec297d2424e8c2d95a4ab7126480bbbd7d2",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "enforcerd",
    "pr-id": "1592",
    "commit-sha": "334ac3e79a163768c72f3e74c1f13ee403542a9c",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "trireme-lib",
    "pr-id": "975",
    "commit-sha": "d7ac015c80ea3f9558dd4f1d77fae4fa77760628",
    "pipeline": "master"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "custom-errors",
    "component": "trireme-lib",
    "pr-id": "975",
    "commit-sha": "d7ac015c80ea3f9558dd4f1d77fae4fa77760628",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "backend",
    "pr-id": "700",
    "commit-sha": "918f5298b558586a27430e9c81fb4523eed3494a",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "gaia",
    "pr-id": "457",
    "commit-sha": "4db31ec297d2424e8c2d95a4ab7126480bbbd7d2",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "enforcerd",
    "pr-id": "1592",
    "commit-sha": "923a0d35bf3bfe795f712d3a9114e76c3446be15",
    "pipeline": "master"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "custom-errors",
    "component": "enforcerd",
    "pr-id": "1592",
    "commit-sha": "74d8d32dffc5f46ce53aa491030977572658f4ab",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "trireme-lib",
    "pr-id": "975",
    "commit-sha": "360ec4117de2041533236d642234c286c5afbb83",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "backend",
    "pr-id": "700",
    "commit-sha": "973f563cc1e530d7ad855b670131273839bc3f16",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "gaia",
    "pr-id": "457",
    "commit-sha": "4db31ec297d2424e8c2d95a4ab7126480bbbd7d2",
    "pipeline": "master"
  }
]
```

**Review by amitlimaye — DISMISSED** [review]

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "custom-errors",
    "component": "backend",
    "pr-id": "700",
    "commit-sha": "973f563cc1e530d7ad855b670131273839bc3f16",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "gaia",
    "pr-id": "457",
    "commit-sha": "4db31ec297d2424e8c2d95a4ab7126480bbbd7d2",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "enforcerd",
    "pr-id": "1592",
    "commit-sha": "69b320d8f061ceaf5b1e708453715d0f8e44e7a7",
    "pipeline": "master"
  },
  {
    "project": "custom-errors",
    "component": "trireme-lib",
    "pr-id": "975",
    "commit-sha": "984a49c9029e31127e795bafe4a416096780f64f",
    "pipeline": "master"
  }
]
```

**Review by amitlimaye — APPROVED** [review]

**Pull request merged**
