### PR TITLE
Cleanup is enforcerd was killed using -9.

### PR DESCRIPTION
**Pull request by amitlimaye**
#### Description
*Changes proposed in this pull request.*

#### Test plan
*Outline the test plan used to test this change before merging it.*

> Fixes #.

### CODE REVIEW

**Comment by primalmotion** [comment]
what's the status on this one? If outdated, can someone close it?

**Comment by satyamsi** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
[
  {
    "component": "enforcerd",
    "pr-id": "389",
    "commit-sha": "47370eb979f57ef23c84bddb3ed0ca1150bfe27b"
  },
  {
    "component": "trireme-lib",
    "pr-id": "391",
    "commit-sha": "d820c1fc7879edaebc3a95b5168c23720f2adb79"
  }
]

**Comment by satyamsi** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
[
  {
    "component": "enforcerd",
    "pr-id": "389",
    "commit-sha": "47370eb979f57ef23c84bddb3ed0ca1150bfe27b"
  },
  {
    "component": "trireme-lib",
    "pr-id": "391",
    "commit-sha": "d820c1fc7879edaebc3a95b5168c23720f2adb79"
  }
]

**Comment by satyamsi** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
[
  {
    "component": "enforcerd",
    "pr-id": "389",
    "commit-sha": "47370eb979f57ef23c84bddb3ed0ca1150bfe27b"
  },
  {
    "component": "trireme-lib",
    "pr-id": "391",
    "commit-sha": "d820c1fc7879edaebc3a95b5168c23720f2adb79"
  }
]

**Comment by satyamsi** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
[
  {
    "component": "enforcerd",
    "pr-id": "389",
    "commit-sha": "47370eb979f57ef23c84bddb3ed0ca1150bfe27b"
  },
  {
    "component": "trireme-lib",
    "pr-id": "391",
    "commit-sha": "d820c1fc7879edaebc3a95b5168c23720f2adb79"
  }
]

**Comment by satyamsi** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
[
  {
    "component": "enforcerd",
    "pr-id": "389",
    "commit-sha": "47370eb979f57ef23c84bddb3ed0ca1150bfe27b"
  },
  {
    "component": "trireme-lib",
    "pr-id": "391",
    "commit-sha": "d820c1fc7879edaebc3a95b5168c23720f2adb79"
  }
]

**Comment by satyamsi** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
[
  {
    "component": "enforcerd",
    "pr-id": "389",
    "commit-sha": "47370eb979f57ef23c84bddb3ed0ca1150bfe27b"
  },
  {
    "component": "trireme-lib",
    "pr-id": "391",
    "commit-sha": "d820c1fc7879edaebc3a95b5168c23720f2adb79"
  }
]

**Comment by dstiliadis** [comment]
This needs to be moved forward. It is still needed.

**Pull request closed without merging**
