### PR TITLE
Use configured proxy port for containers.

### PR DESCRIPTION
**Pull request by varks**

### CODE REVIEW

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "661",
    "commit-sha": "9445d2185cd58665d60cc6a4c175a3bf1f38b3d4"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "661",
    "commit-sha": "9445d2185cd58665d60cc6a4c175a3bf1f38b3d4"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "661",
    "commit-sha": "9445d2185cd58665d60cc6a4c175a3bf1f38b3d4"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "661",
    "commit-sha": "a96c8546865f5fac1eebc3efc05f256105a25afb"
  }
]
```

**Review by dstiliadis — APPROVED** [review]

**Pull request merged**
