### PR TITLE
RingBuffer Check

### PR DESCRIPTION
**Pull request by sibicramesh**
--> nfqueue with ringbuffer update
--> skip travis check until merging "Ring Buffer Update Returns" to master in netlink-go
--> netlink-go - https://github.com/aporeto-inc/netlink-go/pull/25

### CODE REVIEW

**Review by dstiliadis — COMMENTED** [review]
Why do we need that? It doesn't make sense to introduce a return that always returns true.

**Comment by satyamsi** [comment]
retest this please

**Comment by satyamsi** [comment]
retest this please 2

**Comment by primalmotion** [comment]
what's the status on this one? If outdated, can someone close it?

**Pull request closed without merging**
