### PR TITLE
Fixes reporting of flows 

### PR DESCRIPTION
**Pull request by dstiliadis**
Fixes the reporting of flow information when user information is also included.

Specifically: 

1. If user authorization information is available in the API request, then the source of the request is the user. There is one exception to this to avoid denial of service attacks, where if there is an explicit drop from an ACL rule, we just report the IP and exit. We don't parse user info that can be expensive. 

2. If user authorization is not available, we report as source the PU. 

3. If a PU is not available as well, we report it as an external service.

### CODE REVIEW

**Review by varks — APPROVED** [review]
lgtm.

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "component": "enforcerd",
    "pr-id": "595",
    "commit-sha": "1fde770efed092f6cbd975a2aefbb09f892ee9f1"
  },
  {
    "component": "trireme-lib",
    "pr-id": "548",
    "commit-sha": "54b31c04cd2462493ad020c5c465a301adfd91a2"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "component": "enforcerd",
    "pr-id": "595",
    "commit-sha": "1fde770efed092f6cbd975a2aefbb09f892ee9f1"
  },
  {
    "component": "trireme-lib",
    "pr-id": "548",
    "commit-sha": "2fd8406a232396ec727365fa474fc074da33b9b9"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "component": "apotests",
    "pr-id": "1552",
    "commit-sha": "7a4f76ee91c0f9a351ef0b934505d2df3f447e5b"
  },
  {
    "component": "trireme-lib",
    "pr-id": "548",
    "commit-sha": "2fd8406a232396ec727365fa474fc074da33b9b9"
  },
  {
    "component": "gaia",
    "pr-id": "162",
    "commit-sha": "ad8ac5776f8b0da2e28cfcc75ab333de1259cfca"
  },
  {
    "component": "backend",
    "pr-id": "10",
    "commit-sha": "07da807aa0a0eb74e722e6e8ee3a4a545672963c"
  },
  {
    "component": "enforcerd",
    "pr-id": "595",
    "commit-sha": "1fde770efed092f6cbd975a2aefbb09f892ee9f1"
  },
  {
    "component": "apoctl",
    "pr-id": "123",
    "commit-sha": "4ad6543b783be5e711a2895f4a01085fd1d6d2ca"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "component": "apoctl",
    "pr-id": "123",
    "commit-sha": "4ad6543b783be5e711a2895f4a01085fd1d6d2ca"
  },
  {
    "component": "apotests",
    "pr-id": "1552",
    "commit-sha": "7a4f76ee91c0f9a351ef0b934505d2df3f447e5b"
  },
  {
    "component": "trireme-lib",
    "pr-id": "548",
    "commit-sha": "2fd8406a232396ec727365fa474fc074da33b9b9"
  },
  {
    "component": "gaia",
    "pr-id": "162",
    "commit-sha": "ad8ac5776f8b0da2e28cfcc75ab333de1259cfca"
  },
  {
    "component": "backend",
    "pr-id": "10",
    "commit-sha": "07da807aa0a0eb74e722e6e8ee3a4a545672963c"
  },
  {
    "component": "enforcerd",
    "pr-id": "595",
    "commit-sha": "3219af823c5b668181b77d8146b77e374e7e80a6"
  }
]
```

**Pull request merged**
