### PR TITLE
Fix the kubernetes logging issue. (#860)

### PR DESCRIPTION
**Pull request by amitlimaye**
* Fix the kubernetes logging issue.

* Remove unwanted files.

* Add disable logging var.

* Minor Changes.

Change the name of the var.

* Add comment.

* Remove print.

#### Description
*Changes proposed in this pull request.*

#### Test plan
*Outline the test plan used to test this change before merging it.*

> Fixes #.

### CODE REVIEW

**Comment by amitlimaye** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1360",
    "commit-sha": "9d499fd6b564eeb1d27e2c0709a02121930c08f3"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "862",
    "commit-sha": "f9f25b282c9fe1b5df1b9009c09c01d60385f436"
  }
]
```

**Comment by abhijitherekar** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "K8s_logging_fix",
    "component": "apotests",
    "pr-id": "2236",
    "commit-sha": "59df9a0307fda03dc5e79e3a8dd8f1c749d5ee37"
  },
  {
    "project": "K8s_logging_fix",
    "component": "apotests-lib",
    "pr-id": "200",
    "commit-sha": "85678b37316893110442b712d501da3c2b00bbfa"
  },
  {
    "project": "K8s_logging_fix",
    "component": "enforcerd",
    "pr-id": "1360",
    "commit-sha": "628708907c1e981d6d692f5ec3f247630af081a3"
  },
  {
    "project": "K8s_logging_fix",
    "component": "trireme-lib",
    "pr-id": "862",
    "commit-sha": "f9f25b282c9fe1b5df1b9009c09c01d60385f436"
  }
]
```

**Comment by abhijitherekar** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "K8s_logging_fix",
    "component": "apotests",
    "pr-id": "2236",
    "commit-sha": "59df9a0307fda03dc5e79e3a8dd8f1c749d5ee37"
  },
  {
    "project": "K8s_logging_fix",
    "component": "apotests-lib",
    "pr-id": "200",
    "commit-sha": "85678b37316893110442b712d501da3c2b00bbfa"
  },
  {
    "project": "K8s_logging_fix",
    "component": "enforcerd",
    "pr-id": "1360",
    "commit-sha": "628708907c1e981d6d692f5ec3f247630af081a3"
  },
  {
    "project": "K8s_logging_fix",
    "component": "trireme-lib",
    "pr-id": "862",
    "commit-sha": "f9f25b282c9fe1b5df1b9009c09c01d60385f436"
  }
]
```

**Comment by abhijitherekar** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "K8s_logging_fix",
    "component": "apotests",
    "pr-id": "2236",
    "commit-sha": "59df9a0307fda03dc5e79e3a8dd8f1c749d5ee37"
  },
  {
    "project": "K8s_logging_fix",
    "component": "apotests-lib",
    "pr-id": "202",
    "commit-sha": "7acf5280dfaea4c5e71b54e91448226ae417fb26"
  },
  {
    "project": "K8s_logging_fix",
    "component": "enforcerd",
    "pr-id": "1360",
    "commit-sha": "628708907c1e981d6d692f5ec3f247630af081a3"
  },
  {
    "project": "K8s_logging_fix",
    "component": "trireme-lib",
    "pr-id": "862",
    "commit-sha": "f9f25b282c9fe1b5df1b9009c09c01d60385f436"
  }
]
```

**Comment by abhijitherekar** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "K8s_logging_fix",
    "component": "apotests-lib",
    "pr-id": "202",
    "commit-sha": "7acf5280dfaea4c5e71b54e91448226ae417fb26"
  },
  {
    "project": "K8s_logging_fix",
    "component": "enforcerd",
    "pr-id": "1360",
    "commit-sha": "628708907c1e981d6d692f5ec3f247630af081a3"
  },
  {
    "project": "K8s_logging_fix",
    "component": "trireme-lib",
    "pr-id": "862",
    "commit-sha": "f9f25b282c9fe1b5df1b9009c09c01d60385f436"
  },
  {
    "project": "K8s_logging_fix",
    "component": "apotests",
    "pr-id": "2237",
    "commit-sha": "f0c3c5cd848e75ef850a84967c26e1876c5b487b"
  }
]
```

**Comment by sooryamanian91** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "K8s_logging_fix",
    "component": "apotests-lib",
    "pr-id": "202",
    "commit-sha": "e9e36f25c29c63f59521799dbdf7fca57393081f"
  },
  {
    "project": "K8s_logging_fix",
    "component": "enforcerd",
    "pr-id": "1360",
    "commit-sha": "628708907c1e981d6d692f5ec3f247630af081a3"
  },
  {
    "project": "K8s_logging_fix",
    "component": "trireme-lib",
    "pr-id": "862",
    "commit-sha": "f9f25b282c9fe1b5df1b9009c09c01d60385f436"
  },
  {
    "project": "K8s_logging_fix",
    "component": "apotests",
    "pr-id": "2237",
    "commit-sha": "c2b2a0fe3958943e270151e38f26af5bef8822a8"
  }
]
```

**Comment by sooryamanian91** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "K8s_logging_fix",
    "component": "enforcerd",
    "pr-id": "1360",
    "commit-sha": "628708907c1e981d6d692f5ec3f247630af081a3"
  },
  {
    "project": "K8s_logging_fix",
    "component": "trireme-lib",
    "pr-id": "862",
    "commit-sha": "f9f25b282c9fe1b5df1b9009c09c01d60385f436"
  },
  {
    "project": "K8s_logging_fix",
    "component": "apotests",
    "pr-id": "2237",
    "commit-sha": "d0624e1d8a39380f2942705afa2189723450949f"
  },
  {
    "project": "K8s_logging_fix",
    "component": "apotests-lib",
    "pr-id": "202",
    "commit-sha": "015b3cb250dda9f9e9b381016eaefa24a1cb6834"
  }
]
```

**Comment by abhijitherekar** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "K8s_logging_fix",
    "component": "enforcerd",
    "pr-id": "1360",
    "commit-sha": "99a43e864fe75f39f115e60baf954189facf4af8"
  },
  {
    "project": "K8s_logging_fix",
    "component": "trireme-lib",
    "pr-id": "862",
    "commit-sha": "f9f25b282c9fe1b5df1b9009c09c01d60385f436"
  },
  {
    "project": "K8s_logging_fix",
    "component": "apotests",
    "pr-id": "2237",
    "commit-sha": "d0624e1d8a39380f2942705afa2189723450949f"
  },
  {
    "project": "K8s_logging_fix",
    "component": "apotests-lib",
    "pr-id": "202",
    "commit-sha": "015b3cb250dda9f9e9b381016eaefa24a1cb6834"
  }
]
```

**Comment by abhijitherekar** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "K8s_logging_fix",
    "component": "apotests-lib",
    "pr-id": "202",
    "commit-sha": "015b3cb250dda9f9e9b381016eaefa24a1cb6834"
  },
  {
    "project": "K8s_logging_fix",
    "component": "enforcerd",
    "pr-id": "1360",
    "commit-sha": "99a43e864fe75f39f115e60baf954189facf4af8"
  },
  {
    "project": "K8s_logging_fix",
    "component": "trireme-lib",
    "pr-id": "862",
    "commit-sha": "f9f25b282c9fe1b5df1b9009c09c01d60385f436"
  },
  {
    "project": "K8s_logging_fix",
    "component": "apotests",
    "pr-id": "2239",
    "commit-sha": "68e9d64d8e12cec0f614a7ee0f24dac1ce391202"
  }
]
```

**Comment by priteshchandaliya** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "K8s_logging_fix",
    "component": "enforcerd",
    "pr-id": "1360",
    "commit-sha": "99a43e864fe75f39f115e60baf954189facf4af8"
  },
  {
    "project": "K8s_logging_fix",
    "component": "trireme-lib",
    "pr-id": "862",
    "commit-sha": "f9f25b282c9fe1b5df1b9009c09c01d60385f436"
  },
  {
    "project": "K8s_logging_fix",
    "component": "apotests",
    "pr-id": "2239",
    "commit-sha": "b81051806c8d75d4032b45e360b55bf9d9f953f4"
  },
  {
    "project": "K8s_logging_fix",
    "component": "apotests-lib",
    "pr-id": "202",
    "commit-sha": "015b3cb250dda9f9e9b381016eaefa24a1cb6834"
  }
]
```

**Comment by priteshchandaliya** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "K8s_logging_fix",
    "component": "enforcerd",
    "pr-id": "1360",
    "commit-sha": "99a43e864fe75f39f115e60baf954189facf4af8"
  },
  {
    "project": "K8s_logging_fix",
    "component": "trireme-lib",
    "pr-id": "862",
    "commit-sha": "f9f25b282c9fe1b5df1b9009c09c01d60385f436"
  },
  {
    "project": "K8s_logging_fix",
    "component": "apotests",
    "pr-id": "2239",
    "commit-sha": "b81051806c8d75d4032b45e360b55bf9d9f953f4"
  },
  {
    "project": "K8s_logging_fix",
    "component": "apotests-lib",
    "pr-id": "202",
    "commit-sha": "f235c9a36b8ef5cadd084f28842762af86d89ebf"
  }
]
```

**Pull request merged**
