### PR TITLE
Refactor acls with go templates

### PR DESCRIPTION
**Pull request by varks**
The following improvements are included:

1. PUType is simplified and is used in all objects. No multiple values allowed in the extensions.

2. The ACLs are based on templates, and there is a framework for unit testing where the ACLs go into a buffer and the only thing the test does is compare the buffer with the expected state. There are mocks for both the ACLs and the ipsets. 

3. We now support process to process for the same user that was not supported before.

4. The structure has changed where we only touch the main iptables by inserting one rule in INPUT/OUTPUT chains and then jumping in our chains. Others can update the main tables.

5. All objects (acls, ipsets ) strat with the TRI- prefix.

6. UDP traffic is only captured for target UDP networks (since these are also programmed as ipsets and not processed in user space at all)

7. The model for UDP is a little different from TCP since we do not have auto-detection. If you have an ACL (external network rule) that allows traffic towards a network, it will be allowed even if this matches the UDP target networks. So, we will not be messing with DNS traffic etc.

8. Error handling has been cleaned up to make sure there is no residual state in case of error.

The structure of the main tables looks like below:

```
Chain PREROUTING (policy ACCEPT 652 packets, 83939 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain INPUT (policy ACCEPT 600 packets, 81103 bytes)
 pkts bytes target     prot opt in     out     source               destination
 1804  391K NETWORK-SERVICE  all  --  *      *       0.0.0.0/0            0.0.0.0/0
  399 64375 TRI-Net    all  --  *      *       0.0.0.0/0            0.0.0.0/0            ! match-set TRI-Excluded src

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 488 packets, 68690 bytes)
 pkts bytes target     prot opt in     out     source               destination
 1543  349K APP-SERVICE  all  --  *      *       0.0.0.0/0            0.0.0.0/0
  262 36742 TRI-App    all  --  *      *       0.0.0.0/0            0.0.0.0/0            ! match-set TRI-Excluded dst

Chain POSTROUTING (policy ACCEPT 521 packets, 71470 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain APP-SERVICE (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 NFQUEUE    udp  --  *      *       0.0.0.0/0            0.0.0.0/0            connmark match  0xf003 mark match ! 0x40000062 NFQUEUE num 15
    0     0 NFQUEUE    tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            connmark match  0xf003 tcp flags:!0x02/0x02 NFQUEUE num 15
    0     0 NFQUEUE    udp  --  *      *       0.0.0.0/0            0.0.0.0/0            connmark match  0xf002 mark match ! 0x40000062 NFQUEUE num 14
    0     0 NFQUEUE    tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            connmark match  0xf002 tcp flags:!0x02/0x02 NFQUEUE num 14
    0     0 NFQUEUE    udp  --  *      *       0.0.0.0/0            0.0.0.0/0            connmark match  0xf001 mark match ! 0x40000062 NFQUEUE num 13
    0     0 NFQUEUE    tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            connmark match  0xf001 tcp flags:!0x02/0x02 NFQUEUE num 13
    0     0 NFQUEUE    udp  --  *      *       0.0.0.0/0            0.0.0.0/0            connmark match  0xf000 mark match ! 0x40000062 NFQUEUE num 12
    0     0 NFQUEUE    tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            connmark match  0xf000 tcp flags:!0x02/0x02 NFQUEUE num 12

Chain NETWORK-SERVICE (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 NFQUEUE    udp  --  *      *       0.0.0.0/0            0.0.0.0/0            connmark match  0xf003 NFQUEUE num 31
    0     0 NFQUEUE    tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            connmark match  0xf003 tcp flags:!0x02/0x02 NFQUEUE num 31
    0     0 NFQUEUE    udp  --  *      *       0.0.0.0/0            0.0.0.0/0            connmark match  0xf002 NFQUEUE num 30
    0     0 NFQUEUE    tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            connmark match  0xf002 tcp flags:!0x02/0x02 NFQUEUE num 30
    0     0 NFQUEUE    udp  --  *      *       0.0.0.0/0            0.0.0.0/0            connmark match  0xf001 NFQUEUE num 29
    0     0 NFQUEUE    tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            connmark match  0xf001 tcp flags:!0x02/0x02 NFQUEUE num 29
    0     0 NFQUEUE    udp  --  *      *       0.0.0.0/0            0.0.0.0/0            connmark match  0xf000 NFQUEUE num 28
    0     0 NFQUEUE    tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            connmark match  0xf000 tcp flags:!0x02/0x02 NFQUEUE num 28

Chain TRI-App (1 references)
 pkts bytes target     prot opt in     out     source               destination
  262 36742 TRI-Prx-App  all  --  *      *       0.0.0.0/0            0.0.0.0/0
   16 16400 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x40000062
  191 15970 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            connmark match  0xeeee
   55  4372 TRI-UID-App  all  --  *      *       0.0.0.0/0            0.0.0.0/0
    0     0 MARK       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set TRI-TargetTCP dst tcp flags:0x12/0x12 MARK set 0x63
    0     0 NFQUEUE    tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set TRI-TargetTCP dst tcp flags:0x12/0x12 NFQUEUE balance 8:11 bypass
   55  4372 TRI-Pid-App  all  --  *      *       0.0.0.0/0            0.0.0.0/0
   55  4372 TRI-Svc-App  all  --  *      *       0.0.0.0/0            0.0.0.0/0
   55  4372 TRI-Hst-App  all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain TRI-Hst-App (1 references)
 pkts bytes target     prot opt in     out     source               destination

Chain TRI-Hst-Net (1 references)
 pkts bytes target     prot opt in     out     source               destination

Chain TRI-Net (1 references)
 pkts bytes target     prot opt in     out     source               destination
  399 64375 TRI-Prx-Net  all  --  *      *       0.0.0.0/0            0.0.0.0/0
   16 16400 NFQUEUE    udp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set TRI-TargetUDP src STRING match  "n30njxq7bmiwr6dtxq" ALGO name bm TO 65535 NFQUEUE balance 24:27 bypass
  236 26032 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            connmark match  0xeeee
  147 21943 TRI-UID-Net  all  --  *      *       0.0.0.0/0            0.0.0.0/0
    1    44 NFQUEUE    tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set TRI-TargetTCP src tcp flags:0x12/0x12 NFQUEUE balance 24:27 bypass
    0     0 NFQUEUE    tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set TRI-TargetTCP src tcp option=34 flags:0x12/0x02 NFQUEUE balance 16:19 bypass
  146 21899 TRI-Pid-Net  all  --  *      *       0.0.0.0/0            0.0.0.0/0
  146 21899 TRI-Svc-Net  all  --  *      *       0.0.0.0/0            0.0.0.0/0
  146 21899 TRI-Hst-Net  all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain TRI-Pid-App (1 references)
 pkts bytes target     prot opt in     out     source               destination

Chain TRI-Pid-Net (1 references)
 pkts bytes target     prot opt in     out     source               destination

Chain TRI-Prx-App (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x40

Chain TRI-Prx-Net (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x40

Chain TRI-Svc-App (1 references)
 pkts bytes target     prot opt in     out     source               destination

Chain TRI-Svc-Net (1 references)
 pkts bytes target     prot opt in     out     source               destination

Chain TRI-UID-App (1 references)
 pkts bytes target     prot opt in     out     source               destination

Chain TRI-UID-Net (1 references)
 pkts bytes target     prot opt in     out     source               destination
```

### CODE REVIEW

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "refactor_acls",
    "component": "trireme-lib",
    "pr-id": "751",
    "commit-sha": "0f74b805c9f995d4a6f2c836e1c02acaf7ea1766"
  },
  {
    "project": "refactor_acls",
    "component": "enforcerd",
    "pr-id": "1067",
    "commit-sha": "f66ccbaf2f703d8e0752adb473b27e7acb07f5a2"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "refactor_acls",
    "component": "trireme-lib",
    "pr-id": "751",
    "commit-sha": "9cbe9395859b215fdc680329ce11331d0ecea67c"
  },
  {
    "project": "refactor_acls",
    "component": "enforcerd",
    "pr-id": "1067",
    "commit-sha": "f66ccbaf2f703d8e0752adb473b27e7acb07f5a2"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "refactor_acls",
    "component": "trireme-lib",
    "pr-id": "751",
    "commit-sha": "9cbe9395859b215fdc680329ce11331d0ecea67c"
  },
  {
    "project": "refactor_acls",
    "component": "enforcerd",
    "pr-id": "1067",
    "commit-sha": "58d985beeb0f86f500f69858af7447be891bc085"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "refactor_acls",
    "component": "trireme-lib",
    "pr-id": "751",
    "commit-sha": "9b3f54989b94827e5de4177c2b31934e7de4e7fd"
  },
  {
    "project": "refactor_acls",
    "component": "enforcerd",
    "pr-id": "1067",
    "commit-sha": "09e642ec1a0baf44e3ff6e4f03b66b4f770680f5"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "refactor_acls",
    "component": "trireme-lib",
    "pr-id": "751",
    "commit-sha": "8bb75b55f1da6baaeecec9a8b0138d40c31b5644"
  },
  {
    "project": "refactor_acls",
    "component": "enforcerd",
    "pr-id": "1067",
    "commit-sha": "09e642ec1a0baf44e3ff6e4f03b66b4f770680f5"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "751",
    "commit-sha": "c04595aceb6d8debe41c0fa75a854867004e3b3c"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "refactor_acls",
    "component": "enforcerd",
    "pr-id": "1067",
    "commit-sha": "09e642ec1a0baf44e3ff6e4f03b66b4f770680f5"
  },
  {
    "project": "refactor_acls",
    "component": "trireme-lib",
    "pr-id": "751",
    "commit-sha": "12b120e28a9fe01d0a2a98d99bbe0f18f991763d"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "refactor_acls",
    "component": "trireme-lib",
    "pr-id": "751",
    "commit-sha": "dc8f9f24a341e378894c9cb59c26cd6ff7bffde7"
  },
  {
    "project": "refactor_acls",
    "component": "enforcerd",
    "pr-id": "1067",
    "commit-sha": "8484e5a0dc93fc21b0979f734eede858ab67a93b"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "refactor_acls",
    "component": "trireme-lib",
    "pr-id": "751",
    "commit-sha": "dc8f9f24a341e378894c9cb59c26cd6ff7bffde7"
  },
  {
    "project": "refactor_acls",
    "component": "enforcerd",
    "pr-id": "1067",
    "commit-sha": "ecfe353da93dae617218a91560a3cb1400349249"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "refactor_acls",
    "component": "trireme-lib",
    "pr-id": "751",
    "commit-sha": "dc8f9f24a341e378894c9cb59c26cd6ff7bffde7"
  },
  {
    "project": "refactor_acls",
    "component": "enforcerd",
    "pr-id": "1067",
    "commit-sha": "63dba670dfade31091d9429946af127d43754bc5"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "refactor_acls",
    "component": "trireme-lib",
    "pr-id": "751",
    "commit-sha": "6705d8ebcc8a34f104abb0d70b6822420bd8ce57"
  },
  {
    "project": "refactor_acls",
    "component": "enforcerd",
    "pr-id": "1067",
    "commit-sha": "63dba670dfade31091d9429946af127d43754bc5"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "refactor_acls",
    "component": "trireme-lib",
    "pr-id": "751",
    "commit-sha": "94704e05713a7228f87415d6304585064e85e638"
  },
  {
    "project": "refactor_acls",
    "component": "enforcerd",
    "pr-id": "1067",
    "commit-sha": "63dba670dfade31091d9429946af127d43754bc5"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "refactor_acls",
    "component": "enforcerd",
    "pr-id": "1067",
    "commit-sha": "63dba670dfade31091d9429946af127d43754bc5"
  },
  {
    "project": "refactor_acls",
    "component": "trireme-lib",
    "pr-id": "751",
    "commit-sha": "a5886137bfbe382eadaa7992da2c6a623ac651e7"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "refactor_acls",
    "component": "trireme-lib",
    "pr-id": "751",
    "commit-sha": "a9dc25d4393d3d4458e34428eee2b73110b4a33d"
  },
  {
    "project": "refactor_acls",
    "component": "enforcerd",
    "pr-id": "1067",
    "commit-sha": "e57cc8d05ed29c69600e3952f5a586aa39d24d07"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "refactor_acls",
    "component": "trireme-lib",
    "pr-id": "751",
    "commit-sha": "08af26af80608d8178b2d00f1be6d35e9428e22e"
  },
  {
    "project": "refactor_acls",
    "component": "enforcerd",
    "pr-id": "1067",
    "commit-sha": "e57cc8d05ed29c69600e3952f5a586aa39d24d07"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "refactor_acls",
    "component": "trireme-lib",
    "pr-id": "751",
    "commit-sha": "f49aa2d02c762a38824003e1a1ca2bd10118463b"
  },
  {
    "project": "refactor_acls",
    "component": "enforcerd",
    "pr-id": "1067",
    "commit-sha": "1f20bfda52887eddc77439dc943b72c9f59e3b2d"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "refactor_acls",
    "component": "trireme-lib",
    "pr-id": "751",
    "commit-sha": "bdf59f5e75ff3741a546b7f17b8ec354cdfba78e"
  },
  {
    "project": "refactor_acls",
    "component": "enforcerd",
    "pr-id": "1067",
    "commit-sha": "1f20bfda52887eddc77439dc943b72c9f59e3b2d"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "refactor_acls",
    "component": "enforcerd",
    "pr-id": "1067",
    "commit-sha": "1f20bfda52887eddc77439dc943b72c9f59e3b2d"
  },
  {
    "project": "refactor_acls",
    "component": "trireme-lib",
    "pr-id": "751",
    "commit-sha": "bdf59f5e75ff3741a546b7f17b8ec354cdfba78e"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "refactor_acls",
    "component": "trireme-lib",
    "pr-id": "751",
    "commit-sha": "291d5204c991465191521f04347cedc79758b399"
  },
  {
    "project": "refactor_acls",
    "component": "enforcerd",
    "pr-id": "1067",
    "commit-sha": "1f20bfda52887eddc77439dc943b72c9f59e3b2d"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "refactor_acls",
    "component": "trireme-lib",
    "pr-id": "751",
    "commit-sha": "291d5204c991465191521f04347cedc79758b399"
  },
  {
    "project": "refactor_acls",
    "component": "enforcerd",
    "pr-id": "1067",
    "commit-sha": "1f20bfda52887eddc77439dc943b72c9f59e3b2d"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "refactor_acls",
    "component": "trireme-lib",
    "pr-id": "751",
    "commit-sha": "556a7991646872b1b4c6af3f543bdc3ebf1a6290"
  },
  {
    "project": "refactor_acls",
    "component": "enforcerd",
    "pr-id": "1067",
    "commit-sha": "1f20bfda52887eddc77439dc943b72c9f59e3b2d"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "refactor_acls",
    "component": "trireme-lib",
    "pr-id": "751",
    "commit-sha": "556a7991646872b1b4c6af3f543bdc3ebf1a6290"
  },
  {
    "project": "refactor_acls",
    "component": "enforcerd",
    "pr-id": "1067",
    "commit-sha": "68aa34c2ba3e3299f7b4b8d2e2e2825549b59f6f"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "refactor_acls",
    "component": "trireme-lib",
    "pr-id": "751",
    "commit-sha": "a0b105dd72165d23f8fdf80884e028208ab290ac"
  },
  {
    "project": "refactor_acls",
    "component": "enforcerd",
    "pr-id": "1067",
    "commit-sha": "68aa34c2ba3e3299f7b4b8d2e2e2825549b59f6f"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "refactor_acls",
    "component": "trireme-lib",
    "pr-id": "751",
    "commit-sha": "ac9da16c4867792a04b333dc0eb8ab2ee62618cf"
  },
  {
    "project": "refactor_acls",
    "component": "enforcerd",
    "pr-id": "1067",
    "commit-sha": "68aa34c2ba3e3299f7b4b8d2e2e2825549b59f6f"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "refactor_acls",
    "component": "trireme-lib",
    "pr-id": "751",
    "commit-sha": "164cc3837945cdb2d4375e7f1292262468e9c340"
  },
  {
    "project": "refactor_acls",
    "component": "enforcerd",
    "pr-id": "1067",
    "commit-sha": "68aa34c2ba3e3299f7b4b8d2e2e2825549b59f6f"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "refactor_acls",
    "component": "trireme-lib",
    "pr-id": "751",
    "commit-sha": "df8fa2fc88e334351fd262d8e22f0b55ea842453"
  },
  {
    "project": "refactor_acls",
    "component": "enforcerd",
    "pr-id": "1067",
    "commit-sha": "68aa34c2ba3e3299f7b4b8d2e2e2825549b59f6f"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "refactor_acls",
    "component": "trireme-lib",
    "pr-id": "751",
    "commit-sha": "db1a243802e4e24a0faf902f1f550b20fbd064dc"
  },
  {
    "project": "refactor_acls",
    "component": "enforcerd",
    "pr-id": "1067",
    "commit-sha": "68aa34c2ba3e3299f7b4b8d2e2e2825549b59f6f"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "refactor_acls",
    "component": "trireme-lib",
    "pr-id": "751",
    "commit-sha": "7da37655bac4d3b50f1f8e82e6c9cac82a5a02fa"
  },
  {
    "project": "refactor_acls",
    "component": "enforcerd",
    "pr-id": "1067",
    "commit-sha": "68aa34c2ba3e3299f7b4b8d2e2e2825549b59f6f"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "refactor_acls",
    "component": "trireme-lib",
    "pr-id": "751",
    "commit-sha": "36a71cdc89cacb211ab8989ee4234a8fe57292d3"
  },
  {
    "project": "refactor_acls",
    "component": "enforcerd",
    "pr-id": "1067",
    "commit-sha": "74f2da1dc24afa84738f864e9df86f8ea6891733"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "refactor_acls",
    "component": "enforcerd",
    "pr-id": "1067",
    "commit-sha": "74f2da1dc24afa84738f864e9df86f8ea6891733"
  },
  {
    "project": "refactor_acls",
    "component": "trireme-lib",
    "pr-id": "751",
    "commit-sha": "7c34e2184e76ef1e96126dc07665631ac3ca6ab4"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "refactor_acls",
    "component": "trireme-lib",
    "pr-id": "751",
    "commit-sha": "7c34e2184e76ef1e96126dc07665631ac3ca6ab4"
  },
  {
    "project": "refactor_acls",
    "component": "enforcerd",
    "pr-id": "1067",
    "commit-sha": "74f2da1dc24afa84738f864e9df86f8ea6891733"
  },
  {
    "project": "refactor_acls",
    "component": "apotests",
    "pr-id": "1966",
    "commit-sha": "c357a0945631ec0dec40adbb750bcf45dfc0bb58"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "refactor_acls",
    "component": "trireme-lib",
    "pr-id": "751",
    "commit-sha": "7c34e2184e76ef1e96126dc07665631ac3ca6ab4"
  },
  {
    "project": "refactor_acls",
    "component": "enforcerd",
    "pr-id": "1067",
    "commit-sha": "74f2da1dc24afa84738f864e9df86f8ea6891733"
  },
  {
    "project": "refactor_acls",
    "component": "apotests",
    "pr-id": "1966",
    "commit-sha": "4c0b31a4854c6c1860abf2bc4eb8c8dceb7756db"
  }
]
```

**Pull request merged**
