### PR TITLE
Proxies [WIP]

### PR DESCRIPTION
**Pull request by dstiliadis**
#### Description
This PR introduces support for L7 proxies using the Trireme framework.

### CODE REVIEW

**Comment by aporeto-dimitri** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "component": "trireme-lib",
    "pr-id": "475",
    "commit-sha": "093ab24ff40be2975227513767251f176c957b5b"
  },
  {
    "component": "tg",
    "pr-id": "7",
    "commit-sha": "1b93eabe7b6c6ec6467b6c02f13da520d6518004"
  },
  {
    "component": "underwater",
    "pr-id": "12",
    "commit-sha": "73c4a50edf98f9336dd326b79d54a35e3a675487"
  },
  {
    "component": "enforcerd",
    "pr-id": "466",
    "commit-sha": "66b47e025089f573a3aff1a86bda56fc49dca9a1"
  },
  {
    "component": "gaia",
    "pr-id": "103",
    "commit-sha": "7cc7cc3eca5fdf5111eda4fa2ed8641065128239"
  },
  {
    "component": "squall",
    "pr-id": "311",
    "commit-sha": "260a6400a30cdbdc46e9c0d0d222e35608455da5"
  }
]
```

**Comment by aporeto-dimitri** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "component": "gaia",
    "pr-id": "103",
    "commit-sha": "7cc7cc3eca5fdf5111eda4fa2ed8641065128239"
  },
  {
    "component": "squall",
    "pr-id": "311",
    "commit-sha": "260a6400a30cdbdc46e9c0d0d222e35608455da5"
  },
  {
    "component": "enforcerd",
    "pr-id": "466",
    "commit-sha": "90ef5219a2759648d8bd25c404915c46be93e1d3"
  },
  {
    "component": "trireme-lib",
    "pr-id": "475",
    "commit-sha": "093ab24ff40be2975227513767251f176c957b5b"
  },
  {
    "component": "underwater",
    "pr-id": "12",
    "commit-sha": "73c4a50edf98f9336dd326b79d54a35e3a675487"
  },
  {
    "component": "tg",
    "pr-id": "7",
    "commit-sha": "1b93eabe7b6c6ec6467b6c02f13da520d6518004"
  }
]
```

**Comment by aporeto-dimitri** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "component": "gaia",
    "pr-id": "103",
    "commit-sha": "7cc7cc3eca5fdf5111eda4fa2ed8641065128239"
  },
  {
    "component": "squall",
    "pr-id": "311",
    "commit-sha": "6f9130bc19f4af6d7c67ffee80e6cdda4cd8897c"
  },
  {
    "component": "enforcerd",
    "pr-id": "466",
    "commit-sha": "90ef5219a2759648d8bd25c404915c46be93e1d3"
  },
  {
    "component": "trireme-lib",
    "pr-id": "475",
    "commit-sha": "093ab24ff40be2975227513767251f176c957b5b"
  },
  {
    "component": "underwater",
    "pr-id": "12",
    "commit-sha": "73c4a50edf98f9336dd326b79d54a35e3a675487"
  },
  {
    "component": "tg",
    "pr-id": "7",
    "commit-sha": "1b93eabe7b6c6ec6467b6c02f13da520d6518004"
  }
]
```

**Comment by aporeto-dimitri** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "component": "trireme-lib",
    "pr-id": "475",
    "commit-sha": "093ab24ff40be2975227513767251f176c957b5b"
  },
  {
    "component": "underwater",
    "pr-id": "12",
    "commit-sha": "73c4a50edf98f9336dd326b79d54a35e3a675487"
  },
  {
    "component": "tg",
    "pr-id": "7",
    "commit-sha": "1b93eabe7b6c6ec6467b6c02f13da520d6518004"
  },
  {
    "component": "gaia",
    "pr-id": "103",
    "commit-sha": "7cc7cc3eca5fdf5111eda4fa2ed8641065128239"
  },
  {
    "component": "squall",
    "pr-id": "311",
    "commit-sha": "5ddc5a2d4262ac484e3bbf1c77cdda5f6ca02d00"
  },
  {
    "component": "enforcerd",
    "pr-id": "466",
    "commit-sha": "90ef5219a2759648d8bd25c404915c46be93e1d3"
  }
]
```

**Comment by aporeto-dimitri** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "component": "enforcerd",
    "pr-id": "466",
    "commit-sha": "4240dc299f17f98f41ebe8d6c558eeb30f3ffb0c"
  },
  {
    "component": "trireme-lib",
    "pr-id": "475",
    "commit-sha": "093ab24ff40be2975227513767251f176c957b5b"
  },
  {
    "component": "underwater",
    "pr-id": "12",
    "commit-sha": "73c4a50edf98f9336dd326b79d54a35e3a675487"
  },
  {
    "component": "tg",
    "pr-id": "7",
    "commit-sha": "1b93eabe7b6c6ec6467b6c02f13da520d6518004"
  },
  {
    "component": "gaia",
    "pr-id": "103",
    "commit-sha": "7cc7cc3eca5fdf5111eda4fa2ed8641065128239"
  },
  {
    "component": "squall",
    "pr-id": "311",
    "commit-sha": "5ddc5a2d4262ac484e3bbf1c77cdda5f6ca02d00"
  }
]
```

**Comment by aporeto-dimitri** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "component": "midgard",
    "pr-id": "34",
    "commit-sha": "7e6fdf200347f406e3001e387da11e53bf74a46d"
  },
  {
    "component": "gaia",
    "pr-id": "103",
    "commit-sha": "3ce54f9f21805896e8b5d89172cf0b6cf34b7fb7"
  },
  {
    "component": "squall",
    "pr-id": "311",
    "commit-sha": "c8114fb9a4467f8385bba8b327966c43cdf58e72"
  },
  {
    "component": "enforcerd",
    "pr-id": "466",
    "commit-sha": "4240dc299f17f98f41ebe8d6c558eeb30f3ffb0c"
  },
  {
    "component": "trireme-lib",
    "pr-id": "475",
    "commit-sha": "99c1a0a9d8beefa3ba6414036fe18cd0a1a1c1f9"
  },
  {
    "component": "underwater",
    "pr-id": "12",
    "commit-sha": "633eac5c7934b14b24166c8a13e1f9ef1f0b72f3"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "component": "squall",
    "pr-id": "311",
    "commit-sha": "c8114fb9a4467f8385bba8b327966c43cdf58e72"
  },
  {
    "component": "enforcerd",
    "pr-id": "466",
    "commit-sha": "c1f544eddddd3d1dc66bee55005e903dd23aa834"
  },
  {
    "component": "trireme-lib",
    "pr-id": "475",
    "commit-sha": "26a60e5eecf5ae82a486821545ed707f195b6db7"
  },
  {
    "component": "underwater",
    "pr-id": "12",
    "commit-sha": "7c55926b537f89f0fcf74d8f3e28825725677f02"
  },
  {
    "component": "gaia",
    "pr-id": "103",
    "commit-sha": "2f793c281aa8d71dc39aaf3112cf91e151b805ac"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "component": "gaia",
    "pr-id": "103",
    "commit-sha": "2f793c281aa8d71dc39aaf3112cf91e151b805ac"
  },
  {
    "component": "squall",
    "pr-id": "311",
    "commit-sha": "c8114fb9a4467f8385bba8b327966c43cdf58e72"
  },
  {
    "component": "enforcerd",
    "pr-id": "466",
    "commit-sha": "c1f544eddddd3d1dc66bee55005e903dd23aa834"
  },
  {
    "component": "trireme-lib",
    "pr-id": "475",
    "commit-sha": "26a60e5eecf5ae82a486821545ed707f195b6db7"
  },
  {
    "component": "underwater",
    "pr-id": "12",
    "commit-sha": "7c55926b537f89f0fcf74d8f3e28825725677f02"
  },
  {
    "component": "apoctl",
    "pr-id": "115",
    "commit-sha": "0cad776be52d9abb62afcead210b5c3e33c7d1d6"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "component": "squall",
    "pr-id": "311",
    "commit-sha": "c8114fb9a4467f8385bba8b327966c43cdf58e72"
  },
  {
    "component": "enforcerd",
    "pr-id": "466",
    "commit-sha": "c1f544eddddd3d1dc66bee55005e903dd23aa834"
  },
  {
    "component": "trireme-lib",
    "pr-id": "475",
    "commit-sha": "26a60e5eecf5ae82a486821545ed707f195b6db7"
  },
  {
    "component": "underwater",
    "pr-id": "12",
    "commit-sha": "7c55926b537f89f0fcf74d8f3e28825725677f02"
  },
  {
    "component": "apoctl",
    "pr-id": "115",
    "commit-sha": "0cad776be52d9abb62afcead210b5c3e33c7d1d6"
  },
  {
    "component": "gaia",
    "pr-id": "103",
    "commit-sha": "794df79775ac8d43348677b733eedec7298b36d4"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "component": "trireme-lib",
    "pr-id": "475",
    "commit-sha": "26a60e5eecf5ae82a486821545ed707f195b6db7"
  },
  {
    "component": "underwater",
    "pr-id": "12",
    "commit-sha": "7c55926b537f89f0fcf74d8f3e28825725677f02"
  },
  {
    "component": "apoctl",
    "pr-id": "115",
    "commit-sha": "62035a2ebf899b1a84c2d4ad205143ef88f44155"
  },
  {
    "component": "gaia",
    "pr-id": "103",
    "commit-sha": "794df79775ac8d43348677b733eedec7298b36d4"
  },
  {
    "component": "squall",
    "pr-id": "311",
    "commit-sha": "c8114fb9a4467f8385bba8b327966c43cdf58e72"
  },
  {
    "component": "enforcerd",
    "pr-id": "466",
    "commit-sha": "c1f544eddddd3d1dc66bee55005e903dd23aa834"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "component": "trireme-lib",
    "pr-id": "475",
    "commit-sha": "26a60e5eecf5ae82a486821545ed707f195b6db7"
  },
  {
    "component": "underwater",
    "pr-id": "12",
    "commit-sha": "7c55926b537f89f0fcf74d8f3e28825725677f02"
  },
  {
    "component": "apoctl",
    "pr-id": "115",
    "commit-sha": "58a1ae2176d4f6ef41118829760e67b0077aef77"
  },
  {
    "component": "gaia",
    "pr-id": "103",
    "commit-sha": "794df79775ac8d43348677b733eedec7298b36d4"
  },
  {
    "component": "squall",
    "pr-id": "311",
    "commit-sha": "c8114fb9a4467f8385bba8b327966c43cdf58e72"
  },
  {
    "component": "enforcerd",
    "pr-id": "466",
    "commit-sha": "c1f544eddddd3d1dc66bee55005e903dd23aa834"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "component": "gaia",
    "pr-id": "103",
    "commit-sha": "794df79775ac8d43348677b733eedec7298b36d4"
  },
  {
    "component": "squall",
    "pr-id": "311",
    "commit-sha": "2d9c13013da583688dcc10406490584fbfa76c64"
  },
  {
    "component": "enforcerd",
    "pr-id": "466",
    "commit-sha": "7b4004bc6ae8bda9825bf6a60159fd289e49d009"
  },
  {
    "component": "trireme-lib",
    "pr-id": "475",
    "commit-sha": "7c1dbb61f5dc55a8e7c9be0f834a53690930f4ae"
  },
  {
    "component": "underwater",
    "pr-id": "12",
    "commit-sha": "7c55926b537f89f0fcf74d8f3e28825725677f02"
  }
]
```

**Pull request closed without merging**
