### PR TITLE
Do not police traffic belonging to same pu

### PR DESCRIPTION
**Pull request by varks**

### CODE REVIEW

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "same_pu_traffic",
    "component": "trireme-lib",
    "pr-id": "700",
    "commit-sha": "d1d96fd3993aadee71994b80adf88af14ec72b9e"
  },
  {
    "project": "same_pu_traffic",
    "component": "enforcerd",
    "pr-id": "953",
    "commit-sha": "6007892b645d6b8e35994757d024a6fc8f8b244b"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "same_pu_traffic",
    "component": "enforcerd",
    "pr-id": "953",
    "commit-sha": "6007892b645d6b8e35994757d024a6fc8f8b244b"
  },
  {
    "project": "same_pu_traffic",
    "component": "trireme-lib",
    "pr-id": "700",
    "commit-sha": "ca13cf1de78e7429af4e3ee212963b4a0175715a"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "same_pu_traffic",
    "component": "enforcerd",
    "pr-id": "953",
    "commit-sha": "6007892b645d6b8e35994757d024a6fc8f8b244b"
  },
  {
    "project": "same_pu_traffic",
    "component": "trireme-lib",
    "pr-id": "700",
    "commit-sha": "963fa6de2c583741454340a485067e41f1f2c93f"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "same_pu_traffic",
    "component": "trireme-lib",
    "pr-id": "700",
    "commit-sha": "5b5d94c89a96cf4a7379f0f367e5974b5eab278f"
  },
  {
    "project": "same_pu_traffic",
    "component": "enforcerd",
    "pr-id": "953",
    "commit-sha": "6007892b645d6b8e35994757d024a6fc8f8b244b"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "same_pu_traffic",
    "component": "enforcerd",
    "pr-id": "953",
    "commit-sha": "6007892b645d6b8e35994757d024a6fc8f8b244b"
  },
  {
    "project": "same_pu_traffic",
    "component": "trireme-lib",
    "pr-id": "700",
    "commit-sha": "5b5d94c89a96cf4a7379f0f367e5974b5eab278f"
  },
  {
    "project": "same_pu_traffic",
    "component": "apotests",
    "pr-id": "1867",
    "commit-sha": "25e75c486a1c8862338309b14b870170a4c09c0f"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "same_pu_traffic",
    "component": "enforcerd",
    "pr-id": "953",
    "commit-sha": "4a16f4169cd8ca68b83a0da596610ee1a460745f"
  },
  {
    "project": "same_pu_traffic",
    "component": "trireme-lib",
    "pr-id": "700",
    "commit-sha": "5b5d94c89a96cf4a7379f0f367e5974b5eab278f"
  },
  {
    "project": "same_pu_traffic",
    "component": "apotests",
    "pr-id": "1867",
    "commit-sha": "25e75c486a1c8862338309b14b870170a4c09c0f"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "same_pu_traffic",
    "component": "enforcerd",
    "pr-id": "953",
    "commit-sha": "4a16f4169cd8ca68b83a0da596610ee1a460745f"
  },
  {
    "project": "same_pu_traffic",
    "component": "trireme-lib",
    "pr-id": "700",
    "commit-sha": "5b5d94c89a96cf4a7379f0f367e5974b5eab278f"
  },
  {
    "project": "same_pu_traffic",
    "component": "apotests",
    "pr-id": "1867",
    "commit-sha": "58c768f3ab7cf4763137d910f1fb9d9157a8beae"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "same_pu_traffic",
    "component": "enforcerd",
    "pr-id": "953",
    "commit-sha": "569862884da3e6ac6e1696c01f61141796f70729"
  },
  {
    "project": "same_pu_traffic",
    "component": "trireme-lib",
    "pr-id": "700",
    "commit-sha": "5b5d94c89a96cf4a7379f0f367e5974b5eab278f"
  },
  {
    "project": "same_pu_traffic",
    "component": "apotests",
    "pr-id": "1867",
    "commit-sha": "58c768f3ab7cf4763137d910f1fb9d9157a8beae"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "same_pu_traffic",
    "component": "enforcerd",
    "pr-id": "953",
    "commit-sha": "569862884da3e6ac6e1696c01f61141796f70729"
  },
  {
    "project": "same_pu_traffic",
    "component": "trireme-lib",
    "pr-id": "700",
    "commit-sha": "ad6fe84d8feed88412076a9e446c7f4eb0fb683a"
  },
  {
    "project": "same_pu_traffic",
    "component": "apotests",
    "pr-id": "1867",
    "commit-sha": "7e4200616d31e3617e8320242059f6c338d51c74"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "same_pu_traffic",
    "component": "trireme-lib",
    "pr-id": "700",
    "commit-sha": "b6068d57027ed184cc58e6c2d070e9eb42c940c4"
  },
  {
    "project": "same_pu_traffic",
    "component": "apotests",
    "pr-id": "1867",
    "commit-sha": "7e4200616d31e3617e8320242059f6c338d51c74"
  },
  {
    "project": "same_pu_traffic",
    "component": "enforcerd",
    "pr-id": "953",
    "commit-sha": "569862884da3e6ac6e1696c01f61141796f70729"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "same_pu_traffic",
    "component": "enforcerd",
    "pr-id": "953",
    "commit-sha": "569862884da3e6ac6e1696c01f61141796f70729"
  },
  {
    "project": "same_pu_traffic",
    "component": "trireme-lib",
    "pr-id": "700",
    "commit-sha": "9d18e2355a7bb400161c586f05e3bf58d993fa39"
  },
  {
    "project": "same_pu_traffic",
    "component": "apotests",
    "pr-id": "1867",
    "commit-sha": "7e4200616d31e3617e8320242059f6c338d51c74"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "same_pu_traffic",
    "component": "enforcerd",
    "pr-id": "953",
    "commit-sha": "569862884da3e6ac6e1696c01f61141796f70729"
  },
  {
    "project": "same_pu_traffic",
    "component": "trireme-lib",
    "pr-id": "700",
    "commit-sha": "206cfbd45191fa21774514cbc2a3b7cd6f7dad2a"
  },
  {
    "project": "same_pu_traffic",
    "component": "apotests",
    "pr-id": "1867",
    "commit-sha": "7e4200616d31e3617e8320242059f6c338d51c74"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "same_pu_traffic",
    "component": "enforcerd",
    "pr-id": "953",
    "commit-sha": "87b0165c28ac68209e701de3c264c00e8588c570"
  },
  {
    "project": "same_pu_traffic",
    "component": "trireme-lib",
    "pr-id": "700",
    "commit-sha": "206cfbd45191fa21774514cbc2a3b7cd6f7dad2a"
  },
  {
    "project": "same_pu_traffic",
    "component": "apotests",
    "pr-id": "1867",
    "commit-sha": "7e4200616d31e3617e8320242059f6c338d51c74"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "same_pu_traffic",
    "component": "apotests",
    "pr-id": "1867",
    "commit-sha": "7e4200616d31e3617e8320242059f6c338d51c74"
  },
  {
    "project": "same_pu_traffic",
    "component": "enforcerd",
    "pr-id": "953",
    "commit-sha": "cd463eda29a2f6b0456026672c1a7d687392b714"
  },
  {
    "project": "same_pu_traffic",
    "component": "trireme-lib",
    "pr-id": "700",
    "commit-sha": "206cfbd45191fa21774514cbc2a3b7cd6f7dad2a"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "same_pu_traffic",
    "component": "enforcerd",
    "pr-id": "953",
    "commit-sha": "a2ef2a54119f126d91e5496a32375d6a30fa128b"
  },
  {
    "project": "same_pu_traffic",
    "component": "trireme-lib",
    "pr-id": "700",
    "commit-sha": "206cfbd45191fa21774514cbc2a3b7cd6f7dad2a"
  },
  {
    "project": "same_pu_traffic",
    "component": "apotests",
    "pr-id": "1867",
    "commit-sha": "63f14c20ae5cb7397cfa9f34230f4ee82c590c56"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "same_pu_traffic",
    "component": "apotests",
    "pr-id": "1867",
    "commit-sha": "63f14c20ae5cb7397cfa9f34230f4ee82c590c56"
  },
  {
    "project": "same_pu_traffic",
    "component": "enforcerd",
    "pr-id": "953",
    "commit-sha": "a2ef2a54119f126d91e5496a32375d6a30fa128b"
  },
  {
    "project": "same_pu_traffic",
    "component": "trireme-lib",
    "pr-id": "700",
    "commit-sha": "206cfbd45191fa21774514cbc2a3b7cd6f7dad2a"
  }
]
```

**Review by dstiliadis — APPROVED** [review]

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "same_pu_traffic",
    "component": "enforcerd",
    "pr-id": "953",
    "commit-sha": "a2ef2a54119f126d91e5496a32375d6a30fa128b"
  },
  {
    "project": "same_pu_traffic",
    "component": "trireme-lib",
    "pr-id": "700",
    "commit-sha": "092841f3762e473bb021763cbdb10721eb8f7f3c"
  },
  {
    "project": "same_pu_traffic",
    "component": "apotests",
    "pr-id": "1867",
    "commit-sha": "002f76c734d0afc33039822400a7e2a2bf4fe17d"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "same_pu_traffic",
    "component": "enforcerd",
    "pr-id": "953",
    "commit-sha": "a2ef2a54119f126d91e5496a32375d6a30fa128b"
  },
  {
    "project": "same_pu_traffic",
    "component": "trireme-lib",
    "pr-id": "700",
    "commit-sha": "092841f3762e473bb021763cbdb10721eb8f7f3c"
  },
  {
    "project": "same_pu_traffic",
    "component": "apotests",
    "pr-id": "1867",
    "commit-sha": "002f76c734d0afc33039822400a7e2a2bf4fe17d"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "same_pu_traffic",
    "component": "apotests",
    "pr-id": "1867",
    "commit-sha": "002f76c734d0afc33039822400a7e2a2bf4fe17d"
  },
  {
    "project": "same_pu_traffic",
    "component": "enforcerd",
    "pr-id": "953",
    "commit-sha": "470c5a88327b29550cd8e69f7939cbad63c47a07"
  },
  {
    "project": "same_pu_traffic",
    "component": "trireme-lib",
    "pr-id": "700",
    "commit-sha": "092841f3762e473bb021763cbdb10721eb8f7f3c"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "same_pu_traffic",
    "component": "enforcerd",
    "pr-id": "953",
    "commit-sha": "470c5a88327b29550cd8e69f7939cbad63c47a07"
  },
  {
    "project": "same_pu_traffic",
    "component": "trireme-lib",
    "pr-id": "700",
    "commit-sha": "eeaa518b2bb1c5b87e66daaba32950e44fbe2231"
  },
  {
    "project": "same_pu_traffic",
    "component": "apotests",
    "pr-id": "1867",
    "commit-sha": "002f76c734d0afc33039822400a7e2a2bf4fe17d"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "same_pu_traffic",
    "component": "trireme-lib",
    "pr-id": "700",
    "commit-sha": "0cce68f16b20188e3ba181c93734c81f9d0fd079"
  },
  {
    "project": "same_pu_traffic",
    "component": "apotests",
    "pr-id": "1867",
    "commit-sha": "002f76c734d0afc33039822400a7e2a2bf4fe17d"
  },
  {
    "project": "same_pu_traffic",
    "component": "enforcerd",
    "pr-id": "953",
    "commit-sha": "470c5a88327b29550cd8e69f7939cbad63c47a07"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "same_pu_traffic",
    "component": "enforcerd",
    "pr-id": "953",
    "commit-sha": "470c5a88327b29550cd8e69f7939cbad63c47a07"
  },
  {
    "project": "same_pu_traffic",
    "component": "trireme-lib",
    "pr-id": "700",
    "commit-sha": "17d8d5d6925d2acadf9c35c5070bc8be7b9f4f70"
  },
  {
    "project": "same_pu_traffic",
    "component": "apotests",
    "pr-id": "1867",
    "commit-sha": "c353c3a69799921a87351f320c65ca27fca09db7"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "same_pu_traffic",
    "component": "trireme-lib",
    "pr-id": "700",
    "commit-sha": "0f9d71e3ac98c91a87f2cd5c9406011b899af375"
  },
  {
    "project": "same_pu_traffic",
    "component": "apotests",
    "pr-id": "1867",
    "commit-sha": "c353c3a69799921a87351f320c65ca27fca09db7"
  },
  {
    "project": "same_pu_traffic",
    "component": "enforcerd",
    "pr-id": "953",
    "commit-sha": "470c5a88327b29550cd8e69f7939cbad63c47a07"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "same_pu_traffic",
    "component": "enforcerd",
    "pr-id": "953",
    "commit-sha": "470c5a88327b29550cd8e69f7939cbad63c47a07"
  },
  {
    "project": "same_pu_traffic",
    "component": "trireme-lib",
    "pr-id": "700",
    "commit-sha": "0f9d71e3ac98c91a87f2cd5c9406011b899af375"
  },
  {
    "project": "same_pu_traffic",
    "component": "apotests",
    "pr-id": "1867",
    "commit-sha": "c353c3a69799921a87351f320c65ca27fca09db7"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "700",
    "commit-sha": "0f9d71e3ac98c91a87f2cd5c9406011b899af375"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "700",
    "commit-sha": "84c84db1b3132dd90fedb7c4a38bb93c62fd7064"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "same_pu_traffic",
    "component": "apotests",
    "pr-id": "1867",
    "commit-sha": "c353c3a69799921a87351f320c65ca27fca09db7"
  },
  {
    "project": "same_pu_traffic",
    "component": "enforcerd",
    "pr-id": "953",
    "commit-sha": "470c5a88327b29550cd8e69f7939cbad63c47a07"
  },
  {
    "project": "same_pu_traffic",
    "component": "trireme-lib",
    "pr-id": "700",
    "commit-sha": "84c84db1b3132dd90fedb7c4a38bb93c62fd7064"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "same_pu_traffic",
    "component": "enforcerd",
    "pr-id": "953",
    "commit-sha": "470c5a88327b29550cd8e69f7939cbad63c47a07"
  },
  {
    "project": "same_pu_traffic",
    "component": "apotests",
    "pr-id": "1867",
    "commit-sha": "71544a0419d07874d965866a02bf6e611be61778"
  },
  {
    "project": "same_pu_traffic",
    "component": "trireme-lib",
    "pr-id": "700",
    "commit-sha": "84c84db1b3132dd90fedb7c4a38bb93c62fd7064"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "same_pu_traffic",
    "component": "apotests",
    "pr-id": "1867",
    "commit-sha": "ee0e1e35719bdd73caaa2c20ef342e33761cfcc4"
  },
  {
    "project": "same_pu_traffic",
    "component": "trireme-lib",
    "pr-id": "700",
    "commit-sha": "84c84db1b3132dd90fedb7c4a38bb93c62fd7064"
  },
  {
    "project": "same_pu_traffic",
    "component": "enforcerd",
    "pr-id": "953",
    "commit-sha": "470c5a88327b29550cd8e69f7939cbad63c47a07"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "same_pu_traffic",
    "component": "trireme-lib",
    "pr-id": "700",
    "commit-sha": "84c84db1b3132dd90fedb7c4a38bb93c62fd7064"
  },
  {
    "project": "same_pu_traffic",
    "component": "enforcerd",
    "pr-id": "953",
    "commit-sha": "4245db82b83016a9afe2669df4c1a5a31d69a2f7"
  },
  {
    "project": "same_pu_traffic",
    "component": "apotests",
    "pr-id": "1867",
    "commit-sha": "ee0e1e35719bdd73caaa2c20ef342e33761cfcc4"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "same_pu_traffic",
    "component": "trireme-lib",
    "pr-id": "700",
    "commit-sha": "84c84db1b3132dd90fedb7c4a38bb93c62fd7064"
  },
  {
    "project": "same_pu_traffic",
    "component": "enforcerd",
    "pr-id": "953",
    "commit-sha": "4245db82b83016a9afe2669df4c1a5a31d69a2f7"
  },
  {
    "project": "same_pu_traffic",
    "component": "apotests",
    "pr-id": "1867",
    "commit-sha": "ee0e1e35719bdd73caaa2c20ef342e33761cfcc4"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "same_pu_traffic",
    "component": "trireme-lib",
    "pr-id": "700",
    "commit-sha": "f187172e9ddc51d5ff77d8b9a47fe287d1840ec8"
  },
  {
    "project": "same_pu_traffic",
    "component": "enforcerd",
    "pr-id": "953",
    "commit-sha": "0d901266dbf4bea6ddf6006718425b0c988b2f6f"
  },
  {
    "project": "same_pu_traffic",
    "component": "apotests",
    "pr-id": "1867",
    "commit-sha": "ee0e1e35719bdd73caaa2c20ef342e33761cfcc4"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "same_pu_traffic",
    "component": "trireme-lib",
    "pr-id": "700",
    "commit-sha": "f187172e9ddc51d5ff77d8b9a47fe287d1840ec8"
  },
  {
    "project": "same_pu_traffic",
    "component": "enforcerd",
    "pr-id": "953",
    "commit-sha": "0d901266dbf4bea6ddf6006718425b0c988b2f6f"
  },
  {
    "project": "same_pu_traffic",
    "component": "apotests",
    "pr-id": "1867",
    "commit-sha": "830c1824b70c3885309074ba26dea0ed5f7e32a0"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "same_pu_traffic",
    "component": "trireme-lib",
    "pr-id": "700",
    "commit-sha": "a62089926ffdb9a5acad67ed363cad78f8ba72f5"
  },
  {
    "project": "same_pu_traffic",
    "component": "enforcerd",
    "pr-id": "953",
    "commit-sha": "c19ff13c4d1cc9e2163e022cf922253ac5afc514"
  },
  {
    "project": "same_pu_traffic",
    "component": "apotests",
    "pr-id": "1867",
    "commit-sha": "e1fadac9b1a0809884e51908edb9997329fdcf65"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "same_pu_traffic",
    "component": "trireme-lib",
    "pr-id": "700",
    "commit-sha": "a62089926ffdb9a5acad67ed363cad78f8ba72f5"
  },
  {
    "project": "same_pu_traffic",
    "component": "enforcerd",
    "pr-id": "953",
    "commit-sha": "c19ff13c4d1cc9e2163e022cf922253ac5afc514"
  },
  {
    "project": "same_pu_traffic",
    "component": "apotests",
    "pr-id": "1867",
    "commit-sha": "e063fd36f017a7363bc51cf5ccb4983984eb2f92"
  }
]
```

**Pull request merged**
