### PR TITLE
Option to configure cgroup cleaner path

### PR DESCRIPTION
**Pull request by amitlimaye**
#### Description
*Changes proposed in this pull request.*

#### Test plan
*Outline the test plan used to test this change before merging it.*

> Fixes #.

### CODE REVIEW

**Comment by amitlimaye** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1425",
    "commit-sha": "a39b1d6e98ee996e6788fca80304766a7b3a81b6"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "903",
    "commit-sha": "4b9f6eede18ae35c2fb71e5e732d5d99cc4d0195"
  }
]
```

**Comment by amitlimaye** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1425",
    "commit-sha": "40a8f4f09823e0168133f64b6321ae5fbee40fbf"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "903",
    "commit-sha": "4b9f6eede18ae35c2fb71e5e732d5d99cc4d0195"
  }
]
```

**Comment by amitlimaye** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1425",
    "commit-sha": "40a8f4f09823e0168133f64b6321ae5fbee40fbf"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "903",
    "commit-sha": "c0f85d8389393f6ffe56386ed6537fc18a238a23"
  }
]
```

**Review by dstiliadis — APPROVED** [review]

**Comment by amitlimaye** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1425",
    "commit-sha": "312f4691694b0fab2c8545889902ab04effd742b"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "903",
    "commit-sha": "c0f85d8389393f6ffe56386ed6537fc18a238a23"
  }
]
```

**Comment by amitlimaye** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "1425",
    "commit-sha": "2785553b7fea582a171e3832b696e5614b43a76f"
  },
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "903",
    "commit-sha": "c0f85d8389393f6ffe56386ed6537fc18a238a23"
  }
]
```

**Review by satyamsi — APPROVED** [review]

**Pull request merged**
