### PR TITLE
New: Resync existing host pus

### PR DESCRIPTION
**Pull request by sibicramesh**
--> This PR prevents creating duplicate/new host pus

### CODE REVIEW

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "duplicate-host-pus",
    "component": "enforcerd",
    "pr-id": "719",
    "commit-sha": "0ebcefee7a1657e9ce2422712f31b5539e19b2c5"
  },
  {
    "project": "duplicate-host-pus",
    "component": "trireme-lib",
    "pr-id": "594",
    "commit-sha": "a28b8d367fe06b57418e1634e8220167f1b944bd"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "duplicate-host-pus",
    "component": "enforcerd",
    "pr-id": "719",
    "commit-sha": "a9acac51e4caacccad55e4eaecd52d01660ba6e4"
  },
  {
    "project": "duplicate-host-pus",
    "component": "trireme-lib",
    "pr-id": "594",
    "commit-sha": "b3a20f1e3818f3c6860c662ee3f7b4e99c79c420"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "duplicate-host-pus",
    "component": "enforcerd",
    "pr-id": "719",
    "commit-sha": "2139c8527d1ee448dfaf99456a86ceb83d2cbbe0"
  },
  {
    "project": "duplicate-host-pus",
    "component": "trireme-lib",
    "pr-id": "594",
    "commit-sha": "99b558f66bd24ca7cb8f92d8b2a4467d3a033f03"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "duplicate-host-pus",
    "component": "enforcerd",
    "pr-id": "719",
    "commit-sha": "0280c868cf58c5ce2355e08d734de855725f93c7"
  },
  {
    "project": "duplicate-host-pus",
    "component": "trireme-lib",
    "pr-id": "594",
    "commit-sha": "99b558f66bd24ca7cb8f92d8b2a4467d3a033f03"
  },
  {
    "project": "duplicate-host-pus",
    "component": "apotests",
    "pr-id": "1677",
    "commit-sha": "a9c49f37e7818db70c95a1feac701d96d22adde2"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "duplicate-host-pus",
    "component": "enforcerd",
    "pr-id": "719",
    "commit-sha": "6ace4a7cbb9c9bff5e4abaa970ed56db25a5d2da"
  },
  {
    "project": "duplicate-host-pus",
    "component": "trireme-lib",
    "pr-id": "594",
    "commit-sha": "99b558f66bd24ca7cb8f92d8b2a4467d3a033f03"
  },
  {
    "project": "duplicate-host-pus",
    "component": "apotests",
    "pr-id": "1677",
    "commit-sha": "a9c49f37e7818db70c95a1feac701d96d22adde2"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "duplicate-host-pus",
    "component": "enforcerd",
    "pr-id": "719",
    "commit-sha": "a98a752308ec5183e7f99960934c239877136c07"
  },
  {
    "project": "duplicate-host-pus",
    "component": "trireme-lib",
    "pr-id": "594",
    "commit-sha": "99b558f66bd24ca7cb8f92d8b2a4467d3a033f03"
  },
  {
    "project": "duplicate-host-pus",
    "component": "apotests",
    "pr-id": "1677",
    "commit-sha": "a9c49f37e7818db70c95a1feac701d96d22adde2"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "duplicate-host-pus",
    "component": "trireme-lib",
    "pr-id": "594",
    "commit-sha": "0cc357e1a0bd928066f1a0f3227bd3a8eab3517e"
  },
  {
    "project": "duplicate-host-pus",
    "component": "apotests",
    "pr-id": "1677",
    "commit-sha": "338e62be1fe4c12e9cd1f414b90033bf7a54ab93"
  },
  {
    "project": "duplicate-host-pus",
    "component": "enforcerd",
    "pr-id": "719",
    "commit-sha": "ce3c19b0d93d721f08a21d6beb24c92e17bcdabe"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "duplicate-host-pus",
    "component": "trireme-lib",
    "pr-id": "594",
    "commit-sha": "0cc357e1a0bd928066f1a0f3227bd3a8eab3517e"
  },
  {
    "project": "duplicate-host-pus",
    "component": "apotests",
    "pr-id": "1677",
    "commit-sha": "338e62be1fe4c12e9cd1f414b90033bf7a54ab93"
  },
  {
    "project": "duplicate-host-pus",
    "component": "enforcerd",
    "pr-id": "719",
    "commit-sha": "ce3c19b0d93d721f08a21d6beb24c92e17bcdabe"
  }
]
```

**Review by dstiliadis — APPROVED** [review]

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "594",
    "commit-sha": "33b66faa29e51ddb4ffec2d25130445d04ef20c5"
  }
]
```

**Review by satyamsi — APPROVED** [review]

**Pull request merged**
