### PR TITLE
Kubernetes tags reduction: slimming pod extractor interface

### PR DESCRIPTION
**Pull request by mheese**
Implements aporeto-inc/aporeto#2622

### CODE REVIEW

**Comment by mheese** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "reduce-k8s-tags",
    "component": "enforcerd",
    "pr-id": "1591",
    "commit-sha": "433dfadab6aa5b4aabb6ac1f9a48f6c9908fc784",
    "pipeline": "master"
  },
  {
    "project": "reduce-k8s-tags",
    "component": "trireme-lib",
    "pr-id": "999",
    "commit-sha": "e096b4c881bfc68d8414146d5b1c6f6f5b6ed502",
    "pipeline": "master"
  },
  {
    "project": "reduce-k8s-tags",
    "component": "apotests",
    "pr-id": "2457",
    "commit-sha": "bb2d9e689ac5fe3aef12669583fa2d7e960913b8",
    "pipeline": "master"
  }
]
```

**Comment by mheese** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "reduce-k8s-tags",
    "component": "trireme-lib",
    "pr-id": "999",
    "commit-sha": "e2d06e88e1deeffd17042cfd3b23936a99d9ae7d",
    "pipeline": "master"
  },
  {
    "project": "reduce-k8s-tags",
    "component": "apotests",
    "pr-id": "2457",
    "commit-sha": "bb2d9e689ac5fe3aef12669583fa2d7e960913b8",
    "pipeline": "master"
  },
  {
    "project": "reduce-k8s-tags",
    "component": "enforcerd",
    "pr-id": "1591",
    "commit-sha": "433dfadab6aa5b4aabb6ac1f9a48f6c9908fc784",
    "pipeline": "master"
  }
]
```

**Comment by mheese** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "reduce-k8s-tags",
    "component": "enforcerd",
    "pr-id": "1591",
    "commit-sha": "f865fbab38620fa7fc611efbbf76256f5c5b4982",
    "pipeline": "master"
  },
  {
    "project": "reduce-k8s-tags",
    "component": "trireme-lib",
    "pr-id": "999",
    "commit-sha": "a9e7d3941d394415c5fd547aed50d4a5b96a8134",
    "pipeline": "master"
  },
  {
    "project": "reduce-k8s-tags",
    "component": "apotests",
    "pr-id": "2457",
    "commit-sha": "31dced63fe257e79eb03443de176388ff51461a8",
    "pipeline": "master"
  }
]
```

**Comment by mheese** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "reduce-k8s-tags",
    "component": "enforcerd",
    "pr-id": "1591",
    "commit-sha": "11847dc62ce6c071a6215ec5d39a9191ed5272d1",
    "pipeline": "master"
  },
  {
    "project": "reduce-k8s-tags",
    "component": "trireme-lib",
    "pr-id": "999",
    "commit-sha": "a9e7d3941d394415c5fd547aed50d4a5b96a8134",
    "pipeline": "master"
  },
  {
    "project": "reduce-k8s-tags",
    "component": "apotests",
    "pr-id": "2457",
    "commit-sha": "1339b8f4e6da9221c3c7f11df6efd2f65ed0ea76",
    "pipeline": "master"
  }
]
```

**Comment by mheese** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "reduce-k8s-tags",
    "component": "enforcerd",
    "pr-id": "1591",
    "commit-sha": "11847dc62ce6c071a6215ec5d39a9191ed5272d1",
    "pipeline": "master"
  },
  {
    "project": "reduce-k8s-tags",
    "component": "trireme-lib",
    "pr-id": "999",
    "commit-sha": "a9e7d3941d394415c5fd547aed50d4a5b96a8134",
    "pipeline": "master"
  },
  {
    "project": "reduce-k8s-tags",
    "component": "apotests",
    "pr-id": "2457",
    "commit-sha": "1339b8f4e6da9221c3c7f11df6efd2f65ed0ea76",
    "pipeline": "master"
  }
]
```

**Comment by mheese** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "reduce-k8s-tags",
    "component": "enforcerd",
    "pr-id": "1591",
    "commit-sha": "11847dc62ce6c071a6215ec5d39a9191ed5272d1",
    "pipeline": "master"
  },
  {
    "project": "reduce-k8s-tags",
    "component": "trireme-lib",
    "pr-id": "999",
    "commit-sha": "a9e7d3941d394415c5fd547aed50d4a5b96a8134",
    "pipeline": "master"
  },
  {
    "project": "reduce-k8s-tags",
    "component": "apotests",
    "pr-id": "2457",
    "commit-sha": "1339b8f4e6da9221c3c7f11df6efd2f65ed0ea76",
    "pipeline": "master"
  }
]
```

**Comment by mheese** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "reduce-k8s-tags",
    "component": "trireme-lib",
    "pr-id": "999",
    "commit-sha": "a9e7d3941d394415c5fd547aed50d4a5b96a8134",
    "pipeline": "master"
  },
  {
    "project": "reduce-k8s-tags",
    "component": "apotests",
    "pr-id": "2457",
    "commit-sha": "1339b8f4e6da9221c3c7f11df6efd2f65ed0ea76",
    "pipeline": "master"
  },
  {
    "project": "reduce-k8s-tags",
    "component": "enforcerd",
    "pr-id": "1591",
    "commit-sha": "11847dc62ce6c071a6215ec5d39a9191ed5272d1",
    "pipeline": "master"
  }
]
```

**Comment by mheese** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "reduce-k8s-tags",
    "component": "enforcerd",
    "pr-id": "1591",
    "commit-sha": "11847dc62ce6c071a6215ec5d39a9191ed5272d1",
    "pipeline": "master"
  },
  {
    "project": "reduce-k8s-tags",
    "component": "trireme-lib",
    "pr-id": "999",
    "commit-sha": "a9e7d3941d394415c5fd547aed50d4a5b96a8134",
    "pipeline": "master"
  },
  {
    "project": "reduce-k8s-tags",
    "component": "apotests",
    "pr-id": "2457",
    "commit-sha": "1339b8f4e6da9221c3c7f11df6efd2f65ed0ea76",
    "pipeline": "master"
  }
]
```

**Review by abhijitherekar — APPROVED** [review]
LGTM.

**Pull request merged**
