### PR TITLE
new: nflog rule for each extension

### PR DESCRIPTION
**Pull request by sibicramesh**
>> WARNING: Make sure the rule contains the action at the end. 
For example:
This will work
iptables -A INPUT -p tcp --dport 20 -j DROP
This will NOT work
iptables -A INPUT -j DROP -p tcp --dport 20 

--> Provides visibility to the extension rules when the log option in in policy is enabled.
--> Extensions like this,
```console
"-m u32 ! --u32 \"6&0xFF=1\" -j DROP",
"--match multiport --dports 53 -m bpf --bytecode \"20,0 0 0 0,177 0 0 0,12 0 0 0,7 0 0 0,72 0 0 4,53 0 13 29,135 0 0 0,4 0 0 8,7 0 0 0,72 0 0 2,84 0 0 64655,21 0 7 0,72 0 0 4,21 0 5 1,64 0 0 6,21 0 3 0,72 0 0 10,37 1 0 1,6 0 0 0,6 0 0 65535\" -j DROP"
```
will program iptable rules like this on top of pu chain,
```console
Chain TRI-App-3079t_0RXU-0 (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 NFLOG      icmp --  *      *       0.0.0.0/0            0.0.0.0/0            match-set TRI-v4-ext-1NBdR3079zqUx dst u32 ! "0x6&0xff=0x1" state NEW nflog-prefix  "11963819:5d2510195ed69729b398dc8e:5d4b60655ed69791ec9c8df1:6" nflog-group 10
    0     0 DROP       icmp --  *      *       0.0.0.0/0            0.0.0.0/0            match-set TRI-v4-ext-1NBdR3079zqUx dst u32 ! "0x6&0xff=0x1"
    0     0 NFLOG      udp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set TRI-v4-ext-MvAKq3079zqUx dst multiport dports 53bpf [unsupported revision]  state NEW nflog-prefix  "11963819:5d2510195ed69729b398dc8e:5d3fec3fc7820f30f6cbdaf7:6" nflog-group 10
    0     0 DROP       udp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set TRI-v4-ext-MvAKq3079zqUx dst multiport dports 53bpf [unsupported revision]
...
```

>> NOTE: The protocol is from iprule, because otherwise the report endpoint will point to a different policy. Ports are optional because, protcols like icmp doesn't work on ports.

### CODE REVIEW

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "extensions",
    "component": "enforcerd",
    "pr-id": "1323",
    "commit-sha": "31b57fef02a191b639ef2b1c1db474ab792b3652"
  },
  {
    "project": "extensions",
    "component": "trireme-lib",
    "pr-id": "852",
    "commit-sha": "b3f3beac915b4601e8ff1e5f41ac9055a7b4283a"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "extensions",
    "component": "trireme-lib",
    "pr-id": "852",
    "commit-sha": "988c7d6669226697aeaa786fc73228bb47e2b803"
  },
  {
    "project": "extensions",
    "component": "enforcerd",
    "pr-id": "1323",
    "commit-sha": "e667c68329eaf9ffefb4b395a095bd9c67ba2c8a"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "extensions",
    "component": "enforcerd",
    "pr-id": "1323",
    "commit-sha": "e667c68329eaf9ffefb4b395a095bd9c67ba2c8a"
  },
  {
    "project": "extensions",
    "component": "trireme-lib",
    "pr-id": "852",
    "commit-sha": "55083f916cc16575a74cac0f24698161c93f71a8"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "extensions",
    "component": "enforcerd",
    "pr-id": "1323",
    "commit-sha": "76c659cd837fdb1703f9617c0558e961948afd84"
  },
  {
    "project": "extensions",
    "component": "trireme-lib",
    "pr-id": "852",
    "commit-sha": "354118077813843ff5ee39acfb7528f0f7dce349"
  }
]
```

**Review by dstiliadis — APPROVED** [review]

**Pull request merged**
