### PR TITLE
Fix race conditions with log enabled

### PR DESCRIPTION
**Pull request by dstiliadis**
Fixes race conditions in the use of the log level variable.

### CODE REVIEW

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "enforcerd-expand-integ",
    "component": "trireme-lib",
    "pr-id": "836",
    "commit-sha": "adfcac12f589325b8c1764f77b1ff9173be6fb9e"
  },
  {
    "project": "enforcerd-expand-integ",
    "component": "integrations-lib",
    "pr-id": "121",
    "commit-sha": "dd8e0382c1dfd82c910340b175dee6a67b8ff99a"
  },
  {
    "project": "enforcerd-expand-integ",
    "component": "enforcerd",
    "pr-id": "1290",
    "commit-sha": "40d4f0f007553eea227ed299e85f4b3d3176ac75"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "enforcerd-expand-integ",
    "component": "enforcerd",
    "pr-id": "1290",
    "commit-sha": "40d4f0f007553eea227ed299e85f4b3d3176ac75"
  },
  {
    "project": "enforcerd-expand-integ",
    "component": "trireme-lib",
    "pr-id": "836",
    "commit-sha": "adfcac12f589325b8c1764f77b1ff9173be6fb9e"
  },
  {
    "project": "enforcerd-expand-integ",
    "component": "integrations-lib",
    "pr-id": "121",
    "commit-sha": "dd8e0382c1dfd82c910340b175dee6a67b8ff99a"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "enforcerd-expand-integ",
    "component": "enforcerd",
    "pr-id": "1290",
    "commit-sha": "40d4f0f007553eea227ed299e85f4b3d3176ac75"
  },
  {
    "project": "enforcerd-expand-integ",
    "component": "trireme-lib",
    "pr-id": "836",
    "commit-sha": "adfcac12f589325b8c1764f77b1ff9173be6fb9e"
  },
  {
    "project": "enforcerd-expand-integ",
    "component": "integrations-lib",
    "pr-id": "121",
    "commit-sha": "08a84ab46ce8e183dcdea169ef8dd74949d11ac7"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "enforcerd-expand-integ",
    "component": "trireme-lib",
    "pr-id": "836",
    "commit-sha": "5ad4a375b58cce406962a0e52ed14cd47afc330b"
  },
  {
    "project": "enforcerd-expand-integ",
    "component": "integrations-lib",
    "pr-id": "121",
    "commit-sha": "08a84ab46ce8e183dcdea169ef8dd74949d11ac7"
  },
  {
    "project": "enforcerd-expand-integ",
    "component": "enforcerd",
    "pr-id": "1290",
    "commit-sha": "40d4f0f007553eea227ed299e85f4b3d3176ac75"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "enforcerd-expand-integ",
    "component": "integrations-lib",
    "pr-id": "121",
    "commit-sha": "5fb39da3c83260bd67b5b62c916ffbb224f419a3"
  },
  {
    "project": "enforcerd-expand-integ",
    "component": "enforcerd",
    "pr-id": "1290",
    "commit-sha": "a6725bb58ce817bb3f939f236e0eacc806f87c5a"
  },
  {
    "project": "enforcerd-expand-integ",
    "component": "trireme-lib",
    "pr-id": "836",
    "commit-sha": "5ad4a375b58cce406962a0e52ed14cd47afc330b"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "enforcerd-expand-integ",
    "component": "enforcerd",
    "pr-id": "1290",
    "commit-sha": "93a3a002e0e32d76c732183598dbafa72cfbe905"
  },
  {
    "project": "enforcerd-expand-integ",
    "component": "trireme-lib",
    "pr-id": "836",
    "commit-sha": "5139b8c9783ab4b411cfda3cf6419864701756df"
  },
  {
    "project": "enforcerd-expand-integ",
    "component": "integrations-lib",
    "pr-id": "121",
    "commit-sha": "5fb39da3c83260bd67b5b62c916ffbb224f419a3"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "enforcerd-expand-integ",
    "component": "enforcerd",
    "pr-id": "1290",
    "commit-sha": "4fa90e1518b2bfc02e9f99beecc2efb1e102c4ff"
  },
  {
    "project": "enforcerd-expand-integ",
    "component": "trireme-lib",
    "pr-id": "836",
    "commit-sha": "270fc9bbe43cbf398b3693a3c1ecb88a0dc8cbe1"
  },
  {
    "project": "enforcerd-expand-integ",
    "component": "integrations-lib",
    "pr-id": "121",
    "commit-sha": "5fb39da3c83260bd67b5b62c916ffbb224f419a3"
  }
]
```

**Review by sibicramesh — APPROVED** [review]
sorry.:)

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "enforcerd-expand-integ",
    "component": "enforcerd",
    "pr-id": "1290",
    "commit-sha": "4fa90e1518b2bfc02e9f99beecc2efb1e102c4ff"
  },
  {
    "project": "enforcerd-expand-integ",
    "component": "trireme-lib",
    "pr-id": "836",
    "commit-sha": "b40a4e7d9280dea8f4edaa391776cddd15c3f66d"
  },
  {
    "project": "enforcerd-expand-integ",
    "component": "integrations-lib",
    "pr-id": "121",
    "commit-sha": "5fb39da3c83260bd67b5b62c916ffbb224f419a3"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "enforcerd-expand-integ",
    "component": "enforcerd",
    "pr-id": "1290",
    "commit-sha": "58fa16496ce27fd54eeafff28547824cf9ce7ba1"
  },
  {
    "project": "enforcerd-expand-integ",
    "component": "trireme-lib",
    "pr-id": "836",
    "commit-sha": "b40a4e7d9280dea8f4edaa391776cddd15c3f66d"
  },
  {
    "project": "enforcerd-expand-integ",
    "component": "integrations-lib",
    "pr-id": "121",
    "commit-sha": "cb60d649baab8a3d45ec91a84251327673edd2bd"
  }
]
```

**Pull request merged**
