### PR TITLE
support panic recovery for go routines.

### PR DESCRIPTION
**Pull request by varks**
When Go routines panic, recover and capture stack trace in stackdriver format.

### CODE REVIEW

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "component": "enforcerd",
    "pr-id": "570",
    "commit-sha": "f6f6c10d161c7606096020a3402aa9e9bedd1795"
  },
  {
    "component": "trireme-lib",
    "pr-id": "516",
    "commit-sha": "7a3a60153434e7f9c7a802b295d96c905eb542c3"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "component": "trireme-lib",
    "pr-id": "516",
    "commit-sha": "7a3a60153434e7f9c7a802b295d96c905eb542c3"
  },
  {
    "component": "enforcerd",
    "pr-id": "570",
    "commit-sha": "dce37773c79df72a4e602e2b53123e2c39e51711"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "component": "netlink-go",
    "pr-id": "30",
    "commit-sha": "9b4776a4311d022fbea7019ef0763452990c04a9"
  },
  {
    "component": "trireme-lib",
    "pr-id": "516",
    "commit-sha": "7a3a60153434e7f9c7a802b295d96c905eb542c3"
  },
  {
    "component": "enforcerd",
    "pr-id": "570",
    "commit-sha": "dce37773c79df72a4e602e2b53123e2c39e51711"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "component": "netlink-go",
    "pr-id": "30",
    "commit-sha": "9b4776a4311d022fbea7019ef0763452990c04a9"
  },
  {
    "component": "trireme-lib",
    "pr-id": "516",
    "commit-sha": "f0c2865bc73bfb14be052ef2327be12ba255b855"
  },
  {
    "component": "enforcerd",
    "pr-id": "570",
    "commit-sha": "03d4af2ca75370b88dd2e16ef0032cd9635b42c5"
  }
]
```

**Comment by satyamsi** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "panic_recovery",
    "component": "netlink-go",
    "pr-id": "30",
    "commit-sha": "9b4776a4311d022fbea7019ef0763452990c04a9"
  },
  {
    "project": "panic_recovery",
    "component": "trireme-lib",
    "pr-id": "516",
    "commit-sha": "f0c2865bc73bfb14be052ef2327be12ba255b855"
  },
  {
    "project": "panic_recovery",
    "component": "enforcerd",
    "pr-id": "570",
    "commit-sha": "03d4af2ca75370b88dd2e16ef0032cd9635b42c5"
  }
]
```

**Comment by satyamsi** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "panic_recovery",
    "component": "enforcerd",
    "pr-id": "570",
    "commit-sha": "03d4af2ca75370b88dd2e16ef0032cd9635b42c5"
  },
  {
    "project": "panic_recovery",
    "component": "netlink-go",
    "pr-id": "30",
    "commit-sha": "9b4776a4311d022fbea7019ef0763452990c04a9"
  },
  {
    "project": "panic_recovery",
    "component": "trireme-lib",
    "pr-id": "516",
    "commit-sha": "f0c2865bc73bfb14be052ef2327be12ba255b855"
  }
]
```

**Comment by satyamsi** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "panic_recovery",
    "component": "trireme-lib",
    "pr-id": "516",
    "commit-sha": "f0c2865bc73bfb14be052ef2327be12ba255b855"
  },
  {
    "project": "panic_recovery",
    "component": "enforcerd",
    "pr-id": "570",
    "commit-sha": "03d4af2ca75370b88dd2e16ef0032cd9635b42c5"
  },
  {
    "project": "panic_recovery",
    "component": "netlink-go",
    "pr-id": "30",
    "commit-sha": "9b4776a4311d022fbea7019ef0763452990c04a9"
  }
]
```

**Comment by satyamsi** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "panic_recovery",
    "component": "netlink-go",
    "pr-id": "30",
    "commit-sha": "9b4776a4311d022fbea7019ef0763452990c04a9"
  },
  {
    "project": "panic_recovery",
    "component": "trireme-lib",
    "pr-id": "516",
    "commit-sha": "f0c2865bc73bfb14be052ef2327be12ba255b855"
  },
  {
    "project": "panic_recovery",
    "component": "enforcerd",
    "pr-id": "570",
    "commit-sha": "03d4af2ca75370b88dd2e16ef0032cd9635b42c5"
  }
]
```

**Comment by satyamsi** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "panic_recovery",
    "component": "netlink-go",
    "pr-id": "30",
    "commit-sha": "9b4776a4311d022fbea7019ef0763452990c04a9"
  },
  {
    "project": "panic_recovery",
    "component": "trireme-lib",
    "pr-id": "516",
    "commit-sha": "f0c2865bc73bfb14be052ef2327be12ba255b855"
  },
  {
    "project": "panic_recovery",
    "component": "enforcerd",
    "pr-id": "570",
    "commit-sha": "03d4af2ca75370b88dd2e16ef0032cd9635b42c5"
  }
]
```

**Comment by dstiliadis** [comment]
What's the state of this?

**Pull request closed without merging**
