### PR TITLE
Add uidpam/host network service for older kernels.

### PR DESCRIPTION
**Pull request by varks**
This PR supports host network services and uidpam PUs on older kernels without cgroup match support. The outgoing traffic for network services is now trapped based on source port rather than cgroup match. RH 6.x now supports 1) Whole VM protection (host mode) 2) Host network services 3) UID pus.

### CODE REVIEW

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "679",
    "commit-sha": "d986b93bea97303790681f6b385816bb500dc224"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "rhel_support",
    "component": "trireme-lib",
    "pr-id": "679",
    "commit-sha": "645bd2994b04f976cc3f85c79c88ca659c7ebd45"
  },
  {
    "project": "rhel_support",
    "component": "enforcerd",
    "pr-id": "897",
    "commit-sha": "f0ae36a22c8bcba145dbfe9e7be2d425f09e65fe"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "rhel_support",
    "component": "trireme-lib",
    "pr-id": "679",
    "commit-sha": "13b217de42d173738fdf7d1d427152c07b0a5837"
  },
  {
    "project": "rhel_support",
    "component": "enforcerd",
    "pr-id": "897",
    "commit-sha": "061e5231a102a4f887b91b6b3da56d88b87ec065"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "rhel_support",
    "component": "trireme-lib",
    "pr-id": "679",
    "commit-sha": "13b217de42d173738fdf7d1d427152c07b0a5837"
  },
  {
    "project": "rhel_support",
    "component": "enforcerd",
    "pr-id": "897",
    "commit-sha": "1edc6f50474f412a48ca2afc0fba2d73913b946f"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "rhel_support",
    "component": "trireme-lib",
    "pr-id": "679",
    "commit-sha": "3f48fbf7974ae412e9f4269700aa07284c4a5a23"
  },
  {
    "project": "rhel_support",
    "component": "enforcerd",
    "pr-id": "897",
    "commit-sha": "1edc6f50474f412a48ca2afc0fba2d73913b946f"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "rhel_support",
    "component": "trireme-lib",
    "pr-id": "679",
    "commit-sha": "3f48fbf7974ae412e9f4269700aa07284c4a5a23"
  },
  {
    "project": "rhel_support",
    "component": "enforcerd",
    "pr-id": "897",
    "commit-sha": "590fbfdffa7f84a66ab27d9c55fe72fec3c39c44"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "rhel_support",
    "component": "trireme-lib",
    "pr-id": "679",
    "commit-sha": "89381b992b350818243d8fcca3db1dc2bce8cf82"
  },
  {
    "project": "rhel_support",
    "component": "enforcerd",
    "pr-id": "897",
    "commit-sha": "161a9c0b3560f2ee460ca48e8b280f54cc7e99bd"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "rhel_support",
    "component": "trireme-lib",
    "pr-id": "679",
    "commit-sha": "e3733939c9418f1354ac1d4adef0a6ad08a0ce0c"
  },
  {
    "project": "rhel_support",
    "component": "enforcerd",
    "pr-id": "897",
    "commit-sha": "161a9c0b3560f2ee460ca48e8b280f54cc7e99bd"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "rhel_support",
    "component": "trireme-lib",
    "pr-id": "679",
    "commit-sha": "e3733939c9418f1354ac1d4adef0a6ad08a0ce0c"
  },
  {
    "project": "rhel_support",
    "component": "enforcerd",
    "pr-id": "897",
    "commit-sha": "161a9c0b3560f2ee460ca48e8b280f54cc7e99bd"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "rhel_support",
    "component": "trireme-lib",
    "pr-id": "679",
    "commit-sha": "e3733939c9418f1354ac1d4adef0a6ad08a0ce0c"
  },
  {
    "project": "rhel_support",
    "component": "enforcerd",
    "pr-id": "897",
    "commit-sha": "161a9c0b3560f2ee460ca48e8b280f54cc7e99bd"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "rhel_support",
    "component": "trireme-lib",
    "pr-id": "679",
    "commit-sha": "e3733939c9418f1354ac1d4adef0a6ad08a0ce0c"
  },
  {
    "project": "rhel_support",
    "component": "enforcerd",
    "pr-id": "897",
    "commit-sha": "f17932860d396b6e2b01a7f6452f0183508ac4ca"
  }
]
```

**Review by amitlimaye — APPROVED** [review]

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "rhel_support",
    "component": "enforcerd",
    "pr-id": "897",
    "commit-sha": "2e46131cf317b0acbbe0ab672e20e6a999c62a3c"
  },
  {
    "project": "rhel_support",
    "component": "trireme-lib",
    "pr-id": "679",
    "commit-sha": "85df1054943153ab4b8df3e2c117c8c1d041bda0"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "679",
    "commit-sha": "96fcf292e3ae14cfd5c9a9984f4530311318dec5"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "679",
    "commit-sha": "fc28f441f86c9619b15cd954e36b19cdbd78daa1"
  }
]
```

**Pull request merged**
