### PR TITLE
Reliability of UDP implementation

### PR DESCRIPTION
**Pull request by dstiliadis**
#### Description
Improves the reliability of UDP operations by introducing re-transmissions and timers. The protocol works like below:

1. When client starts a UDP packet, a Syn authorization packet is transmitted. A timer is started in a go-routing to send additional authorization packets if no response is received.

2. When the packet is received at the server, it responds with its authorization header and starts another timer to retransmit. 

3. When the client or servers receive a response, they stop their retransmission processes. 

4. If the last packet (with the signature on the nonces) is lost, the receiver will send its packet again and kick of a new sequence and the send will have to respond. When the final packet is received by the receiver it will cancel its retransmissions.

### CODE REVIEW

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "udp-rx",
    "component": "trireme-lib",
    "pr-id": "607",
    "commit-sha": "9f5452b8f54e5160fa87cbece250db1dcf64237f"
  },
  {
    "project": "udp-rx",
    "component": "enforcerd",
    "pr-id": "758",
    "commit-sha": "e4329772a4f287479fc30582207af89eccda8457"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "udp-rx",
    "component": "trireme-lib",
    "pr-id": "607",
    "commit-sha": "0cc4cee3b5b274faf3ae90e9c4ee8981f5966f08"
  },
  {
    "project": "udp-rx",
    "component": "enforcerd",
    "pr-id": "758",
    "commit-sha": "e4329772a4f287479fc30582207af89eccda8457"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "udp-rx",
    "component": "trireme-lib",
    "pr-id": "607",
    "commit-sha": "0cc4cee3b5b274faf3ae90e9c4ee8981f5966f08"
  },
  {
    "project": "udp-rx",
    "component": "enforcerd",
    "pr-id": "758",
    "commit-sha": "0214c01993ecc0b677f042656debdc6c9bcb1207"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "udp-rx",
    "component": "trireme-lib",
    "pr-id": "607",
    "commit-sha": "0cc4cee3b5b274faf3ae90e9c4ee8981f5966f08"
  },
  {
    "project": "udp-rx",
    "component": "enforcerd",
    "pr-id": "758",
    "commit-sha": "0214c01993ecc0b677f042656debdc6c9bcb1207"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "udp-rx",
    "component": "trireme-lib",
    "pr-id": "607",
    "commit-sha": "6255af384075e1dbdcc1072eda800e13a9aacb8f"
  },
  {
    "project": "udp-rx",
    "component": "enforcerd",
    "pr-id": "758",
    "commit-sha": "8928967078330ef9c6083eca23af7e2ad34d6053"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "udp-rx",
    "component": "trireme-lib",
    "pr-id": "607",
    "commit-sha": "679c90e76db2a8b533796fdbf70b1311b1842bb1"
  },
  {
    "project": "udp-rx",
    "component": "enforcerd",
    "pr-id": "758",
    "commit-sha": "8928967078330ef9c6083eca23af7e2ad34d6053"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "udp-rx",
    "component": "trireme-lib",
    "pr-id": "607",
    "commit-sha": "548902335a97c10b2db2d0a0ad381ce0f20e9fac"
  },
  {
    "project": "udp-rx",
    "component": "enforcerd",
    "pr-id": "758",
    "commit-sha": "db63729af412b1a34509eec9e3cdc11758dfa644"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "udp-rx",
    "component": "trireme-lib",
    "pr-id": "607",
    "commit-sha": "d74a4fb1ef1cc5b14de588d36e55159c9a567ff3"
  },
  {
    "project": "udp-rx",
    "component": "enforcerd",
    "pr-id": "758",
    "commit-sha": "a92f900d4f095a0c2230c1c0984920b51c32ce9b"
  }
]
```

**Comment by ghost** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "udp-rx",
    "component": "trireme-lib",
    "pr-id": "607",
    "commit-sha": "3134c20f9adbb62369086c340a1397b8a0eaf7fc"
  },
  {
    "project": "udp-rx",
    "component": "enforcerd",
    "pr-id": "758",
    "commit-sha": "c83c2fcf86fb31b266b7aaa73933c82dd75847d0"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "udp-rx",
    "component": "trireme-lib",
    "pr-id": "607",
    "commit-sha": "3134c20f9adbb62369086c340a1397b8a0eaf7fc"
  },
  {
    "project": "udp-rx",
    "component": "enforcerd",
    "pr-id": "758",
    "commit-sha": "c83c2fcf86fb31b266b7aaa73933c82dd75847d0"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "udp-rx",
    "component": "trireme-lib",
    "pr-id": "607",
    "commit-sha": "3134c20f9adbb62369086c340a1397b8a0eaf7fc"
  },
  {
    "project": "udp-rx",
    "component": "enforcerd",
    "pr-id": "758",
    "commit-sha": "c83c2fcf86fb31b266b7aaa73933c82dd75847d0"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "udp-rx",
    "component": "trireme-lib",
    "pr-id": "607",
    "commit-sha": "3134c20f9adbb62369086c340a1397b8a0eaf7fc"
  },
  {
    "project": "udp-rx",
    "component": "enforcerd",
    "pr-id": "758",
    "commit-sha": "c83c2fcf86fb31b266b7aaa73933c82dd75847d0"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "udp-rx",
    "component": "enforcerd",
    "pr-id": "758",
    "commit-sha": "934bc21417f5fcc5f591dcc4a01da69302d47fed"
  },
  {
    "project": "udp-rx",
    "component": "trireme-lib",
    "pr-id": "607",
    "commit-sha": "3134c20f9adbb62369086c340a1397b8a0eaf7fc"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "udp-rx",
    "component": "trireme-lib",
    "pr-id": "607",
    "commit-sha": "4a405210383818e3caa64fe4009cc4d63ff317fd"
  },
  {
    "project": "udp-rx",
    "component": "enforcerd",
    "pr-id": "758",
    "commit-sha": "934bc21417f5fcc5f591dcc4a01da69302d47fed"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "udp-rx",
    "component": "trireme-lib",
    "pr-id": "607",
    "commit-sha": "4a405210383818e3caa64fe4009cc4d63ff317fd"
  },
  {
    "project": "udp-rx",
    "component": "enforcerd",
    "pr-id": "758",
    "commit-sha": "934bc21417f5fcc5f591dcc4a01da69302d47fed"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "udp-rx",
    "component": "trireme-lib",
    "pr-id": "607",
    "commit-sha": "4a405210383818e3caa64fe4009cc4d63ff317fd"
  },
  {
    "project": "udp-rx",
    "component": "enforcerd",
    "pr-id": "758",
    "commit-sha": "934bc21417f5fcc5f591dcc4a01da69302d47fed"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "udp-rx",
    "component": "trireme-lib",
    "pr-id": "607",
    "commit-sha": "4a405210383818e3caa64fe4009cc4d63ff317fd"
  },
  {
    "project": "udp-rx",
    "component": "enforcerd",
    "pr-id": "758",
    "commit-sha": "934bc21417f5fcc5f591dcc4a01da69302d47fed"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "udp-rx",
    "component": "trireme-lib",
    "pr-id": "607",
    "commit-sha": "4a405210383818e3caa64fe4009cc4d63ff317fd"
  },
  {
    "project": "udp-rx",
    "component": "enforcerd",
    "pr-id": "758",
    "commit-sha": "934bc21417f5fcc5f591dcc4a01da69302d47fed"
  }
]
```

**Review by varks — APPROVED** [review]

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "udp-rx",
    "component": "trireme-lib",
    "pr-id": "607",
    "commit-sha": "4a405210383818e3caa64fe4009cc4d63ff317fd"
  },
  {
    "project": "udp-rx",
    "component": "enforcerd",
    "pr-id": "758",
    "commit-sha": "d5730747c399ab863c89491d71675e6a9dc93c68"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "udp-rx",
    "component": "trireme-lib",
    "pr-id": "607",
    "commit-sha": "4a405210383818e3caa64fe4009cc4d63ff317fd"
  },
  {
    "project": "udp-rx",
    "component": "enforcerd",
    "pr-id": "758",
    "commit-sha": "d5730747c399ab863c89491d71675e6a9dc93c68"
  }
]
```

**Comment by varks** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "trireme-lib",
    "pr-id": "607",
    "commit-sha": "9ce5e350f397461e20ebde8be17db4da10edfbff"
  }
]
```

**Pull request merged**
